function populatetrackinfo(obj)

%%%% aggiornare col CUBBONE
DetectorList = obj.Track.Channel;
TrackList = obj.Track.List;
%%%%%%%%

obj.TrackInfo.ChannelLabel = uicontrol('Parent', obj.MainInfo.TabTrack, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.85 0.35 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Channel');
obj.TrackInfo.Channel = uicontrol('Parent', obj.MainInfo.TabTrack, ...
    'Style', 'listbox', ...
    'Units', 'normalized',...
    'Position', [0.1 0.45 0.35 0.4],...
    'String', DetectorList, ...
    'Value', [], ...
    'Max', 2, ...
    'Visible', 'on', ...
    'Callback', @(h,e)channel_callback(h,e,obj));

obj.TrackInfo.TrackListLabel = uicontrol('Parent', obj.MainInfo.TabTrack, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.55 0.85 0.35 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Tracks');
obj.TrackInfo.TrackList = uicontrol('Parent', obj.MainInfo.TabTrack, ...
    'Style', 'listbox', ...
    'Units', 'normalized',...
    'Position', [0.55 0.45 0.35 0.4],...
    'String', TrackList, ...
    'Value', [], ...
    'Max', 2, ...
    'Visible', 'on', ...
    'Callback', @(h,e)track_list_callback(h,e,obj));

obj.TrackInfo.TrackCheckbox = uicontrol('Parent', obj.MainInfo.TabTrack, ...
    'Style', 'checkbox', ...
    'Units', 'normalized',...
    'Position', [0.1 0.25 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Track Visibility', ...
    'Callback', @(h,e)track_checkbox_callback(h,e,obj));

obj.TrackInfo.TimeSeriesPanel = uipanel('Parent', obj.MainInfo.TabTrack,...
    'Units', 'normalized', ...
    'BorderType', 'none', ...
    'Position', [0.1 0.02 0.8 0.2]);

obj.TrackInfo.TimeSeriesLabel = uicontrol('Parent', obj.TrackInfo.TimeSeriesPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0 0.9 1 0.1],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Tracks plot');

obj.TrackInfo.TimeSeriesAxes = axes('Parent', obj.TrackInfo.TimeSeriesPanel, ...
    'Units', 'normalized', ...
    'NextPlot', 'add', ...
    'Position', [0.15 0.1 0.85 0.7], ...
    'Visible', 'on');

obj.TrackInfo.TimeSeries = plot(obj.TrackInfo.TimeSeriesAxes, ...
    reshape(obj.Track.Value,size(obj.Track.Value,1),[]));

obj.TrackInfo.TimePointVertical = plot([50 50], get(obj.TrackInfo.TimeSeriesAxes, 'YLim'), 'Color', 'k');

obj.TrackInfo.ChannelActive = [];
obj.TrackInfo.TrackActive = [];
end

function channel_callback(h, ~, obj)

if all(obj.TrackInfo.Channel' == h.Value, 'all') && ~isempty(obj.TrackInfo.ChannelActive)
    h.Value = [];
end
Viewer3D.trackrefresh([],[],obj);
obj.TrackInfo.ChannelActive = h.Value;
end

function track_list_callback(h, ~, obj)

if all(obj.TrackInfo.TrackList' == h.Value,'all') && ~isempty(obj.TrackInfo.TrackActive)
    h.Value = [];
end
Viewer3D.trackrefresh([],[],obj);
obj.TrackInfo.TrackActive = h.Value;
end

function track_checkbox_callback(h, ~, obj)

if h.Value
    obj.ForwardInfo.PhotonCheckbox.Value = false;
end
Viewer3D.trackrefresh([],[],obj)
end




