function populateatlasinfo(obj)

obj.AtlasInfo.ScalpAlphaLabel = uicontrol('Parent', obj.MainInfo.TabAtlas, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.95 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Scalp Alpha [0-1]' ...
    );
obj.AtlasInfo.ScalpAlphaEdit = uicontrol('Parent', obj.MainInfo.TabAtlas, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.91 0.8 0.04],...
    'Visible', 'on', ...
    'String', '0.1', ...
    'Callback', @(h,e)scalp_alpha_callback(h,e,obj));

obj.AtlasInfo.GreyMatterAlphaLabel = uicontrol('Parent', obj.MainInfo.TabAtlas, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.85 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'GreyMatter Alpha [0-1]' ...
    );
obj.AtlasInfo.GreyMatterAlphaEdit = uicontrol('Parent', obj.MainInfo.TabAtlas, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.81 0.8 0.04],...
    'Visible', 'on', ...
    'String', '1', ...
    'Callback', @(h,e)greymatter_alpha_callback(h,e,obj));

obj.AtlasInfo.WhiteMatterAlphaLabel = uicontrol('Parent', obj.MainInfo.TabAtlas, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.75 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'WhiteMatter Alpha [0-1]' ...
    );
obj.AtlasInfo.WhiteMatterAlphaEdit = uicontrol('Parent', obj.MainInfo.TabAtlas, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.71 0.8 0.04],...
    'Visible', 'on', ...
    'String', '0', ...
    'Callback', @(h,e)whitematter_alpha_callback(h,e,obj));







obj.AtlasInfo.LandMarkTextCheckbox = uicontrol('Parent', obj.MainInfo.TabAtlas, ...
    'Style', 'checkbox', ...
    'Units', 'normalized',...
    'Position', [0.1 0.35 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Landmark Labels', ...
    'Value', false, ...
    'Callback', @(h,e)landmark_text_callback(h,e,obj));

obj.AtlasInfo.LandMarkCheckbox = uicontrol('Parent', obj.MainInfo.TabAtlas, ...
    'Style', 'checkbox', ...
    'Units', 'normalized',...
    'Position', [0.1 0.3 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Main Landmark', ...
    'Value', false, ...
    'Callback', @(h,e)landmark_callback(h,e,obj));

obj.AtlasInfo.LandMarkSmallCheckbox = uicontrol('Parent', obj.MainInfo.TabAtlas, ...
    'Style', 'checkbox', ...
    'Units', 'normalized',...
    'Position', [0.1 0.25 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'Value', false, ...
    'String', 'All Landmark', ...
    'Callback',@(h,e)landmark_small_callback(h,e,obj));

end

function scalp_alpha_callback(h,~,obj)
obj.AtlasPlot.Scalp.FaceAlpha = min(max(str2double(h.String),0),1);
end
function greymatter_alpha_callback(h,~,obj)
obj.AtlasPlot.GreyMatter.FaceAlpha = min(max(str2double(h.String),0),1);
end

function whitematter_alpha_callback(h,~,obj)
obj.AtlasPlot.WhiteMatter.FaceAlpha = min(max(str2double(h.String),0),1);
end

function landmark_text_callback(h,~,obj)
if (h.Value)
    set(obj.AtlasPlot.LandMarkText,'Visible','on');
else
    set(obj.AtlasPlot.LandMarkText,'Visible','off');
end
end

function landmark_callback(h,~,obj)
if (h.Value)
    set(obj.AtlasPlot.LandMark,'Visible','on');
else
    set(obj.AtlasPlot.LandMark,'Visible','off');
end
end

function landmark_small_callback(h,~,obj)
if (h.Value)
    set(obj.AtlasPlot.LandMarkSmall,'Visible','on');
else
    set(obj.AtlasPlot.LandMarkSmall,'Visible','off');
end
end
