function populateatlasplot(obj)
landMarkColor = [0 0.6 0.2];
landMarkColorSmall = [0.2 1 0.47];
scalpColor = [0.7 0.7 0.7];
greyMatter = [1 1 1];
whiteMatter = [0 0.2 0.2];


obj.AtlasPlot.Scalp = trisurf(...
    obj.Atlas.Scalp.face, ...
    obj.Atlas.Scalp.node(:,1), obj.Atlas.Scalp.node(:,2), obj.Atlas.Scalp.node(:,3), ...
    ones(size(obj.Atlas.Scalp.node(:,3))), ...
    'SpecularStrength', 0, ...
    'EdgeColor', 'none', ...
    'Parent',obj.MainPlot.Axes,...
    'FaceColor', scalpColor, ...
    'FaceAlpha' ,0.1, ...
    'FaceLighting', 'gouraud');

obj.AtlasPlot.GreyMatter = trisurf(...
    obj.Atlas.GreyMatter.face, ...
    obj.Atlas.GreyMatter.node(:,1), obj.Atlas.GreyMatter.node(:,2), obj.Atlas.GreyMatter.node(:,3), ...
    ones(size(obj.Atlas.GreyMatter.node(:,3))), ...
    'Parent',obj.MainPlot.Axes,...
    'SpecularStrength', 0, ...
    'EdgeColor', 'none', ...
    'FaceColor', greyMatter, ...
    'FaceAlpha', 1, ...
    'FaceLighting', 'gouraud');

obj.AtlasPlot.WhiteMatter = trisurf(...
    obj.Atlas.WhiteMatter.face, ...
    obj.Atlas.WhiteMatter.node(:,1), obj.Atlas.WhiteMatter.node(:,2), obj.Atlas.WhiteMatter.node(:,3), ...
    ones(size(obj.Atlas.WhiteMatter.node(:,3))), ...
    'Parent',obj.MainPlot.Axes,...
    'SpecularStrength', 0, ...
    'EdgeColor', 'none', ...
    'FaceColor', whiteMatter, ...
    'FaceAlpha', 0, ...
    'FaceLighting', 'gouraud');


x = reshape(obj.Atlas.LandMarks.coord(:,:,1), [],1);
y = reshape(obj.Atlas.LandMarks.coord(:,:,2), [],1);
z = reshape(obj.Atlas.LandMarks.coord(:,:,3), [],1);
landmarkNames = reshape(obj.Atlas.LandMarks.names(:,:), [], 1);
iMask = find(~cellfun('isempty', landmarkNames));
obj.AtlasPlot.LandMarkSmall = plot3(...
    x(iMask), y(iMask), z(iMask),...
    'MarkerSize',5,...
    'LineStyle', 'none',...
    'Visible', 'off',...
    'Marker','.',...
    'Color',landMarkColorSmall,...
    'Parent', obj.MainPlot.Axes);

stepIdx = linspace(1,size(obj.Atlas.LandMarks.coord,1),21);
x = reshape(obj.Atlas.LandMarks.coord(stepIdx,stepIdx,1), [],1);
y = reshape(obj.Atlas.LandMarks.coord(stepIdx,stepIdx,2), [],1);
z = reshape(obj.Atlas.LandMarks.coord(stepIdx,stepIdx,3), [],1);
landmarkNames = reshape(obj.Atlas.LandMarks.names(stepIdx,stepIdx), [], 1);
iMask = find(~cellfun('isempty', landmarkNames));

obj.AtlasPlot.LandMark = plot3(...
    x(iMask), y(iMask), z(iMask),...
    'MarkerSize',20,...
    'LineStyle', 'none',...
    'Visible', 'off',...
    'Marker','.',...
    'Color',landMarkColor,...
    'Parent', obj.MainPlot.Axes);

obj.AtlasPlot.LandMarkText = text(...
    obj.MainPlot.Axes,...
    x(iMask), y(iMask), z(iMask),...
    landmarkNames(iMask),...
    'Color', landMarkColor,...
    'FontWeight', 'bold',...
    'Visible', 'off');

end
