function populatetracksetting(obj)
obj.MainSetting.Panel.Children.delete;

obj.TrackSetting.DownSamplingLabel = uicontrol('Parent', obj.MainSetting.Panel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.95 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Downsampling Factor [> 1]');
obj.TrackSetting.DownSampling = uicontrol('Parent', obj.MainSetting.Panel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.91 0.8 0.04],...
    'String', '10', ...
    'Visible', 'on', ...
    'Callback', @(h,e)Viewer3D.trackrefresh(h,e,obj));

obj.TrackSetting.MaxMarkerSizeLabel = uicontrol('Parent', obj.MainSetting.Panel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.85 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Max Marker Size');
obj.TrackSetting.MaxMarkerSize = uicontrol('Parent', obj.MainSetting.Panel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.81 0.8 0.04],...
    'String', '10', ...
    'Visible', 'on', ...
    'Callback', @(h,e)Viewer3D.trackrefresh(h,e,obj));

obj.TrackSetting.AngleLabel = uicontrol('Parent', obj.MainSetting.Panel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.75 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Plane cut angles');
obj.TrackSetting.Angle1 = uicontrol('Parent', obj.MainSetting.Panel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.71 0.35 0.04],...
    'String', '0', ...
    'Visible', 'on', ...
    'Callback', @(h,e)Viewer3D.photonrefresh(h,e,obj));
obj.TrackSetting.Angle2 = uicontrol('Parent', obj.MainSetting.Panel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.55 0.71 0.35 0.04],...
    'String', '0', ...
    'Visible', 'on', ...
    'Callback', @(h,e)Viewer3D.trackrefresh(h,e,obj));

obj.TrackSetting.ThresholdLabel = uicontrol('Parent', obj.MainSetting.Panel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.65 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Threshold');
obj.TrackSetting.Threshold = uicontrol('Parent', obj.MainSetting.Panel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.61 0.8 0.04],...
    'String', '-6', ...
    'Visible', 'on', ...
    'Callback', @(h,e)Viewer3D.trackrefresh(h,e,obj));

obj.TrackSetting.ColormapLabel = uicontrol('Parent', obj.MainSetting.Panel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.55 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Colormap');
obj.TrackSetting.Colormap = uicontrol('Parent', obj.MainSetting.Panel, ...
    'Style', 'popup', ...
    'Units', 'normalized',...
    'Position', [0.1 0.51 0.8 0.04],...
    'String', {'parula'; 'hsv'; 'hot'; 'gray'; 'bone'; ...
    'copper';'pink'; 'white'; 'flag';  'lines'; ...
    'colorcube';'jet'; 'prism'; 'cool'; ...
    'autumn'; 'spring'; 'winter';'summer'}, ...
    'Visible', 'on', ...
    'Callback', @(h,e)Viewer3D.trackrefresh(h,e,obj));

obj.TrackSetting.ScaleLabel = uicontrol('Parent', obj.MainSetting.Panel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.45 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Scale');
obj.TrackSetting.Scale = uicontrol('Parent', obj.MainSetting.Panel, ...
    'Style', 'popup', ...
    'Units', 'normalized',...
    'Position', [0.1 0.41 0.8 0.04],...
    'String', {'linear'; 'log10'; 'log'; 'exp'; 'sqrt'; 'cube root'}, ...
    'Value', 2, ...
    'Visible', 'on', ...
    'Callback', @(h,e)Viewer3D.trackrefresh(h,e,obj));


obj.TrackSetting.TimeSliderLabel = uicontrol('Parent', obj.MainSetting.Panel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.35 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Time Slider');

obj.TrackSetting.TimeSliderLabel = uicontrol('Parent', obj.MainSetting.Panel, ...
    'Style', 'slider', ...
    'Units', 'normalized',...
    'Position', [0.1 0.31 0.8 0.04],...
    'SliderStep', [0.01 0.1], ...
    'Visible', 'on', ...
    'Callback', @(h,e)Viewer3D.trackrefresh(h,e,obj));


end

