function populateprobeinfo(obj)
obj.ProbeInfo.DataTypeLabel = uicontrol('Parent', obj.MainInfo.TabProbe, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.95 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'String', 'Data type');
obj.ProbeInfo.DataType = uicontrol('Parent', obj.MainInfo.TabProbe, ...
    'Style', 'popup', ...
    'Units', 'normalized',...
    'Position', [0.1 0.9 0.8 0.05],...
    'String', {'SrcDet'; 'Channels'}, ...
    'Callback', @(h,e)switch_datatype(h,e,obj));

obj.ProbeInfo.SrcListLabel = uicontrol('Parent', obj.MainInfo.TabProbe, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.85 0.35 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Sources');
obj.ProbeInfo.SrcList = uicontrol('Parent', obj.MainInfo.TabProbe, ...
    'Style', 'listbox', ...
    'Units', 'normalized',...
    'Position', [0.1 0.45 0.35 0.4],...
    'String', obj.Probe.source.label, ...
    'Value', [], ...
    'Max', 2, ...
    'Visible', 'on', ...
    'Callback', @(h,e)srclist_callback(h,e,obj));

obj.ProbeInfo.DetListLabel = uicontrol('Parent', obj.MainInfo.TabProbe, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.55 0.85 0.35 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Detectors');
obj.ProbeInfo.DetList = uicontrol('Parent', obj.MainInfo.TabProbe, ...
    'Style', 'listbox', ...
    'Units', 'normalized',...
    'Position', [0.55 0.45 0.35 0.4],...
    'String', obj.Probe.detector.label, ...
    'Value', [], ...
    'Max', 2, ...
    'Visible', 'on', ...
    'Callback', @(h,e)detlist_callback(h,e,obj));

obj.ProbeInfo.ChannelListLabel = uicontrol('Parent', obj.MainInfo.TabProbe, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.85 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'off', ...
    'String', 'Channels');
obj.ProbeInfo.ChannelList = uicontrol('Parent', obj.MainInfo.TabProbe, ...
    'Style', 'listbox', ...
    'Units', 'normalized',...
    'Position', [0.1 0.45 0.8 0.4],...
    'String', obj.Probe.channel.label, ...
    'Max', 2, ...
    'Value', [], ...
    'Visible', 'off', ...
    'Callback', @(h,e)channellist_callback(h,e,obj));

obj.ProbeInfo.OptodeCheckbox = uicontrol('Parent', obj.MainInfo.TabProbe, ...
    'Style', 'checkbox', ...
    'Units', 'normalized',...
    'Position', [0.1 0.35 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Optodes', ...
    'Value', true, ...
    'Callback', @(h,e)optode_checkbox(h,e,obj));
obj.ProbeInfo.ArrowCheckbox = uicontrol('Parent', obj.MainInfo.TabProbe, ...
    'Style', 'checkbox', ...
    'Units', 'normalized',...
    'Position', [0.1 0.3 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Direction', ...
    'Value', false, ...
    'Callback', @(h,e)arrow_checkbox(h,e,obj));
obj.ProbeInfo.PhotonCheckbox = uicontrol('Parent', obj.MainInfo.TabProbe, ...
    'Style', 'checkbox', ...
    'Units', 'normalized',...
    'Position', [0.1 0.25 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Photon density', ...
    'Callback', @(h,e)ViewForward.photonrefresh(h,e,obj));
obj.ProbeInfo.ExtraInfoButton = uicontrol('Parent', obj.MainInfo.TabProbe, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized',...
    'Position', [0.1 0.1 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Forward Details', ...
    'Callback', @(h,e)ViewForward.extrainfo(h,e,obj));

obj.ProbeInfo.SrcActive = [];
obj.ProbeInfo.DetActive = [];
obj.ProbeInfo.ChannelActive = [];
end

function switch_datatype(h, ~, obj)
if h.Value == 1
    obj.ProbeInfo.SrcListLabel.Visible = 'on';
    obj.ProbeInfo.SrcList.Visible = 'on';
    obj.ProbeInfo.DetListLabel.Visible = 'on';
    obj.ProbeInfo.DetList.Visible = 'on';
    obj.ProbeInfo.ChannelList.Visible = 'off';
    obj.ProbeInfo.ChannelListLabel.Visible = 'off';
else
    obj.ProbeInfo.SrcListLabel.Visible = 'off';
    obj.ProbeInfo.SrcList.Visible = 'off';
    obj.ProbeInfo.DetListLabel.Visible = 'off';
    obj.ProbeInfo.DetList.Visible = 'off';
    obj.ProbeInfo.ChannelList.Visible = 'on';
    obj.ProbeInfo.ChannelListLabel.Visible = 'on';
end
end

function srclist_callback(h, ~, obj)
colorOn = 'r';
colorOff = [0.2 0 0];
if all(obj.ProbeInfo.SrcActive' == h.Value, 'all') && ~isempty(obj.ProbeInfo.SrcActive)
    h.Value = [];
end
set(obj.ForwardPlot.SourceOptode, 'Color', colorOff);
set(obj.ForwardPlot.SourceOptode(h.Value), 'Color', colorOn);
set(obj.ForwardPlot.SrcDirectionArrow, 'FaceColor', colorOff);
set(obj.ForwardPlot.SrcDirectionArrow(h.Value), 'FaceColor', colorOn);
ViewForward.photonrefresh([],[],obj);
obj.ProbeInfo.SrcActive = h.Value;
end

function detlist_callback(h, ~, obj)
colorOn = [0 0 1];
colorOff = [0 0 0.2];
if all(obj.ProbeInfo.DetActive' == h.Value,'all') && ~isempty(obj.ProbeInfo.DetActive)
    h.Value = [];
end
set(obj.ForwardPlot.DetectorOptode, 'Color', colorOff);
set(obj.ForwardPlot.DetectorOptode(h.Value), 'Color', colorOn);
set(obj.ForwardPlot.DetDirectionArrow, 'FaceColor', colorOff);
set(obj.ForwardPlot.DetDirectionArrow(h.Value), 'FaceColor', colorOn);
ViewForward.photonrefresh([],[],obj);
obj.ProbeInfo.DetActive = h.Value;
end

function channellist_callback(h, ~, obj)
src = obj.Probe.channel.pairs(h.Value,1);
det = obj.Probe.channel.pairs(h.Value,2);

if all(obj.ProbeInfo.ChannelActive' == h.Value,'all') && ~isempty(obj.ProbeInfo.ChannelActive)
    h.Value = [];
end

colorOn = [1 0 0];
colorOff = [0.2 0 0];
set(obj.ForwardPlot.SourceOptode, 'Color', colorOff);
set(obj.ForwardPlot.SourceOptode(src), 'Color', colorOn);
set(obj.ForwardPlot.SrcDirectionArrow, 'FaceColor', colorOff);
set(obj.ForwardPlot.SrcDirectionArrow(src), 'FaceColor', colorOn);

colorOn = [0 0 1];
colorOff = [0 0 0.2];
set(obj.ForwardPlot.DetectorOptode,'Color', colorOff);
set(obj.ForwardPlot.DetectorOptode(det),'Color', colorOn);
set(obj.ForwardPlot.DetDirectionArrow, 'FaceColor', colorOff);
set(obj.ForwardPlot.DetDirectionArrow(det), 'FaceColor', colorOn);

ViewForward.photonrefresh([],[],obj);
obj.ProbeInfo.ChannelActive = h.Value;
end

function optode_checkbox(h, ~, obj)
if h.Value == true
    set(obj.ForwardPlot.SourceOptode,'Visible', 'on');
    set(obj.ForwardPlot.DetectorOptode,'Visible', 'on');
else
    set(obj.ForwardPlot.SourceOptode,'Visible', 'off');
    set(obj.ForwardPlot.DetectorOptode,'Visible', 'off');
end
end

function arrow_checkbox(h, ~, obj)
if h.Value
    set(obj.ForwardPlot.SrcDirectionArrow, 'Visible', 'on');
    set(obj.ForwardPlot.DetDirectionArrow, 'Visible', 'on');
else
    set(obj.ForwardPlot.SrcDirectionArrow, 'Visible', 'off');
    set(obj.ForwardPlot.DetDirectionArrow, 'Visible', 'off');
end
end

