function populateprobeplot(obj)

lineShrinkFactor = 2;
sourceColor = [1 0 0];
detectorColor = [0 0 1];
channelColor = [0 0 0];

obj.ProbePlot.SourceOptode = plot3(...
    [obj.Probe.source.position(:,1) obj.Probe.source.position(:,1)]', ...
    [obj.Probe.source.position(:,2) obj.Probe.source.position(:,2)]', ...
    [obj.Probe.source.position(:,3) obj.Probe.source.position(:,3)]', ...
    'Marker', '.', ...
    'MarkerSize', 20, ...
    'Color', sourceColor, ...
    'LineStyle', 'none', ...
    'Parent', obj.MainPlot.Axes);

obj.ProbePlot.DetectorOptode = plot3(...
    [obj.Probe.detector.position(:,1) obj.Probe.detector.position(:,1)]', ...
    [obj.Probe.detector.position(:,2) obj.Probe.detector.position(:,2)]', ...
    [obj.Probe.detector.position(:,3) obj.Probe.detector.position(:,3)]', ...
    'Marker', '.', ...
    'MarkerSize', 20, ...
    'Color', detectorColor, ...
    'LineStyle', 'none', ...
    'Parent', obj.MainPlot.Axes);

tempVector = obj.Probe.source.position(obj.Probe.channel.pairs(:,1),:)-obj.Probe.detector.position(obj.Probe.channel.pairs(:,2),:);
tempVersor = tempVector./vecnorm(tempVector,2,2);

tempCoordSourceShrink = obj.Probe.source.position(obj.Probe.channel.pairs(:,1),:) - tempVersor.*lineShrinkFactor;
tempCoordDetectorShrink = obj.Probe.detector.position(obj.Probe.channel.pairs(:,2),:) + tempVersor.*lineShrinkFactor;
xChannel = [tempCoordSourceShrink(:,1) tempCoordDetectorShrink(:,1)]';
yChannel = [tempCoordSourceShrink(:,2) tempCoordDetectorShrink(:,2)]';
zChannel = [tempCoordSourceShrink(:,3) tempCoordDetectorShrink(:,3)]';

obj.ProbePlot.Channel = plot3(obj.MainPlot.Axes, ...
    xChannel, ...
    yChannel, ...
    zChannel, ...
    'LineWidth', 2, ...
    'Color', channelColor,...
    'HitTest', 'off'...
    );

obj.ProbePlot.LabelSource = text(obj.Probe.source.position(:,1),...
    obj.Probe.source.position(:,2),...
    obj.Probe.source.position(:,3),...
    obj.Probe.source.label, ...
    'FontWeight', 'bold', ...
    'FontSize', 10, ...
    'HitTest', 'off', ...
    'Visible', 'off', ...
    'Color', sourceColor);

obj.ProbePlot.LabelDetector = text(obj.Probe.detector.position(:,1),...
    obj.Probe.detector.position(:,2),...
    obj.Probe.detector.position(:,3),...
    obj.Probe.detector.label, ...
    'FontWeight', 'bold', ...
    'FontSize', 10, ...
    'HitTest', 'off', ...
    'Visible', 'off', ...
    'Color', detectorColor);

xCoordChannel = mean(xChannel,1);
yCoordChannel = mean(yChannel,1);
zCoordChannel = mean(zChannel,1);

obj.ProbePlot.LabelChannel = text(xCoordChannel, yCoordChannel, zCoordChannel, ...
    obj.Probe.channel.label, ...
    'FontWeight', 'bold', ...
    'FontSize', 10, ...
    'HitTest', 'off', ...
    'Visible', 'off', ...
    'Color', 'k');
end
