function populateprobeinfo(obj)
obj.ProbeInfo.OptodeCheckbox = uicontrol('Parent', obj.MainInfo.TabProbe, ...
    'Style', 'checkbox', ...
    'Units', 'normalized',...
    'Position', [0.1 0.35 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Optodes', ...
    'Value', true, ...
    'Callback', @(h,e)optode_checkbox(h,e,obj));
obj.ProbeInfo.ChannelCheckbox = uicontrol('Parent', obj.MainInfo.TabProbe, ...
    'Style', 'checkbox', ...
    'Units', 'normalized',...
    'Position', [0.1 0.3 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Channels', ...
    'Value', true, ...
    'Callback', @(h,e)channel_checkbox(h,e,obj));
obj.ProbeInfo.LabelCheckbox = uicontrol('Parent', obj.MainInfo.TabProbe, ...
    'Style', 'checkbox', ...
    'Units', 'normalized',...
    'Position', [0.1 0.25 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Labels', ...
    'Value', false, ...
    'Callback', @(h,e)label_checkbox(h,e,obj));
end

function optode_checkbox(h, ~, obj)
if h.Value == true
    set(obj.ProbePlot.SourceOptode,'Visible', 'on');
    set(obj.ProbePlot.DetectorOptode,'Visible', 'on');
else
    set(obj.ProbePlot.SourceOptode,'Visible', 'off');
    set(obj.ProbePlot.DetectorOptode,'Visible', 'off');
end
end

function channel_checkbox(h, ~, obj)
if h.Value
    set(obj.ProbePlot.Channel, 'Visible', 'on');
else
    set(obj.ProbePlot.Channel, 'Visible', 'off');
end
end

function label_checkbox(h, ~, obj)
if h.Value
    set(obj.ProbePlot.LabelSource, 'Visible', 'on');
    set(obj.ProbePlot.LabelDetector, 'Visible', 'on');
    set(obj.ProbePlot.LabelChannel, 'Visible', 'on');
else
    set(obj.ProbePlot.LabelSource, 'Visible', 'off');
    set(obj.ProbePlot.LabelDetector, 'Visible', 'off');
    set(obj.ProbePlot.LabelChannel, 'Visible', 'off');
end
end


