function  createtimefrequency(obj)

 obj.Panel.Plot.TimeFrequency.MainAxes = axes('parent', obj.Panel.Plot.TimeFrequency.Tab,...
    'Position', [0.07 0.22 0.88 0.66], ...
    'Units', 'normalized', ...
    'Color', obj.Preference.backgroundColor, ...
    'XColor', obj.Preference.foregroundColor, ...
    'YColor', obj.Preference.foregroundColor, ...
    'XGrid', 'on', ...
    'XDir','reverse',...
    'YGrid', 'on', ...
    'View',[-240 ,  30],...
    'NextPlot', 'add',...
    'GridColor', obj.Preference.foregroundColor, ...
    'FontSize',obj.Preference.defaultFontSize,...
    'FontWeight', 'bold', ...
    'FontName', obj.Preference.defaultFontName, ...
    'Visible', 'off', ...
    'Title', 'Main plots');

 obj.Panel.Plot.TimeFrequency.Text = uicontrol(...
    'Parent', obj.Panel.Plot.TimeFrequency.Tab, ...
    'Style', 'text', ...
    'BackgroundColor',obj.Preference.backgroundColor, ...
    'ForegroundColor', obj.Preference.foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.25 0.25 0.5 0.5], ...
    'FontWeight', 'bold', ...
    'FontSize', 40, ...
    'Visible', 'on',...
    'FontAngle', 'italic', ...
    'HorizontalAlignment', 'center', ...
    'String', 'Select one curve!!!');
end