function createmenu(obj)


obj.Menu.File = uimenu('Parent',  obj.MainFigure, 'Label', 'File');
obj.Menu.FileLoadData = uimenu('Parent', obj.Menu.File, ...
    'Label', 'Load Data...', ...
    'Callback', @load_data);
obj.Menu.FileExport = uimenu('Parent', obj.Menu.File, ...
    'Label', 'Export');
obj.Menu.FileExportExport2png = uimenu('Parent', obj.Menu.File, ...
    'Label', 'Export to png', ...
    'Callback', @export2png);
obj.Menu.FileQuit = uimenu('Parent', obj.Menu.File, ...
    'Label', 'Quit', ...
    'Callback', {@closewindow, obj.MainFigure});
obj.Menu.Edit = uimenu('Parent', obj.MainFigure, 'Label', 'Edit');
obj.Menu.View = uimenu('Parent', obj.MainFigure, 'Label', 'View');
obj.Menu.ViewOpenTable = uimenu('Parent', obj.Menu.View, ...
    'Label', 'Open Table...');
end

