function populatepreference(obj)

obj.Panel.Preference.PopupType = uiw.widget.Popup(...
    'Parent', obj.Panel.PanelPreference, ...
    'Units','normalized',...
    'Position',[0 0.75 1 0.25],...
    'Items', obj.Dataset.dataType,...
    'BackgroundColor', obj.Preference.backgroundColor, ...
    'ForegroundColor', obj.Preference.foregroundColor, ...
    'FontWeight', 'bold', ...
    'Label','Sorting:', ...
    'LabelLocation','left',...
    'Callback', @(h,e)typeselector_callback(h, e, obj)...
    );

obj.Panel.Preference.PopupSorting = uiw.widget.Popup(...
    'Parent',  obj.Panel.PanelPreference, ...
        'Units','normalized',...
    'Position',[0 0.50 1 0.25],...
    'Items',obj.Dataset.sortingMethod,...
    'BackgroundColor', obj.Preference.backgroundColor, ...
    'ForegroundColor', obj.Preference.foregroundColor, ...
    'LabelLocation','left',...
    'Callback',@(h,e)sortingmethod_callback(h, e, obj)...
    );

obj.Panel.Preference.CheckBoxYAutoscale = uicontrol(...
    'Parent', obj.Panel.PanelPreference, ...
    'Style', 'checkbox', ...
    'BackgroundColor', obj.Preference.backgroundColor, ...
    'ForegroundColor', obj.Preference.foregroundColor, ...
        'Units','normalized',...
    'Position',[0 0.25 1 0.25],...
    'FontWeight', 'bold', ...
    'Value',true,...
    'Callback',@(h,e)yautoscale_callback(h, e, obj),...
    'FontSize', 8, ...
    'FontAngle', 'italic', ...
    'HorizontalAlignment', 'right', ...
    'String', 'Y axes Autoscale');

obj.Panel.Preference.CheckBoxShowEvent = uicontrol(...
    'Parent', obj.Panel.PanelPreference, ...
    'Style', 'checkbox', ...
    'BackgroundColor', obj.Preference.backgroundColor, ...
    'ForegroundColor', obj.Preference.foregroundColor, ...
        'Units','normalized',...
    'Position',[0 0 1 0.25],...
    'FontWeight', 'bold', ...
    'Value', true,...
    'Callback', @(h,e)show_events(h, e, obj),...
    'FontSize', 8, ...
    'FontAngle', 'italic', ...
    'HorizontalAlignment', 'right', ...
    'String', 'Show Events');
end

function yautoscale_callback(handle, ~, obj)
if handle.Value
    obj.Panel.Plot.Time.YEditMax.Visible = 'off';
    obj.Panel.Plot.Time.YEditMin.Visible = 'off';
    obj.WatchList.edvLine = obj.WatchList.edvLine;
else
    obj.Panel.Plot.Time.YEditMax.Visible = 'on';
    obj.Panel.Plot.Time.YEditMin.Visible = 'on';
    obj.Panel.Plot.Time.YEditMax.String = 'max';
    obj.Panel.Plot.Time.YEditMin.String = 'min';
end
end

function sortingmethod_callback(~, Event, obj)
sortingmethod = Event.NewValue;
colors = sorting_colors((width(obj.Dataset.Data.Time)-1), sortingmethod);
obj.WatchList.colorLine = colors;
obj.WatchList.edvLine = ones(size(obj.WatchList.edvLine));
end

function typeselector_callback(Source, ~, obj)
dataIdx = contains(obj.Dataset.Data.Time.Properties.VariableNames , {'Time', Source.Value});
obj.WatchList.time2Plot = obj.Dataset.Data.Time(:,dataIdx);
obj.WatchList.spectrum2Plot = obj.Dataset.Data.Frequency(:,dataIdx);
end

function show_events(handle, ~, obj)
if handle.Value
    set(obj.Panel.Plot.Time.Events, 'Visible', 'on');
else
    set(obj.Panel.Plot.Time.Events, 'Visible', 'off');
end
end