function populateinfo(obj)

Label = {'Date';...
    'Note';...
    'id';...
    'Analysis' ;...
    'Time length';...
    'Sample length';...
    'Sampling frequency';...
    'Events';...
    'Track';...
    'Min';...
    'Max';...
    'Avg';...
    'Std'};

Value = Label;

nParam = length(Label);
i = 1/(2*nParam+1);
e = i;

for iParam = 1:1:nParam
    labelPos = [0.1, (nParam-iParam+1)*e+(nParam-iParam)*i, 0.4, i];
    valuePos = [0.5, (nParam-iParam+1)*e+(nParam-iParam)*i, 0.4, i];
    obj.Panel.Info.textLabel(iParam) = uicontrol('Parent', obj.Panel.PanelInfo, ...
        'Style', 'text', ...
        'Units', 'normalized',...
        'Position', labelPos,...
        'HorizontalAlignment', 'left', ...
        'Visible', 'on', ...
        'String', Label{iParam});
    obj.Panel.Info.textValue(iParam) = uicontrol('Parent', obj.Panel.PanelInfo, ...
        'Style', 'text', ...
        'Units', 'normalized',...
        'Position', valuePos,...
        'Max',2,...
        'HorizontalAlignment', 'left', ...
        'Visible', 'on', ...
        'String', Value{iParam});
end
% Value = {datestr(obj.Dataset.Analysis.date);...
%     obj.Dataset.Analysis.note; ...
%     obj.Dataset.Analysis.id;...
%     obj.Dataset.Analysis.analysis; ...
%     [num2str(obj.Dataset.Measure.timeLength) ' s'];...
%     num2str(height(obj.Dataset.Data.Time))};

