function viewerpopulatepreferences(viewerC, GHandle, vIdx)

GHandle.Viewer(vIdx).PreferencePanel.DataTypeSelector = uiw.widget.Popup(...
    'Parent', GHandle.Viewer(vIdx).PreferencePanel.VPanel, ...
    'Items', viewerC.dataType,...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'FontWeight', 'bold', ...
    'Label','Sorting:', ...
    'LabelLocation','left',...
    'Callback', @(h,e)typeselector_callback(h, e, GHandle, vIdx, viewerC)...
    );

GHandle.Viewer(vIdx).PreferencePanel.SortingMethods = uiw.widget.Popup(...
    'Parent',  GHandle.Viewer(vIdx).PreferencePanel.VPanel, ...
    'Items',viewerC.sortingMethod,...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'Label','Sorting:', ...
    'LabelLocation','left',...
    'Callback',@(h,e)sortingmethod_callback(h, e, GHandle, vIdx, viewerC)...
    );

GHandle.Viewer(vIdx).PreferencePanel.YAutoscale = uicontrol(...
    'Parent', GHandle.Viewer(vIdx).PreferencePanel.VPanel, ...
    'Style', 'checkbox', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'Units', 'normalized', ...
    'FontWeight', 'bold', ...
    'Value',true,...
    'Callback', {@yautoscale_callback, GHandle, vIdx},...
    'FontSize', 8, ...
    'FontAngle', 'italic', ...
    'HorizontalAlignment', 'right', ...
    'String', 'Y axes Autoscale');

GHandle.Viewer(vIdx).PreferencePanel.ShowEvent = uicontrol(...
    'Parent', GHandle.Viewer(vIdx).PreferencePanel.VPanel, ...
    'Style', 'checkbox', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'Units', 'normalized', ...
    'FontWeight', 'bold', ...
    'Value', true,...
    'Callback', {@show_events, GHandle, vIdx},...
    'FontSize', 8, ...
    'FontAngle', 'italic', ...
    'HorizontalAlignment', 'right', ...
    'String', 'Show Events');
end

function yautoscale_callback(handle, ~, GHandle, vIdx)
if handle.Value
    GHandle.Viewer(vIdx).PlotPanel.Time.YEditMax.Visible = 'off';
    GHandle.Viewer(vIdx).PlotPanel.Time.YEditMin.Visible = 'off';
    GHandle.Viewer(vIdx).WatchList.edvLine = GHandle.Viewer(vIdx).WatchList.edvLine;
else
    GHandle.Viewer(vIdx).PlotPanel.Time.YEditMax.Visible = 'on';
    GHandle.Viewer(vIdx).PlotPanel.Time.YEditMin.Visible = 'on';
    GHandle.Viewer(vIdx).PlotPanel.Time.YEditMax.String = 'max';
    GHandle.Viewer(vIdx).PlotPanel.Time.YEditMin.String = 'min';
end
end

function sortingmethod_callback(~, Event, GHandle, vIdx, viewerC)
sortingmethod = Event.NewValue;
colors = sorting_colors((width(viewerC.Data.Time)-1), sortingmethod);
GHandle.Viewer(vIdx).WatchList.colorLine = colors;
GHandle.Viewer(vIdx).WatchList.edvLine = ones(size(GHandle.Viewer(vIdx).WatchList.edvLine));
end

function typeselector_callback(Source, ~, GHandle, vIdx, viewerC)
dataIdx = contains(viewerC.Data.Time.Properties.VariableNames , {'Time', Source.Value});
GHandle.Viewer(vIdx).WatchList.time2Plot = viewerC.Data.Time(:,dataIdx);
GHandle.Viewer(vIdx).WatchList.spectrum2Plot = viewerC.Data.Frequency(:,dataIdx);
end

function show_events(handle, ~, GHandle, vIdx)
if handle.Value
    set(GHandle.Viewer(vIdx).PlotPanel.Time.Events, 'Visible', 'on');
else
    set(GHandle.Viewer(vIdx).PlotPanel.Time.Events, 'Visible', 'off');
end
end