function probesimulationwindow(GHandle)
figureSize = GHandle.Preference.Figure.sizeMedium;

%% Set color theme
backgroundColor = GHandle.Preference.Theme.backgroundColor;
foregroundColor = GHandle.Preference.Theme.foregroundColor;
highlightColor = GHandle.Preference.Theme.highlightColor;
textForegroundColor = [0 0 0];
sourceColor = 'r';
detectorColor = 'b';
channelColor = 'k';

%% Set font
defaultFontName = GHandle.Preference.Font.name;

Probe = GHandle.CurrentDataSet.Probe;
DBProbe = GHandle.DataBase.findid(Probe.id);
GHandle.TempWindow.Probe = Probe;
GHandle.TempWindow.DBProbe = DBProbe;

DBAtlas = GHandle.DataBase.findid(Probe.atlasId);
GHandle.TempWindow.DBAtlas = DBAtlas;
GHandle.TempWindow.Atlas = DBAtlas.load;
%% Create GUI
GHandle.TempWindow.SimulationFigure = figure(...
    'position', figureSize,...
    'Color',backgroundColor,...
    'Resize', 'on',...
    'Name', 'Probe Sensitivity Simulation', ...
    'Numbertitle', 'off', ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Visible', 'off', ...
    'DeleteFcn', {@close_figure, GHandle});

GHandle.TempWindow.ParameterPanel = uipanel('Parent', GHandle.TempWindow.SimulationFigure,...
    'Units', 'normalized', ...
    'Position', [0 0 0.5 1]);
GHandle.TempWindow.RunPanel = uipanel('Parent', GHandle.TempWindow.SimulationFigure,...
    'Units', 'normalized', ...
    'Position', [0.5 0 0.5 1]);
% GHandle.TempWindow.SettingPanel = uipanel('Parent', GHandle.TempWindow.SimulationFigure,...
%     'Units', 'normalized', ...
%     'Position', [0.81 0 0.2 1]);

GHandle.TempWindow.NPhotonLabel = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.15 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'N photons');
GHandle.TempWindow.NPhoton = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.1 0.8 0.05],...
    'String', '1e6', ...
    'Visible', 'on');

GHandle.TempWindow.TimeLabel = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.3 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Time (Tstart, Tstep, Tend)');
GHandle.TempWindow.TStart = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.25 0.25 0.05],...
    'String', '0', ...
    'Visible', 'on');
GHandle.TempWindow.TStep = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.375 0.25 0.25 0.05],...
    'String', '1e-11', ...
    'Visible', 'on');
GHandle.TempWindow.TEnd = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.65 0.25 0.25 0.05],...
    'String', '1e-9', ...
    'Visible', 'on');

srcTypes = {'pencil'; 'isotropic'; 'cone'; 'gaussian'; 'planar'; 'pattern';...
    'fourier'; 'arcsine'; 'disk'; 'fourierx'; 'fourierx2d'; 'zgaussian'};
GHandle.TempWindow.SrcTypeLabel = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.45 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Source type');
GHandle.TempWindow.SrcType = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'popup', ...
    'Units', 'normalized',...
    'Position', [0.1 0.4 0.8 0.05],...
    'String', srcTypes, ...
    'Visible', 'on');

GHandle.TempWindow.DebugLevelLabel = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.6 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Debug level (subset of [MCBWDIOXATRPE])');
GHandle.TempWindow.DebugLevel = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.55 0.8 0.05],...
    'String', 'TP', ...
    'Visible', 'on');

GHandle.TempWindow.RunButton = uicontrol('Parent', GHandle.TempWindow.RunPanel, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized',...
    'Position', [0.1 0.1 0.8 0.8],...
    'String', 'Run like hell', ...
    'Visible', 'on', ...
    'Callback', @(h,e)runforward(h,e,GHandle));

%% Check forward solver

%% Check atlas

%% Turn on figure
GHandle.TempWindow.SimulationFigure.Visible = 'on';
end

function close_figure(Handle, ~, GHandle)
delete(Handle);
GHandle.TempWindow = [];
end
