function  Handle = guidisp(Measure, PannelHandle , editableField)
	dxsxEdge = 0.05;
	overunderEdge = 0.009;
	textBoxWidth = 0.3;
	textBoxHeight = 0.12;

	

	% create the figure and the editable field if is not specify
	if ~exist('editableField','var')
		editableField = '';
	end
	editableField = lower(editableField);
	
	if ~exist('PannelHandle','var') || isempty(PannelHandle)
		Handle.MainFigure = figure;
		Handle.Pannel = uipanel('Parent',Handle.MainFigure);
	else
		Handle.Pannel = PannelHandle;
	end
	
	% assign the title
	Handle.Pannel.Title = 'Measure';
	
	% id
	lowerPos = (0.3 +overunderEdge) + 3 *( 0.7 - overunderEdge)/4;
	Handle.IdTextBox = uiw.widget.FixedText(...      
		'Parent',Handle.Pannel,...
		'Value',Measure.id,...
		'Label','ID:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);

	% date
	lowerPos = (0.3 +overunderEdge) + 2 *( 0.7 - overunderEdge)/4;
	if any(contains(editableField,'Date'))
		Handle.BirthdateEditableTextBox = uiw.widget.EditableText(...      
		'Parent',Handle.Pannel,...
		'Value',datestr(Measure.date, 'dd/mm/yyyy'),...
		'Label','Name',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);
	else
		Handle.BirthdateTextBox = uiw.widget.FixedText(...      
		'Parent',Handle.Pannel,...
		'Value',datestr(Measure.date, 'dd/mm/yyyy'),...
		'Label','Date:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);
	end
	
	%duration
	lowerPos = (0.3 +overunderEdge) + 1 *( 0.7 - overunderEdge)/4;
	Handle.BirthdateTextBox = uiw.widget.FixedText(...      
	'Parent',Handle.Pannel,...
	'Value',char(Measure.timeLength),...
	'Label','Time Length:',...
	'LabelLocation','top',...
	'LabelWidth',90,...
	'Units','normalized',...
	'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);

	
	
	%update rate
	lowerPos = (0.3 +overunderEdge);
	Handle.BirthdateTextBox = uiw.widget.FixedText(...      
	'Parent',Handle.Pannel,...
	'Value',num2str(Measure.updateRate),...
	'Label','Update Rate:',...
	'LabelLocation','top',...
	'LabelWidth',90,...
	'Units','normalized',...
	'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);

	
	% note
	if any(contains(editableField,'note'))
		Handle.NoteEditableTextBox = uiw.widget.EditableText(...      
		'Parent',Handle.Pannel,...
		'Value',Measure.note,...
		'Label','Note',...
		'LabelLocation','top',...
		'IsMultiLine', true,...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[dxsxEdge overunderEdge textBoxWidth 0.3-overunderEdge]);
	else
		Handle.NoteTextBox = uiw.widget.FixedText(...      
		'Parent',Handle.Pannel,...
		'Value',Measure.note,...
		'Label','Note:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[dxsxEdge overunderEdge textBoxWidth 0.3-overunderEdge]);
	end
	
	% plot the info list
	infoList = fieldnames(Measure.Info);
	nInfo = length(infoList);
	for iInfo = 1 : nInfo
		field = infoList{iInfo};
		fieldValue = num2str(Measure.Info.(field));
		
		ypos = (1 - overunderEdge - textBoxHeight ) -  (iInfo-1)/nInfo;
		xpos = 0.5;
			
		tag = [field ,'EditableTextBox'];
		if any(contains(editableField,field))
			Handle.(tag) = uiw.widget.EditableText(...      
			'Parent',Handle.Pannel,...
			'Value',fieldValue,...
			'Label',[field,':'],...
			'LabelLocation','top',...
			'IsMultiLine', true,...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[xpos ypos textBoxWidth, textBoxHeight]);
		else
			Handle.(tag) = uiw.widget.FixedText(...      
			'Parent',Handle.Pannel,...
			'Value',fieldValue,...
			'Label',[field,':'],...
			'LabelLocation','top',...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[xpos ypos textBoxWidth, textBoxHeight]);
		end
	end
	
end

