function  Handle = guidisp(Measure, PannelHandle , editableField)
	dxsxEdge = 0.05;
	overunderEdge = 0.009;
	textBoxWidth = 0.3;
	textBoxHeight = 0.12;
	

	% create the figure and the editable field if is not specify
	if ~exist('editableField','var')
		editableField = '';
	end
	editableField = lower(editableField);
	
	if ~exist('PannelHandle','var') || isempty(PannelHandle)
		Handle.MainFigure = figure;
		Handle.Pannel = uipanel('Parent',Handle.MainFigure);
	else
		Handle.Pannel = PannelHandle;
	end
	
	% assign the title
	Handle.Pannel.Title = 'Measure';
	
	% id
	lowerPos = (0.3 +overunderEdge) + 3 *( 0.7 - overunderEdge)/4;
	Handle.IdTextBox = gtextbox(...      
		'Parent',Handle.Pannel,...
		'TextString',Measure.id,...
		'TitleString','ID:',...
		'Units','normalized',...
		'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);

	% date
	lowerPos = (0.3 +overunderEdge) + 2 *( 0.7 - overunderEdge)/4;
	if any(contains(editableField,'Date'))
		Handle.BirthdateEditableTextBox = geditabletext(...      
		'Parent',Handle.Pannel,...
		'TextString',datestr(Measure.date, 'dd/mm/yyyy'),...
		'TitleString','Name',...
		'Units','normalized',...
		'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);
	else
		Handle.BirthdateTextBox = gtextbox(...      
		'Parent',Handle.Pannel,...
		'TextString',datestr(Measure.date, 'dd/mm/yyyy'),...
		'TitleString','Date:',...
		'Units','normalized',...
		'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);
	end
	
	%duration
	lowerPos = (0.3 +overunderEdge) + 1 *( 0.7 - overunderEdge)/4;
	Handle.BirthdateTextBox = gtextbox(...      
	'Parent',Handle.Pannel,...
	'TextString',char(Measure.timeLength),...
	'TitleString','Time Length:',...
	'Units','normalized',...
	'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);

	
	
	%update rate
	lowerPos = (0.3 +overunderEdge);
	Handle.BirthdateTextBox = gtextbox(...      
	'Parent',Handle.Pannel,...
	'TextString',num2str(Measure.updateRate),...
	'TitleString','Update Rate:',...
	'Units','normalized',...
	'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);

	
	% note
	if any(contains(editableField,'note'))
		Handle.NoteEditableTextBox = geditabletext(...      
		'Parent',Handle.Pannel,...
		'TextString',Measure.note,...
		'TitleString','Note',...
		'Units','normalized',...
		'Position',[dxsxEdge overunderEdge textBoxWidth 0.3-overunderEdge]);
	else
		Handle.NoteTextBox = gtextbox(...      
		'Parent',Handle.Pannel,...
		'TextString',Measure.note,...
		'TitleString','Note:',...
		'Units','normalized',...
		'Position',[dxsxEdge overunderEdge textBoxWidth 0.3-overunderEdge]);
	end
	
	% plot the info list
	infoList = fieldnames(Measure.Info);
	nInfo = length(infoList);
	for iInfo = 1 : nInfo
		field = infoList{iInfo};
		fieldTextString = num2str(Measure.Info.(field));
		
		ypos = (1 - overunderEdge - textBoxHeight ) -  (iInfo-1)/nInfo;
		xpos = 0.5;
			
		tag = [field ,'EditableTextBox'];
		if any(contains(editableField,field))
			Handle.(tag) = geditabletext(...      
			'Parent',Handle.Pannel,...
			'TextString',fieldTextString,...
			'TitleString',[field,':'],...
			'Units','normalized',...
			'Position',[xpos ypos textBoxWidth, textBoxHeight]);
		else
			Handle.(tag) = gtextbox(...      
			'Parent',Handle.Pannel,...
			'TextString',fieldTextString,...
			'TitleString',[field,':'],...
			'Units','normalized',...
			'Position',[xpos ypos textBoxWidth, textBoxHeight]);
		end
	end
	
end

