%% 3d
f = figure;
ax = axes('Parent', f, 'NextPlot', 'add');

gmColor = [0.65 0.65 0.65];
landMarkColor = [0 0.8 0];
landMarkTextColor = [0 0.8 0];

Atlas = GHandle.DataBase.Atlas(6).load;
Gray = trisurf(...
    Atlas.GreyMatter.face,...
    Atlas.GreyMatter.node(:,1),Atlas.GreyMatter.node(:,2), Atlas.GreyMatter.node(:,3),...
    2.*ones(size(Atlas.GreyMatter.node(:,3))),...
    'Parent', ax,...
    'SpecularStrength', 0, ...
    'EdgeColor','none',...
    'FaceColor',gmColor,...
    'FaceAlpha',1);
axis equal
axis off

x = reshape(Atlas.LandMarks.coord(1:5:end,1:5:end,1), [],1);
y = reshape(Atlas.LandMarks.coord(1:5:end,1:5:end,2), [],1);
z = reshape(Atlas.LandMarks.coord(1:5:end,1:5:end,3), [],1);
%landmarkNames = reshape(Atlas.LandMarks.names(1:5:end,1:5:end), [], 1);
landmarkNames = reshape(tenFive.names(1:5:end,1:5:end), [], 1);
iMask = find(~cellfun('isempty', landmarkNames));

LandMark = plot3(...
    x(iMask), y(iMask), z(iMask),...
    'MarkerSize',20,...
    'LineStyle', 'none',...
    'Visible', 'on',...
    'Marker','.',...
    'Color',landMarkColor,...
    'Parent', ax);

LandMarkText = text(...
    ax,...
    x(iMask), y(iMask), z(iMask),...
    landmarkNames(iMask),...
    'Color',landMarkTextColor,...
    'FontWeight','bold',...
    'Visible', 'on');

lighting(ax,'gouraud');
Light(1) = light('Position', [+100 0 50]);
Light(2) = light('Position', [-100 0 50]);

set(ax,'CameraViewAngle',6);
set(ax,'PlotBoxAspectRatio',[1 1 1]);
set(ax,'DataAspectRatio', [1 1 1]);
rotate3d(ax, 'on');
