function newstudy(~, ~, GHandle)

figureSize = GHandle.Preference.Figure.sizeMedium;


GHandle.TempWindow.NewStudyFigure = figure(...
    'position', figureSize,...
    'Resize', 'on',...
    'Name', 'New NIRS Study', ...
    'Numbertitle', 'off', ...
    'CloseRequestFcn', @(h,e)close_function(h,e, GHandle),...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL',...
    'Visible', 'off' ...
    );

GHandle.TempWindow.NewStudyName = uiw.widget.EditableText(...
    'Parent',GHandle.TempWindow.NewStudyFigure,...=
    'Value','Insert Name',...
    'Label','Study Name:',...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.80 0.35 0.15]);

GHandle.TempWindow.NewStudyNote = uiw.widget.EditableText(...
    'Parent',GHandle.TempWindow.NewStudyFigure,...
    'Value','Insert Note',...
    'Label','Study Note:',...
    'IsMultiLine', 1,...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.50 0.05 0.25 0.45]);

GHandle.TempWindow.NewStudyListBox = uicontrol(...
    'Parent', GHandle.TempWindow.NewStudyFigure, ...
    'Style','listbox',...
    'Units', 'normalize', ...
    'Max', 2,...
    'Position',  [0.05 0.05 0.4 0.55],...
    'String',[],...
    'Value',[]);

GHandle.TempWindow.NewStudySelector = uiw.widget.FolderSelector(...
    'Parent', GHandle.TempWindow.NewStudyFigure, ...
    'Value', [], ...
    'Label','Choose a data file:', ...
    'LabelLocation','top',...
    'LabelWidth',150,...
    'Units', 'normalize', ...
    'Position', [0.05 0.60 0.4 0.15],...
    'Callback',@(ObjectHandle, Event)founddatafile(ObjectHandle, Event, GHandle)...
    );




GHandle.TempWindow.NewStudyLoadButton = uicontrol('Style', 'pushbutton',...
    'Parent', GHandle.TempWindow.NewStudyFigure, ...
    'String', 'Load',...
    'Units', 'normalize', ...
    'Position', [0.8 0.15 0.2 0.1],...
    'Callback', {@load_study ,GHandle}...
    );

GHandle.TempWindow.NewStudyFigure.Visible = 'on';

end

function founddatafile( ~, Events, GHandle)

dataExtension = {'.txt', '.dat'};

% find all the flie
listing = dir(Events.NewValue);

%filter only data file
listIdx = contains({listing.name},dataExtension);

% add it to the list box
if any(listIdx)
    GHandle.TempWindow.NewStudyListBox.String = {listing(listIdx).name};
else
    GHandle.TempWindow.NewStudyListBox.String = [];
end

end


function load_study(~, ~, GHandle )
%inserire il phantom del soggetto e le note

studyName = GHandle.TempWindow.NewStudyName.Value;
note = GHandle.TempWindow.NewStudyNote.Value;

NewStudy = NirsStudy('tag', studyName, 'date' ,datetime, 'note', note);

DataBase = GHandle.DataBase.add(NewStudy);

GHandle.DataBase = DataBase;

tree(GHandle);

idxListMeasure = GHandle.TempWindow.NewStudyListBox.Value;
if ~isempty(idxListMeasure)
    fileNameCell = GHandle.TempWindow.NewStudyListBox.String(GHandle.TempWindow.NewStudyListBox.Value);
    filePathCell = fullfile(GHandle.TempWindow.NewStudySelector.Value, fileNameCell);
end
close_function(GHandle.TempWindow.NewStudyFigure,[], GHandle)
for idxMeasure = 1:length(idxListMeasure)
    filePath = filePathCell{idxMeasure};
    % set the path of the measure
    GHandle.Temp.location = filePath;
    GHandle.Temp.measureNote = 'Batch loaded';
    % create the subject
    
    NewSubject = NirsSubject('name', ['Subject' num2str(idxMeasure,'%.3d')],...
        'surname','',...
        'note', 'Auto loaded');
    
    DataBase = GHandle.DataBase.add(NewSubject);
    GHandle.DataBase = DataBase;
    
    %modify this part
    GHandle.CurrentDataSet.Subject.id = GHandle.DataBase.Subject(end).id;
    
    GHandle.Main.Tree.StudyTree.SelectedNodes = GHandle.Main.Tree.Study(end).MainNode;
    %cambiarlo che fara casino
    GHandle.CurrentDataSet.Study.id = GHandle.DataBase.Study(end).id;
    loadmeasure(GHandle);
end


end


function close_function(h , ~ ,GHandle)
delete(h);
GHandle.TempWindow = [];
end













