function viewermenu(viewerC, GHandle, vIdx)


GHandle.Viewer(vIdx).menu.menuFile = uimenu('Parent', GHandle.Viewer(vIdx).mainFigure, 'Label', 'File');
GHandle.Viewer(vIdx).menu.menuFile_loadData = uimenu('Parent', GHandle.Viewer(vIdx).menu.menuFile, ...
    'Label', 'Load Data...', ...
    'Callback', @load_data);
GHandle.Viewer(vIdx).menu.menuFile_export = uimenu('Parent', GHandle.Viewer(vIdx).menu.menuFile, ...
    'Label', 'Export');
GHandle.Viewer(vIdx).menu.menuFile_export_export2png = uimenu('Parent', GHandle.Viewer(vIdx).menu.menuFile, ...
    'Label', 'Export to png', ...
    'Callback', @export2png);
GHandle.Viewer(vIdx).menu.menuFile_quit = uimenu('Parent', GHandle.Viewer(vIdx).menu.menuFile, ...
    'Label', 'Quit', ...
    'Callback', {@closewindow, GHandle.Viewer(vIdx).mainFigure});

GHandle.Viewer(vIdx).menu.menuEdit = uimenu('Parent', GHandle.Viewer(vIdx).mainFigure, 'Label', 'Edit');

GHandle.Viewer(vIdx).menu.menuView = uimenu('Parent', GHandle.Viewer(vIdx).mainFigure, 'Label', 'View');
GHandle.Viewer(vIdx).menu.menuView_openTable = uimenu('Parent', GHandle.Viewer(vIdx).menu.menuView, ...
    'Label', 'Open Table...');
end

