function  Handle = guidisp(Analysis, PannelHandle , editableField)
	dxsxEdge = 0.05;
	overunderEdge = 0.05;
	textBoxWidth = 0.3;
	textBoxHeight = 0.12;
	

	% create the figure and the editable field if is not specify
	if ~exist('editableField','var')
		editableField = '';
	end
	editableField = lower(editableField);
	
	if ~exist('PannelHandle','var') || isempty(PannelHandle)
		Handle.MainFigure = figure;
		Handle.Pannel = uipanel('Parent',Handle.MainFigure);
	else
		Handle.Pannel = PannelHandle;
	end
	
	% assign the title
	Handle.Pannel.Title = 'Analysis';
	
	% id
	lowerPos = 1 - (textBoxHeight + overunderEdge);
	Handle.IdTextBox = gtextbox(...      
		'Parent',Handle.Pannel,...
		'Value',Analysis.id,...
		'Label','ID:',...
		'Units','normalized',...
		'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);
	
	% Analysis
	Handle.NoteTextBox = gtextbox(...      
		'Parent',Handle.Pannel,...
		'Value',Analysis.analysis,...
		'Label','Analysis done:',...
		'Units','normalized',...
		'Position',[dxsxEdge overunderEdge textBoxWidth (1 - (textBoxHeight + 3*overunderEdge))]);

	
	% Date
	lowerPos = 1 - (textBoxHeight + overunderEdge);
	Handle.BirthdateTextBox = gtextbox(...      
		'Parent',Handle.Pannel,...
		'Value',datestr(Analysis.date, 'dd/mm/yyyy'),...
		'Label','Date:',...
		'Units','normalized',...
		'Position',[(dxsxEdge + 0.4) lowerPos textBoxWidth textBoxHeight]);
	
	
	% note
	lowerPos = 1 - 2*(textBoxHeight + overunderEdge);
	if any(contains(editableField,'note'))
		Handle.NoteEditableTextBox = geditabletext(...      
		'Parent',Handle.Pannel,...
		'Value',Analysis.note,...
		'Label','Note',...
		'Units','normalized',...
		'Position',[(dxsxEdge + 0.4)  lowerPos textBoxWidth textBoxHeight]);
	else
		Handle.NoteTextBox = gtextbox(...      
		'Parent',Handle.Pannel,...
		'Value',Analysis.note,...
		'Label','Note:',...
		'Units','normalized',...
		'Position',[(dxsxEdge + 0.4)  lowerPos textBoxWidth textBoxHeight]);
	end
	
	
	%symply data
	axesWidth = 0.7 - 3*dxsxEdge;
	axesHeight = 1 - (overunderEdge +  2*(textBoxHeight + overunderEdge));
	Handle.Axes = axes(...     
		'Parent',Handle.Pannel,...
		'Units','Normalized',...
		'Visible','on',...
		'Position', [(0.3 + 2*dxsxEdge)  overunderEdge axesWidth axesHeight]...
	);
	
	nField = length(Analysis.SimplyData.Properties.VariableNames);
	
	plot(...    
		Analysis.SimplyData.relativeTime,...
		Analysis.SimplyData{:,2:nField});

end

