function  Handle = guidisp(Analysis, GHandle , editableField)
	dxsxEdge = 0.05;
	overunderEdge = 0.05;
	textBoxWidth = 0.3;
	textBoxHeight = 0.12;	

	textFontSize = GHandle.Preference.Font.sizeM;
	
	idx = GHandle.Temp.idx;
	
	% create the figure and the editable field if is not specify
	if ~exist('editableField','var')
		editableField = '';
	end
	editableField = lower(editableField);
	
	if ~exist('GHandle','var') || isempty(GHandle)
		Handle.MainFigure = figure;
		GHandle.Main.SubPanel.Panel = uipanel('Parent',Handle.MainFigure);
	end
	
	% assign the title
	GHandle.Main.Display.SubPanel(idx).Panel.Title = 'Analysis';
	
	% id
	lowerPos = 1 - (textBoxHeight + overunderEdge);
	GHandle.Main.Display.SubPanel(idx).IdTextBox = gtextbox(...      
		'Parent',GHandle.Main.Display.SubPanel(idx).Panel,...
		'TextString',Analysis.id,...
		'TitleString','ID:',...
		'FontSize',textFontSize,...
		'Units','normalized',...
		'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);
	
	% Analysis
	GHandle.Main.Display.SubPanel(idx).NoteTextBox = gtextbox(...      
		'Parent',GHandle.Main.Display.SubPanel(idx).Panel,...
		'TextString',Analysis.analysis,...
		'TitleString','Analysis done:',...
		'FontSize',textFontSize,...
		'Units','normalized',...
		'Position',[dxsxEdge overunderEdge textBoxWidth (1 - (textBoxHeight + 3*overunderEdge))]);

	
	% Date
	lowerPos = 1 - (textBoxHeight + overunderEdge);
	GHandle.Main.Display.SubPanel(idx).BirthdateTextBox = gtextbox(...      
		'Parent',GHandle.Main.Display.SubPanel(idx).Panel,...
		'TextString',datestr(Analysis.date, 'dd/mm/yyyy'),...
		'TitleString','Date:',...
		'FontSize',textFontSize,...
		'Units','normalized',...
		'Position',[(dxsxEdge + 0.4) lowerPos textBoxWidth textBoxHeight]);
	
	
	% note
	lowerPos = 1 - 2*(textBoxHeight + overunderEdge);
	if any(contains(editableField,'note'))
		GHandle.Main.Display.SubPanel(idx).NoteEditableTextBox = geditabletext(...      
		'Parent',GHandle.Main.Display.SubPanel(idx).Panel,...
		'TextString',Analysis.note,...
		'TitleString','Note',...
		'FontSize',textFontSize,...
		'Units','normalized',...
		'Position',[(dxsxEdge + 0.4)  lowerPos textBoxWidth textBoxHeight]);
	else
		GHandle.Main.Display.SubPanel(idx).NoteTextBox = gtextbox(...      
		'Parent',GHandle.Main.Display.SubPanel(idx).Panel,...
		'TextString',Analysis.note,...
		'TitleString','Note:',...
		'FontSize',textFontSize,...
		'Units','normalized',...
		'Position',[(dxsxEdge + 0.4)  lowerPos textBoxWidth textBoxHeight]);
	end
	
	
	%symply data
	axesWidth = 0.7 - 3*dxsxEdge;
	axesHeight = 1 - (overunderEdge +  2*(textBoxHeight + overunderEdge));
	GHandle.Main.Display.SubPanel(idx).Axes = axes(...     
		'Parent',GHandle.Main.Display.SubPanel(idx).Panel,...
		'Units','Normalized',...
		'Visible','on',...
		'Position', [(0.3 + 2*dxsxEdge)  overunderEdge axesWidth axesHeight]...
	);
	
	nField = length(Analysis.SimplyData.Properties.VariableNames);
	
	plot(...    
		Analysis.SimplyData.reltime,...
		Analysis.SimplyData{:,1:nField-1});

end

