function HandleTextBox= gtextbox(varargin)

Prop.BackgroundColor = [0.9400 0.9400 0.9400];
Prop.BusyAction = 'queue';
Prop.ButtonDownFcn = '';
Prop.Clipping = 'on';
Prop.CreateFcn = '';
Prop.DeleteFcn = '';
Prop.Enable = 'on';
Prop.FontAngle = 'normal';
Prop.FontName = 'Helvetica';
Prop.FontSize = 8;
Prop.FontUnits = 'points';
Prop.FontWeight = 'normal';
Prop.ForegroundColor = [0 0 0];
Prop.HandleVisibility = 'on';
Prop.Interruptible = 'on';
Prop.Label = '';
Prop.LabelFontAngle = 'normal';
Prop.LabelFontName = 'Helvetica';
Prop.LabelFontSize = 6;
Prop.LabelFontUnits = 'points';
Prop.LabelFontWeight = 'normal';
Prop.LabelForegroundColor = [0 0 0];
Prop.LabelHeight = 10;
Prop.LabelHorizontalAlignment = 'left';
Prop.LabelLocation = 'top';
Prop.LabelSpacing = 4;
Prop.LabelTooltipString = '';
Prop.LabelVisible = 'off';
Prop.LabelWidth = 75;
Prop.OuterPosition = [0 0 1 1];
Prop.Padding = 0;
Prop.Position = [0 0 1 1];
Prop.SizeChangedFcn = '';
Prop.Spacing = 0;
Prop.Tag = '';
Prop.TextBackgroundColor = [0.9400 0.9400 0.9400];
Prop.TextEditable = 'on';
Prop.TextForegroundColor = [0 0 0];
Prop.TextHorizontalAlignment = 'left';
Prop.TextInvalidBackgroundColor = [1 0.8000 0.8000];
Prop.TextInvalidForegroundColor = [];
Prop.TextIsValid = 1;
Prop.Units = 'normalized';
Prop.UserData = [];
Prop.Value = [];
Prop.Visible = 'on';

for iField = 1 : 2 : nargin
	Prop.(varargin{iField}) = varargin{iField+1};
end

HandleTextBox = uiw.widget.FixedText(...
					'Parent', Prop.Parent,...
					'BackgroundColor', Prop.BackgroundColor,....
					'ButtonDownFcn', Prop.ButtonDownFcn,...
					'BusyAction', Prop.BusyAction,...
					'Clipping', Prop.Clipping,...
					'CreateFcn', Prop.CreateFcn,...
					'DeleteFcn', Prop.DeleteFcn,...
					'Enable', Prop.Enable,...
					'FontAngle', Prop.FontAngle,...
					'FontName', Prop.FontName,...
					'FontSize', Prop.FontSize,...
					'FontUnits', Prop.FontUnits,...
					'FontWeight', Prop.FontWeight,...
					'ForegroundColor', Prop.ForegroundColor,...
					'HandleVisibility', Prop.HandleVisibility,...
					'Interruptible', Prop.Interruptible,...
					'Label', Prop.Label,...
					'LabelFontAngle', Prop.LabelFontAngle,...
					'LabelFontName', Prop.LabelFontName,...
					'LabelFontSize', Prop.LabelFontSize,...
					'LabelFontUnits', Prop.LabelFontUnits,...
					'LabelFontWeight', Prop.LabelFontWeight,...
					'LabelForegroundColor', Prop.LabelForegroundColor,...
					'LabelHeight', Prop.LabelHeight,...
					'LabelHorizontalAlignment', Prop.LabelHorizontalAlignment,...
					'LabelLocation', Prop.LabelLocation,...
					'LabelSpacing', Prop.LabelSpacing,...
					'LabelTooltipString', Prop.LabelTooltipString,...
					'LabelVisible', Prop.LabelVisible,...
					'LabelWidth', Prop.LabelWidth,...
					'OuterPosition', Prop.OuterPosition,...
					'Padding', Prop.Padding,...
					'Position', Prop.Position,...
					'SizeChangedFcn', Prop.SizeChangedFcn,...
					'Spacing', Prop.Spacing,...
					'Tag', Prop.Tag,...
					'TextBackgroundColor', Prop.TextBackgroundColor,...
					'TextEditable', Prop.TextEditable,...
					'TextForegroundColor', Prop.TextForegroundColor,...
					'TextHorizontalAlignment', Prop.TextHorizontalAlignment,...
					'TextInvalidBackgroundColor', Prop.TextInvalidBackgroundColor,...
					'TextInvalidForegroundColor', Prop.TextInvalidForegroundColor,...
					'TextIsValid', Prop.TextIsValid,...
					'Units', Prop.Units,...
					'UserData', Prop.UserData,...
					'Value', Prop.Value,...
					'Visible', Prop.Visible);						
end

