function [hTE, hT, hE] = gtextedit(parent, label, position, spacing, sizeRatio, configuration)

hTE = uipanel(...
    'Parent', parent,...
    'Units', 'normalize', ...
    'BorderType', 'none', ...
    'Position', position);

if length(spacing) == 1
    spacing = [spacing spacing spacing];
end

vE = (1-(spacing(1)+spacing(2)+spacing(3))) / (sizeRatio+1);
vT = sizeRatio*vE;

switch configuration
    case 'vertical'
        hT = axes(...
            'Parent', hTE,...
            'Units', 'normalize', ...
            'Position',[0 spacing(1)+vE+spacing(2) 1 vT],...
            'XLim', [0 1], ...
            'YLim', [0 1], ...
            'Visible', 'off');
        hT = text(hT, 0, 0.5, label, 'FontSize', 8);
        hE = uicontrol('Style', 'edit',...
            'Parent', hTE, ...
            'String', '10',...
            'Visible','on',...
            'Units', 'normalize', ...
            'HorizontalAlignment', 'left', ...
            'Position', [0 spacing(1) 1 vE]);
    case 'horizontal'
        hT = axes(...
            'Parent', hTE,...
            'Units', 'normalize', ...
            'Position',[spacing(1) 0 vE 1],...
            'XLim', [0 1], ...
            'YLim', [0 1], ...
            'Visible', 'off');
        text(hT, 0, 0.5, label, 'FontSize', 8);
        hE = uicontrol('Style', 'edit',...
            'Parent', hTE, ...
            'String', '10',...
            'Visible','on',...
            'Units', 'normalize', ...
            'HorizontalAlignment', 'left', ...
            'Position', [spacing(1)+vE+spacing(2) 0 vT 1]);
end

