function [MeasureFigure] = measurewindow(Measure, editableField, MainHandle, MainFigure)
%MeasureWINDOW Summary of this function goes here
%   Detailed explanation goes here

% editable field is case unsensitive
editableField = lower(editableField);

	if isempty(MainFigure)
		MeasureFigure.MainFigure = figure(...
		'position', MainHandle.screenSize.*(3/4),...
		'Resize', 'on',...
		'Numbertitle', 'off', ...
		'Toolbar', 'none', ...
		'Menubar', 'none', ...
		'DoubleBuffer', 'on', ...
		'DockControls', 'off', ...
		'Renderer', 'OpenGL',...
		'Visible', 'on' ...
		);
	else
		MeasureFigure.MainFigure = MainFigure;
	end
	
	
%% id
	MeasureFigure.NameTextBox = uiw.widget.FixedText(...      
		'Parent',MeasureFigure.MainFigure,...
		'Value',Measure.id,...
		'Label','ID:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.9 0.3, 0.09]);

%% Time length
	if any(contains(editableField,'timelength'))
		MeasureFigure.NameEditableTextBox = uiw.widget.EditableText(...      
		'Parent',MeasureFigure.MainFigure,...
		'Value',datestr(Measure.updateRate, 'HH:MM:SS.FFF'),...
		'Label','Time Length:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.75 0.3, 0.09]);
	else
		MeasureFigure.NameTextBox = uiw.widget.FixedText(...      
		'Parent',MeasureFigure.MainFigure,...
		'Value',datestr(Measure.updateRate, 'HH:MM:SS.FFF'),...
		'Label','Time Length:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.75 0.3, 0.09]);
	end
	
%% Update Rate
	if any(contains(editableField,'updaterate'))
		MeasureFigure.NameEditableTextBox = uiw.widget.EditableText(...      
		'Parent',MeasureFigure.MainFigure,...
		'Value',num2str(Measure.updateRate),...
		'Label','Update Rate:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.60 0.3, 0.09]);
	else
		MeasureFigure.NameTextBox = uiw.widget.FixedText(...      
		'Parent',MeasureFigure.MainFigure,...
		'Value',num2str(Measure.updateRate),...
		'Label','Update Rate:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.60 0.3, 0.09]);
	end

%% date
	if isnat(Measure.date) 
		dateString = 'NaT';
	else
		dateString = datestr(Measure.date, 'dd/mm/yyyy');
	end
	
	if any(contains(editableField,'date'))
		MeasureFigure.NameEditableTextBox = uiw.widget.EditableText(...      
		'Parent',MeasureFigure.MainFigure,...
		'Value',dateString,...
		'Label','Date:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.45 0.3, 0.09]);
	else
		MeasureFigure.NameTextBox = uiw.widget.FixedText(...      
		'Parent',MeasureFigure.MainFigure,...
		'Value',dateString,...
		'Label','Date:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.45 0.3, 0.09]);
	end
	

%% note
	if any(contains(editableField,'note'))
		MeasureFigure.NameEditableTextBox = uiw.widget.EditableText(...      
		'Parent',MeasureFigure.MainFigure,...
		'Value',Measure.note,...
		'Label','Note',...
		'LabelLocation','top',...
		'IsMultiLine', true,...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.05 0.3, 0.35]);
	else
		MeasureFigure.NameTextBox = uiw.widget.FixedText(...      
		'Parent',MeasureFigure.MainFigure,...
		'Value',Measure.note,...
		'Label','Note:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.05 0.3, 0.35]);
	end

%% other info	
	
	infoList = fieldnames(Measure.Info);
	nInfo = length(infoList);
	for iInfo = 1 : nInfo
		field = infoList{iInfo};
		ypos = 0.9*(1-(iInfo-1)/nInfo);
		xpos = 0.5;
			
		
		if any(contains(editableField,field))
			MeasureFigure.NameEditableTextBox = uiw.widget.EditableText(...      
			'Parent',MeasureFigure.MainFigure,...
			'Value',Measure.Info.(field),...
			'Label',field,...
			'LabelLocation','top',...
			'IsMultiLine', true,...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[xpos ypos 0.3, 0.09]);
		else
			MeasureFigure.NameTextBox = uiw.widget.FixedText(...      
			'Parent',MeasureFigure.MainFigure,...
			'Value',Measure.Info.(field),...
			'Label',field,...
			'LabelLocation','top',...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[xpos ypos 0.3, 0.09]);
		end
	end
end


