function  handleNewDatabase = newdatabasewindow(gNirsPath)
%NEWDATABASEWINDOW Summary of this function goes here

% add other settings features
handleNewDatabase.gNirsPath = gNirsPath;
handleNewDatabase.screenSize = get(0,'ScreenSize');
handleNewDatabase.figureSize = [(1/4).*handleNewDatabase.screenSize(3:4),...
								(1/2).*handleNewDatabase.screenSize(3:4)];


handleNewDatabase.MainFigure = figure('Visible', 'off', ...
	'position', handleNewDatabase.figureSize,...
    'Resize', 'on',...
    'Name', 'New Database', ...
    'Numbertitle', 'off', ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL');


standardPath = fullfile(gNirsPath, 'DataBase');

handleNewDatabase.FolderSelector = uiw.widget.FolderSelector(...
						'Parent', handleNewDatabase.MainFigure, ...
						'Value', standardPath, ...
						'Label','Select a folder:',...
						'LabelLocation','top',...
						'LabelWidth',90,...
						'Units', 'normalized', ...
						'Position', [0.05 0.05 0.7 0.125]);

handleNewDatabase.CreateButton = uicontrol('Style', 'pushbutton',... 
						'String', 'Create',...
						'Units', 'normalized', ...
						'Position', [0.85 0.05 0.1 0.1],...
						'Callback', {@initialize, handleNewDatabase});      


set(handleNewDatabase.MainFigure, 'Visible', 'on');
end




function initialize(~, ~, MainHandle)
	
	dataBasePath = MainHandle.FolderSelector.Value;

	GDataBase.create(dataBasePath, MainHandle.gNirsPath);

	close(MainHandle.MainFigure);
end






