function StudyFigure = NewNIRSStudy(~, ~, Hmain,~)
		
	
	

	StudyFigure.MainFigure = figure('Visible', 'on', ...
	'position', Hmain.screenSize.*(1/2),...
    'Resize', 'on',...
    'Name', 'New NIRS Study', ...
    'Numbertitle', 'off', ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL',...
	'Visible', 'off' ...
	);
	
	StudyFigure.Subject.StudyName = uiw.widget.EditableText(...      
    'Parent',StudyFigure.MainFigure,...=
    'Value','Insert Name',...
    'Callback',@(h,e)disp(e),...
    'Label','Study Name:',...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.80 0.35 0.15]);

	StudyFigure.ListBox = uicontrol(...
			'Parent', StudyFigure.MainFigure, ...
			'Style','listbox',...
			'Units', 'normalize', ...
			'Max', 2,...
			'Position',  [0.05 0.05 0.4 0.55],...
			'String',[],...
			'Value',[]);

	StudyFigure.StudySelector = uiw.widget.FolderSelector(...
    'Parent', StudyFigure.MainFigure, ...
    'Value', [], ...
    'Label','Choose a data file:', ...
    'LabelLocation','top',...
    'LabelWidth',150,...
    'Units', 'normalize', ...
    'Position', [0.05 0.60 0.4 0.15],...	
	'Callback',@(ObjectHandle, Event)foudfile(ObjectHandle, Event,StudyFigure)...
	);

	
	

	StudyFigure.LoadButton = uicontrol('Style', 'pushbutton',...	
    'Parent', StudyFigure.MainFigure, ...
	'String', 'Load',...
	'Units', 'normalize', ...
	'Position', [0.8 0.15 0.2 0.1],...
	'Callback', {@AddStudytoDataBase ,Hmain ,StudyFigure }); 

	

	StudyFigure.MainFigure.Visible = 'on';

end


%% extra function


function	AddStudytoDataBase( ~, ~, MainHandle , studyhandle )


	pathDataBase = MainHandle.dataBasePath;
	
	NewStudy = NIRSStudy('name', studyhandle.Subject.StudyName.Value);
	
	DataBase = addstudydatabase(NewStudy, pathDataBase);
	
	close(studyhandle.MainFigure);
	
	
	
	
	NIRSTree(MainHandle,DataBase);
	
end



function foudfile(ObjectHandle, ~,StudyHandle)
	searchingPath = ObjectHandle.FullPath;
	listOfFile = dir(searchingPath);
	listOfTxt = listOfFile(contains({listOfFile.name}, '.txt'));
	
	StudyHandle.ListBox.String = {listOfTxt.name};
	drawnow
end



























