function probesimulationwindow(GHandle)
figureSize = GHandle.Preference.Figure.sizeMedium;

%% Set color theme
backgroundColor = GHandle.Preference.Theme.backgroundColor;
foregroundColor = GHandle.Preference.Theme.foregroundColor;
highlightColor = GHandle.Preference.Theme.highlightColor;
textForegroundColor = [0 0 0];
sourceColor = 'r';
detectorColor = 'b';
channelColor = 'k';

%% Set font
defaultFontName = GHandle.Preference.Font.name;

Probe = GHandle.CurrentDataSet.Probe;
DBProbe = GHandle.DataBase.findid(Probe.id);
GHandle.TempWindow.Probe = Probe;
GHandle.TempWindow.DBProbe = DBProbe;
%% Create GUI
GHandle.TempWindow.SimulationFigure = figure(...
    'position', figureSize,...
    'Color',backgroundColor,...
    'Resize', 'on',...
    'Name', 'Probe Sensitivity Simulation', ...
    'Numbertitle', 'off', ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Visible', 'off', ...
    'DeleteFcn', {@close_figure, GHandle});

GHandle.TempWindow.ParameterPanel = uipanel('Parent', GHandle.TempWindow.SimulationFigure,...
    'Units', 'normalized', ...
    'Position', [0 0 0.5 1]);
GHandle.TempWindow.RunPanel = uipanel('Parent', GHandle.TempWindow.SimulationFigure,...
    'Units', 'normalized', ...
    'Position', [0.5 0 0.5 1]);
% GHandle.TempWindow.SettingPanel = uipanel('Parent', GHandle.TempWindow.SimulationFigure,...
%     'Units', 'normalized', ...
%     'Position', [0.81 0 0.2 1]);

GHandle.TempWindow.NPhotonLabel = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.15 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'N photons');
GHandle.TempWindow.NPhoton = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.1 0.8 0.05],...
    'String', '1e6', ...
    'Visible', 'on');

GHandle.TempWindow.TimeLabel = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.3 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Time (Tstart, Tstep, Tend)');
GHandle.TempWindow.TStart = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.25 0.25 0.05],...
    'String', '0', ...
    'Visible', 'on');
GHandle.TempWindow.TStep = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.375 0.25 0.25 0.05],...
    'String', '1e-11', ...
    'Visible', 'on');
GHandle.TempWindow.TEnd = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.65 0.25 0.25 0.05],...
    'String', '1e-9', ...
    'Visible', 'on');

srcTypes = {'pencil'; 'isotropic'; 'cone'; 'gaussian'; 'planar'; 'pattern';...
    'fourier'; 'arcsine'; 'disk'; 'fourierx'; 'fourierx2d'; 'zgaussian'};
GHandle.TempWindow.SrcTypeLabel = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.45 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Source type');
GHandle.TempWindow.SrcType = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'popup', ...
    'Units', 'normalized',...
    'Position', [0.1 0.4 0.8 0.05],...
    'String', srcTypes, ...
    'Visible', 'on');

GHandle.TempWindow.DebugLevelLabel = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.6 0.8 0.05],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Debug level (subset of [MCBWDIOXATRPE])');
GHandle.TempWindow.DebugLevel = uicontrol('Parent', GHandle.TempWindow.ParameterPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.55 0.8 0.05],...
    'String', 'TP', ...
    'Visible', 'on');

GHandle.TempWindow.RunButton = uicontrol('Parent', GHandle.TempWindow.RunPanel, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized',...
    'Position', [0.1 0.1 0.8 0.8],...
    'String', 'Run like hell', ...
    'Visible', 'on', ...
    'Callback', @(h,e)run_simulation(h,e,GHandle));

%% Check forward solver

%% Check atlas

%% Simulate photon migration

%% Turn on figure
GHandle.TempWindow.SimulationFigure.Visible = 'on';
end

function run_simulation(~, ~, GHandle)

% cfg.nphoton = str2double(GHandle.TempWindow.NPhoton.Value);
% 
% cfg.node = He.node(:,1:3);
% cfg.face = He.face;
% cfg.elem = He.elem;
% cfg.elemprop = ones(size(cfg.elem,1),1);
% cfg.srcpos = pos;
% 
% cfg.srctype = GHandle.TempWindow.SrcType.String(GHandle.TempWindow.SrcType.Value);
% cfg.srcparam1 = 0;
% cfg.srcparam2 = 0; 
% 
% cfg.tstart = str2double(GHandle.TempWindow.TStart.String);
% cfg.tend = str2double(GHandle.TempWindow.TEnd.String);
% cfg.tstep = str2double(GHandle.TempWindow.TStep.String);
% 
% cfg.debuglevel = GHandle.TempWindow.DebugLevel.String;
% 
% cfg1.prop = [0.0000  0.00 1.0 1.0; ...    % Air
%              0.0170 17.50 0.9 1.3; ...     % ECT
%              0.0041  0.32 0.9 1.3; ...     % CSF
%              0.0480  5.00 0.9 1.3; ...     % GM
%              0.0370 10.00 0.9 1.3; ...     % WM
%              0.0370 10.00 0.9 1.3; ...     % Brainstem
%              0.0370 10.00 0.9 1.3];        % Cerebellum
% tic
% fluxx1 = mmclab(cfg1);
% t(1) = toc;

%% save the results 

%% remove this code {
[FILENAME, Path] = uigetfile('*.mat');
load(fullfile(Path, FILENAME))
%% }
ForwardSymulation = NirsForward(...
        'atlasId', GHandle.TempWindow.DBProbe.atlasId , ...
        'probeId', GHandle.TempWindow.DBProbe.id , ...
        'date', datetime, ...
        'node', He.node, ...
        'src', src3, ...
        'det', det3, ...
        'srcDir', srcdir, ...
        'detDir', detdir, ...
        'srcFlux', fluxsrc, ...
        'detFlux', fluxdet, ...
        'note', '');

save([GHandle.TempWindow.DBProbe.path,'ForwardSym'], 'ForwardSymulation');
probeMask = GHandle.DataBase.Probe == GHandle.TempWindow.DBProbe;
GHandle.DataBase.Probe(probeMask).forwardFlag = true;
GHandle.DataBase.save;

close(GHandle.TempWindow.SimulationFigure);
end

function close_figure(Handle, ~, GHandle)
delete(Handle);
GHandle.TempWindow = [];
end
