function [StudyFigure] = studywindow(Study, editableField, MainHandle)
%SUBJECTWINDOW Summary of this function goes here
%   Detailed explanation goes here





% editable field is case unsensitive
editableField = lower(editableField);





	StudyFigure.MainFigure = figure(...
	'position', MainHandle.screenSize.*(3/4),...
    'Resize', 'on',...
    'Name', 'New NIRS measure', ...
    'Numbertitle', 'off', ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL',...
	'Visible', 'on' ...
);
%% id
	StudyFigure.NameTextBox = uiw.widget.FixedText(...      
		'Parent',StudyFigure.MainFigure,...
		'Value',Study.id,...
		'Label','ID:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.9 0.3, 0.09]);


%% name	
	if any(contains(editableField,'name'))
		StudyFigure.NameEditableTextBox = uiw.widget.EditableText(...      
		'Parent',StudyFigure.MainFigure,...
		'Value',Study.name,...
		'Label','Name',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.75 0.3, 0.09]);
	else
		StudyFigure.NameTextBox = uiw.widget.FixedText(...      
		'Parent',StudyFigure.MainFigure,...
		'Value',Study.name,...
		'Label','Name:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.75 0.3, 0.09]);
	end


%% date
	if any(contains(editableField,'date'))
		StudyFigure.NameEditableTextBox = uiw.widget.EditableText(...      
		'Parent',StudyFigure.MainFigure,...
		'Value',datestr(Study.date, 'dd/mm/yyyy'),...
		'Label','Date of Creation',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.45 0.3, 0.09]);
	else
		StudyFigure.NameTextBox = uiw.widget.FixedText(...      
		'Parent',StudyFigure.MainFigure,...
		'Value',datestr(Study.date, 'dd/mm/yyyy'),...
		'Label','Date of Creation:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.45 0.3, 0.09]);
	end
	

%% note
	if any(contains(editableField,'note'))
		StudyFigure.NameEditableTextBox = uiw.widget.EditableText(...      
		'Parent',StudyFigure.MainFigure,...
		'Value',Study.note,...
		'Label','Note',...
		'LabelLocation','top',...
		'IsMultiLine', true,...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.05 0.3, 0.35]);
	else
		StudyFigure.NameTextBox = uiw.widget.FixedText(...      
		'Parent',StudyFigure.MainFigure,...
		'Value',Study.note,...
		'Label','Note:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[0.05 0.05 0.3, 0.35]);
	end


end

