function [SubjectFigure] = subjectwindow(Subject, editableField, MainHandle)
%SUBJECTWINDOW Summary of this function goes here
%   Detailed explanation goes here
	SubjectFigure.MainFigure = figure(...
	'position', MainHandle.screenSize.*(3/4),...
    'Resize', 'on',...
    'Name', 'New NIRS measure', ...
    'Numbertitle', 'off', ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL',...
	'Visible', 'off' ...
);
	
	
	
end

