function  Handle = guidisp(Subject, PannelHandle , editableField)
	dxsxEdge = 0.05;
	overunderEdge = 0.009;
	textBoxWidth = 0.3;
	textBoxHeight = 0.12;

	

	% create the figure and the editable field if is not specify
	if ~exist('editableField','var')
		editableField = '';
	end
	editableField = lower(editableField);
	
	if ~exist('PannelHandle','var') || isempty(PannelHandle)
		Handle.MainFigure = figure;
		Handle.Pannel = uipanel('Parent',Handle.MainFigure);
	else
		Handle.Pannel = PannelHandle;
	end
	
	% assign the title
	Handle.Pannel.Title = 'Subject';
	
	% id
	lowerPos = (0.3 +overunderEdge) + 3 *( 0.7 - overunderEdge)/4;
	Handle.IdTextBox = uiw.widget.FixedText(...      
		'Parent',Handle.Pannel,...
		'Value',Subject.id,...
		'Label','ID:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);

	
	lowerPos = (0.3 +overunderEdge) + 2 *( 0.7 - overunderEdge)/4;
	% name	
	if any(contains(editableField,'name'))
		Handle.NameEditableTextBox = uiw.widget.EditableText(...      
		'Parent',Handle.Pannel,...
		'Value',Subject.name,...
		'Label','Name',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);
	else
		Handle.NameTextBox = uiw.widget.FixedText(...      
		'Parent',Handle.Pannel,...
		'Value',Subject.name,...
		'Label','Name:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);
	end
	
	
	% Surname	
	lowerPos = (0.3 +overunderEdge) + 1 *( 0.7 - overunderEdge)/4;
	if any(contains(editableField,'surname'))
		Handle.SurnameEditableTextBox = uiw.widget.EditableText(...      
		'Parent',Handle.Pannel,...
		'Value',Subject.surName,...
		'Label','Surname',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);
	else
		Handle.SurnameTextBox = uiw.widget.FixedText(...      
		'Parent',Handle.Pannel,...
		'Value',Subject.surName,...
		'Label','Surname:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);
	end
	
	% Birthdate
	lowerPos = (0.3 +overunderEdge);
	if any(contains(editableField,'birthdate'))
		Handle.BirthdateEditableTextBox = uiw.widget.EditableText(...      
		'Parent',Handle.Pannel,...
		'Value',datestr(Subject.birthDay, 'dd/mm/yyyy'),...
		'Label','Name',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);
	else
		Handle.BirthdateTextBox = uiw.widget.FixedText(...      
		'Parent',Handle.Pannel,...
		'Value',datestr(Subject.birthDay, 'dd/mm/yyyy'),...
		'Label','Birthday:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);
	end
	
	% note
	if any(contains(editableField,'note'))
		Handle.NoteEditableTextBox = uiw.widget.EditableText(...      
		'Parent',Handle.Pannel,...
		'Value',Subject.note,...
		'Label','Note',...
		'LabelLocation','top',...
		'IsMultiLine', true,...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[dxsxEdge overunderEdge textBoxWidth 0.3-overunderEdge]);
	else
		Handle.NoteTextBox = uiw.widget.FixedText(...      
		'Parent',Handle.Pannel,...
		'Value',Subject.note,...
		'Label','Note:',...
		'LabelLocation','top',...
		'LabelWidth',90,...
		'Units','normalized',...
		'Position',[dxsxEdge overunderEdge textBoxWidth 0.3-overunderEdge]);
	end
	% plot the info list
	infoList = fieldnames(Subject.Info);
	nInfo = length(infoList);
	for iInfo = 1 : nInfo
		field = infoList{iInfo};
		fieldValue = num2str(Subject.Info.(field));
		
		ypos = (1 - overunderEdge - textBoxHeight ) -  (iInfo-1)/nInfo;
		xpos = 0.5;
			
		tag = [field ,'EditableTextBox'];
		if any(contains(editableField,field))
			Handle.(tag) = uiw.widget.EditableText(...      
			'Parent',Handle.Pannel,...
			'Value',fieldValue,...
			'Label',[field,':'],...
			'LabelLocation','top',...
			'IsMultiLine', true,...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[xpos ypos textBoxWidth, textBoxHeight]);
		else
			Handle.(tag) = uiw.widget.FixedText(...      
			'Parent',Handle.Pannel,...
			'Value',fieldValue,...
			'Label',[field,':'],...
			'LabelLocation','top',...
			'LabelWidth',90,...
			'Units','normalized',...
			'Position',[xpos ypos textBoxWidth, textBoxHeight]);
		end
	end
	
end

