%% Fixed Text
%   Copyright 2017-2018 The MathWorks, Inc.

%% Create the widget

f = figure(...
    'Toolbar','none',...
    'MenuBar','none',...
    'NumberTitle','off',...
    'Units','pixels',...
    'Position',[100 100 320 45]);
movegui(f,[100 -100])

w = uiw.widget.FixedText(...
    'Parent',f,...=
    'Value','This is fixed text',...
    'BackgroundColor',[.7 .7 .7],...
    'Units','pixels',...
    'Position',[10 10 300 25]);