function addsubjecttemplate(~, ~, GHandle, studyId)
figureSize = GHandle.Preference.Figure.sizeMedium;




GHandle.TempWindow.AddSubjectTemplate = figure(...
    'position', figureSize,...
    'Resize', 'on',...
    'Name', 'New NIRS Study', ...
    'Numbertitle', 'off', ...
    'CloseRequestFcn', @(h,e)close_function(h,e, GHandle),...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL',...
    'Visible', 'off' ...
    );

GHandle.TempWindow.AddSubjectField = uiw.widget.EditableText(...
    'Parent', GHandle.TempWindow.AddSubjectTemplate,...
    'Value','NewField (no special characters)',...
    'Label','Add new field (space in between)',...
    'IsMultiLine', 1,...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.05 0.5 0.8]);

GHandle.TempWindow.AddSubjectButton = uicontrol('Style', 'pushbutton',...
    'Parent', GHandle.TempWindow.AddSubjectTemplate,...
    'String', 'Load',...
    'Units', 'normalize', ...
    'Position', [0.8 0.15 0.2 0.1],...
    'Callback', {@Add_template ,GHandle,studyId}...
    );

GHandle.TempWindow.AddSubjectTemplate.Visible = 'on';
end

function Add_template( ~, ~, GHandle, studyId)

field = strsplit(GHandle.TempWindow.AddSubjectField.Value);

DBStudy = GHandle.DataBase.findid(studyId);
Study = DBStudy.load;

for ifield = 1:1:length(field)
    Study.SubjectTemplate.Info.(field{ifield}) = [] ;
end


DBStudy.substitute(Study);

 close_function(GHandle.TempWindow.AddSubjectTemplate , [] ,GHandle)

end

function close_function(h , ~ ,GHandle)
delete(h);
GHandle.TempWindow = [];
end


