f = figure;
hold on

trisurf(Scalp.face,...
    Scalp.node(:,1),Scalp.node(:,2),Scalp.node(:,3),...
    ones(size(Scalp.node(:,3))),...
    'SpecularStrength', 0, ...
    'EdgeColor','none',...
    'FaceColor',[0.7 0.7 0.7],...
    'FaceAlpha',0.3);

trisurf(GM.face,...
GM.node(:,1),GM.node(:,2),GM.node(:,3),...
ones(size(GM.node(:,3))),...
'SpecularStrength', 0, ...
'EdgeColor','none',...
'FaceColor',[0.7 0.2 0],...
'FaceAlpha',0.3);

trisurf(WM.face,...
WM.node(:,1),WM.node(:,2),WM.node(:,3),...
ones(size(WM.node(:,3))),...
'SpecularStrength', 0, ...
'EdgeColor','none',...
'FaceColor',[0 0.2 0.2],...
'FaceAlpha',0.3);

light('Position',[100 0 100]);     % x is left->right, y is back->front
light('Position',[-100 0 100]);

axis equal
axis off
axis vis3d

% circle on z=0 plane
theta1 = pi/2;
theta2 = 3*pi/2;
t = linspace(theta1,theta2);
x = cos(t);
y = sin(t);
z = 0*t;
origin = [0,0,0];
center = [-2,-20,0];
radius = 70;
shrink = 5; % points
pnts = [radius.*x+center(1); radius.*y+center(2); z+center(3)];
%pnts = [center', pnts];
plot3(pnts(1,shrink:end-shrink), pnts(2,shrink:end-shrink), pnts(3,shrink:end-shrink), ...
    'Color', 'r', ...
    'LineStyle', '-', ...
    'LineWidth', 3);
p1 = pnts(:,1);
text(p1(1), p1(2), p1(3), 'Rostral', ...
    'Color', 'r')
p2 = pnts(:,end);
text(p2(1), p2(2), p2(3), 'Caudal', ...
    'Color', 'r')

n0 = [0;0;1]; 
n0 = n0/norm(n0);

%Rotate circle
% n1(1)*x + n1(2)*y + n1(3)*z = 0
n1 = [1;0;0]; 
n1 = n1/norm(n1); 
% theta is the angle between normals
c = dot(n0,n1) / ( norm(n0)*norm(n1) ); % cos(theta)
s = sqrt(1-c*c);                        % sin(theta)
u = cross(n0,n1) / ( norm(n0)*norm(n1) ); % rotation axis...
u = u/norm(u); % ... as unit vector
C = 1-c;
% the rotation matrix
R = [u(1)^2*C+c, u(1)*u(2)*C-u(3)*s, u(1)*u(3)*C+u(2)*s
    u(2)*u(1)*C+u(3)*s, u(2)^2*C+c, u(2)*u(3)*C-u(1)*s
    u(3)*u(1)*C-u(2)*s, u(3)*u(2)*C+u(1)*s, u(3)^2*C+c];
% Rotated points
newPnts = R*pnts;
colorplot = 'b';
plot3(newPnts(1,shrink:end-shrink), newPnts(2,shrink:end-shrink), newPnts(3,shrink:end-shrink), ...
    'Color', colorplot, ...
    'LineStyle', '-', ...
    'LineWidth', 3);

p1 = newPnts(:,1);
text(p1(1), p1(2), p1(3), 'Rostral', ...
    'Color', colorplot)
p2 = newPnts(:,end);
text(p2(1), p2(2), p2(3), 'Caudal', ...
    'Color', colorplot)