%% Pruning
UserParameters = struct;
Parameters = struct;

UserParameters(1).name = 'Minimum value';
UserParameters(1).field = 'max';
UserParameters(1).string = '';
UserParameters(1).style = 'edit';

UserParameters(2).name = 'Maximum value';
UserParameters(2).field = 'max';
UserParameters(2).string = '';
UserParameters(2).style = 'edit';

UserParameters(3).name = 'Max standard deviation';
UserParameters(3).field = 'max';
UserParameters(3).string = '';
UserParameters(3).style = 'edit';

Parameters.max = 1;
Parameters.min = 1;
Parameters.std = 1;

MethodList(1) = NirsMethod(... 
'Parameters', Parameters,...
'UserParameters', UserParameters,...
'description', 'Pruning' ,...
'methodFunction',	@pruning,...
'name', 'Pruning' ,...
'note', [] ,...
'plotFunction',	@plot,...
'tag', 'Pruning',... 
'type', 'General'...
);



%% Low Pass
UserParameters = struct;
Parameters = struct;

UserParameters(1).name ='Low Pass Cutoff frequency [Hz]';
UserParameters(1).field = 'freq';
UserParameters(1).string = '';
UserParameters(1).style = 'edit';

Parameters.freq = 1;

MethodList(2) = NirsMethod(... 
'Parameters', Parameters,...
'UserParameters', UserParameters,...
'description', 'Low-pass filter method' ,...
'methodFunction',	@(dataIn, Parameters)lowpassfilter(dataIn, Parameters),...
'name', 'LowPass Filter' ,...
'note', [] ,...
'plotFunction',	@plot,...
'subType', 'Spectral',... 
'tag', 'LowPass',... 
'type', 'Filter'...
);


%% High Pass
UserParameters = struct;
Parameters = struct;

UserParameters(1).name = 'High Pass Cutoff frequency [Hz]';
UserParameters(1).field = 'freq';
UserParameters(1).string = '';
UserParameters(1).style = 'edit';

Parameters.freq = 1;

MethodList(3) = NirsMethod(... 
'Parameters', Parameters,...
'UserParameters', UserParameters,...
'description', 'High-pass filter method' ,...
'methodFunction',	@highpassfilter,...
'name', 'HighPass Filter' ,...
'note', [] ,...
'plotFunction',	@plot,...
'subType', 'Spectral',... 
'tag', 'HighPass',... 
'type', 'Filter'...
);


%% Band Pass
UserParameters = struct;
Parameters = struct;

UserParameters(1).name = 'Low frequency [Hz]';
UserParameters(1).field = 'lowFreq';
UserParameters(1).string = '';
UserParameters(1).style = 'edit';
UserParameters(2).name = 'High frequency [Hz]';
UserParameters(2).field = 'highFreq';
UserParameters(2).string = '';
UserParameters(2).style = 'edit';

Parameters.lowFreq = 1;
Parameters.highFreq = 1;

MethodList(4) = NirsMethod(... 
'Parameters', Parameters,...
'UserParameters', UserParameters,...
'description', 'Band-pass filter method' ,...
'methodFunction',	@bandpassfilter,...
'name', 'BandPass Filter' ,...
'note', [] ,...
'plotFunction',	@plot,...
'subType', 'Spectral',... 
'tag', 'BandPass',... 
'type', 'Filter'...
);


%% Calibrate
UserParameters = struct;
Parameters = struct;

Parameters(1).name = 'Calibrate';
UserParameters(1).field = 'freq';
UserParameters(1).string = '';
UserParameters(1).style = 'edit';

MethodList(5) = NirsMethod(... 
'Parameters', Parameters,...
'UserParameters', UserParameters,...
'description', 'Calibrate method' ,...
'methodFunction',	@calibrate,...
'name', 'Calibrate' ,...
'note', [] ,...
'plotFunction',	@plot,...
'subType', '',... 
'tag', 'Calibrate',... 
'type', 'General'...
);


%% Decalibrate
UserParameters = struct;
Parameters = struct;

Parameters(1).name = 'Decalibrate';
UserParameters(1).field = 'freq';
UserParameters(1).string = '';
UserParameters(1).style = 'edit';

MethodList(6) = NirsMethod(... 
'Parameters', Parameters,...
'UserParameters', UserParameters,...
'description', 'Decalibrate method' ,...
'methodFunction',	@decalibrate,...
'name', 'Decalibrate' ,...
'note', [] ,...
'plotFunction',	@plot,...
'subType', '',... 
'tag', 'Decalibrate',... 
'type', 'General'...
);

%% Block average
UserParameters = struct;
Parameters = struct;

UserParameters(1).name = 'Conditions';
UserParameters(1).field = 'condition';
UserParameters(1).string = 'Event';
UserParameters(1).style = 'listbox';
UserParameters(2).name =  'Start (s)';
UserParameters(2).field = 'start';
UserParameters(2).string = '';
UserParameters(2).style = 'edit';
UserParameters(3).name =  'Stop (s)';
UserParameters(3).field = 'stop';
UserParameters(3).string = '';
UserParameters(3).style = 'edit';
UserParameters(4).name = 'Detrend';
UserParameters(4).field = 'detrend';
UserParameters(4).string = '';
UserParameters(4).style = 'checkbox';


Parameters.condition = [];
Parameters.start = -1;
Parameters.stop = 1;
Parameters.detrend = 0;
Parameters.Event = [];

MethodList(7) = NirsMethod(... 
'Parameters', Parameters,...
'UserParameters', UserParameters,...
'description', 'Block average method' ,...
'methodFunction', @(dataIn, Parameters)blockaverage(dataIn, Parameters),...
'name', 'Block Average' ,...
'note', [] ,...
'plotFunction',	@plot,...
'tag', 'Blockaverage',... 
'type', 'General'...
);


%% Pruning
UserParameters = struct;
Parameters = struct;


MethodList(8) = NirsMethod(... 
'Parameters', Parameters,...
'UserParameters', UserParameters,...
'description', 'Generalizzed Linear Model (GLS)' ,...
'methodFunction',	@generalizedlinearmodel,...
'name', 'GLS' ,...
'note', [] ,...
'plotFunction',	@plot,...
'tag', 'GLS',... 
'type', 'Statistical'...
);

%% Save
%save( '/home/pagno/Desktop/MyProg/Method/MethodList.mat' , 'MethodList')
save( 'C:\Users\matteo.caffini\Documents\MATLAB\Gnirs\Method\MethodList.mat' , 'MethodList')