%% Pruning
Parameters = struct;
Parameters(1).name = 'Minimum value';
Parameters(1).value = 1;
Parameters(1).style = 'edit';
Parameters(1).name = 'Maximum value';
Parameters(1).value = 1;
Parameters(1).style = 'edit';
Parameters(1).name = 'Max standard deviation';
Parameters(1).value = 1;
Parameters(1).style = 'edit';

MethodList(1) = NirsMethod(... 
'Parameters', Parameters,...
'description', 'Pruning' ,...
'inputType',  'TxC',...
'methodFunction',	@pruning,...
'name', 'Pruning' ,...
'note', [] ,...
'outputType',	'TxC',...
'plotFunction',	@plot,...
'tag', 'Pruning',... 
'type', 'General'...
);


% %% OD2Concentration
% Parameters(1).name = 'Path Length';
% Parameters(1).value = 1;
% Parameters(1).style = 'edit';
% 
% MethodList(8) = NirsMethod(... 
% 'Parameters', Parameters,...
% 'description', 'Low-pass filter method' ,...
% 'inputType',  'TxC',...
% 'methodFunction',	@lowpassfilter,...
% 'name', 'LowPass Filter' ,...
% 'note', [] ,...
% 'outputType',	'TxC',...
% 'plotFunction',	@plot,...
% 'subType', 'Spectral',... 
% 'tag', 'LowPass',... 
% 'type', 'Filter'...
% );



%% Low Pass
Parameters = struct;
Parameters(1).name = 'Low Pass Cutoff frequency [Hz]';
Parameters(1).value = 1;
Parameters(1).style = 'edit';

MethodList(2) = NirsMethod(... 
'Parameters', Parameters,...
'description', 'Low-pass filter method' ,...
'inputType',  'TxC',...
'methodFunction',	@(dataIn, Parameters)lowpassfilter(dataIn, Parameters),...
'name', 'LowPass Filter' ,...
'note', [] ,...
'outputType',	'TxC',...
'plotFunction',	@plot,...
'subType', 'Spectral',... 
'tag', 'LowPass',... 
'type', 'Filter'...
);


%% High Pass
Parameters = struct;
Parameters(1).name = 'High Pass Cutoff frequency [Hz]';
Parameters(1).value = 1;
Parameters(1).style = 'edit';

MethodList(3) = NirsMethod(... 
'Parameters', Parameters,...
'description', 'High-pass filter method' ,...
'inputType',  'TxC',...
'methodFunction',	@highpassfilter,...
'name', 'HighPass Filter' ,...
'note', [] ,...
'outputType',	'TxC',...
'plotFunction',	@plot,...
'subType', 'Spectral',... 
'tag', 'HighPass',... 
'type', 'Filter'...
);


%% Band Pass
Parameters = struct;
Parameters(1).name = 'Low frequency [Hz]';
Parameters(1).value = 1;
Parameters(1).style = 'edit';
Parameters(2).name = 'High frequency [Hz]';
Parameters(2).value = 2;
Parameters(2).style = 'edit';

MethodList(4) = NirsMethod(... 
'Parameters', Parameters,...
'description', 'Band-pass filter method' ,...
'inputType',  'TxC',...
'methodFunction',	@bandpassfilter,...
'name', 'BandPass Filter' ,...
'note', [] ,...
'outputType',	'TxC',...
'plotFunction',	@plot,...
'subType', 'Spectral',... 
'tag', 'BandPass',... 
'type', 'Filter'...
);


%% Calibrate
Parameters = struct;
Parameters(1).name = 'Calibrate';
Parameters(1).value = '';
Parameters(1).style = 'text';

MethodList(5) = NirsMethod(... 
'Parameters', Parameters,...
'description', 'Calibrate method' ,...
'inputType',  'TxC',...
'methodFunction',	@calibrate,...
'name', 'Calibrate' ,...
'note', [] ,...
'outputType',	'TxC',...
'plotFunction',	@plot,...
'subType', '',... 
'tag', 'Calibrate',... 
'type', 'General'...
);


%% Decalibrate
Parameters = struct;
Parameters(1).name = 'Decalibrate';
Parameters(1).value = '';
Parameters(1).style = 'text';

MethodList(6) = NirsMethod(... 
'Parameters', Parameters,...
'description', 'Decalibrate method' ,...
'inputType',  'TxC',...
'methodFunction',	@decalibrate,...
'name', 'Decalibrate' ,...
'note', [] ,...
'outputType',	'TxC',...
'plotFunction',	@plot,...
'subType', '',... 
'tag', 'Decalibrate',... 
'type', 'General'...
);

%% Save
save( '/home/pagno/Desktop/MyProg/Method/MethodList.mat' , 'MethodList')