%% Pruning
Parameters = struct;
Parameters(1).name = 'Minimum value';
Parameters(1).value = 1;
Parameters(1).style = 'edit';
Parameters(2).name = 'Maximum value';
Parameters(2).value = 1;
Parameters(2).style = 'edit';
Parameters(3).name = 'Max standard deviation';
Parameters(3).value = 1;
Parameters(3).style = 'edit';

MethodList(1) = NirsMethod(... 
'Parameters', Parameters,...
'description', 'Pruning' ,...
'inputType',  'TxC',...
'methodFunction',	@pruning,...
'name', 'Pruning' ,...
'note', [] ,...
'outputType',	'TxC',...
'plotFunction',	@plot,...
'tag', 'Pruning',... 
'type', 'General'...
);



%% Low Pass
Parameters = struct;
Parameters(1).name = 'Low Pass Cutoff frequency [Hz]';
Parameters(1).value = 1;
Parameters(1).style = 'edit';

MethodList(2) = NirsMethod(... 
'Parameters', Parameters,...
'description', 'Low-pass filter method' ,...
'inputType',  'TxC',...
'methodFunction',	@(dataIn, Parameters)lowpassfilter(dataIn, Parameters),...
'name', 'LowPass Filter' ,...
'note', [] ,...
'outputType',	'TxC',...
'plotFunction',	@plot,...
'subType', 'Spectral',... 
'tag', 'LowPass',... 
'type', 'Filter'...
);


%% High Pass
Parameters = struct;
Parameters(1).name = 'High Pass Cutoff frequency [Hz]';
Parameters(1).value = 1;
Parameters(1).style = 'edit';

MethodList(3) = NirsMethod(... 
'Parameters', Parameters,...
'description', 'High-pass filter method' ,...
'inputType',  'TxC',...
'methodFunction',	@highpassfilter,...
'name', 'HighPass Filter' ,...
'note', [] ,...
'outputType',	'TxC',...
'plotFunction',	@plot,...
'subType', 'Spectral',... 
'tag', 'HighPass',... 
'type', 'Filter'...
);


%% Band Pass
Parameters = struct;
Parameters(1).name = 'Low frequency [Hz]';
Parameters(1).value = 1;
Parameters(1).style = 'edit';
Parameters(2).name = 'High frequency [Hz]';
Parameters(2).value = 2;
Parameters(2).style = 'edit';

MethodList(4) = NirsMethod(... 
'Parameters', Parameters,...
'description', 'Band-pass filter method' ,...
'inputType',  'TxC',...
'methodFunction',	@bandpassfilter,...
'name', 'BandPass Filter' ,...
'note', [] ,...
'outputType',	'TxC',...
'plotFunction',	@plot,...
'subType', 'Spectral',... 
'tag', 'BandPass',... 
'type', 'Filter'...
);


%% Calibrate
Parameters = struct;
Parameters(1).name = 'Calibrate';
Parameters(1).value = '';
Parameters(1).style = 'text';

MethodList(5) = NirsMethod(... 
'Parameters', Parameters,...
'description', 'Calibrate method' ,...
'inputType',  'TxC',...
'methodFunction',	@calibrate,...
'name', 'Calibrate' ,...
'note', [] ,...
'outputType',	'TxC',...
'plotFunction',	@plot,...
'subType', '',... 
'tag', 'Calibrate',... 
'type', 'General'...
);


%% Decalibrate
Parameters = struct;
Parameters(1).name = 'Decalibrate';
Parameters(1).value = '';
Parameters(1).style = 'text';

MethodList(6) = NirsMethod(... 
'Parameters', Parameters,...
'description', 'Decalibrate method' ,...
'inputType',  'TxC',...
'methodFunction',	@decalibrate,...
'name', 'Decalibrate' ,...
'note', [] ,...
'outputType',	'TxC',...
'plotFunction',	@plot,...
'subType', '',... 
'tag', 'Decalibrate',... 
'type', 'General'...
);

%% Block average
Parameters(1).name = 'Conditions';
Parameters(1).value = [];
Parameters(1).style = 'listbox';
Parameters(2).name = 'Start (s)';
Parameters(2).value = -1;
Parameters(2).style = 'edit';
Parameters(3).name = 'Stop (s)';
Parameters(3).value = 1;
Parameters(3).style = 'edit';
Parameters(4).name = 'Detrend';
Parameters(4).value = false;
Parameters(4).style = 'checkbox';

MethodList(7) = NirsMethod(... 
'Parameters', Parameters,...
'description', 'Block average method' ,...
'inputType',  '', ...
'methodFunction', @(dataIn, Parameters)blockaverage(dataIn, Parameters),...
'name', 'Block Average' ,...
'note', [] ,...
'outputType',	'',...
'plotFunction',	@plot,...
'tag', 'Blockaverage',... 
'type', 'General'...
);
%% Save
%save( '/home/pagno/Desktop/MyProg/Method/MethodList.mat' , 'MethodList')
save( 'C:\Users\matteo.caffini\Documents\MATLAB\Gnirs\Method\MethodList.mat' , 'MethodList')