f1 = NirsForward(...
        'atlasId', 'uaujbas', ...
        'probeId', 'sdsa', ...
        'date', datetime, ...
        'node', He.node, ...
        'src', src3, ...
        'det', det3, ...
        'srcDir', srcdir, ...
        'detDir', detdir, ...
        'srcFlux', fluxsrc, ...
        'detFlux', fluxdet, ...
        'note', 'jhsdgfskdjnf');