function PlotHandle = plotsensitivity3d(HeadMesh,sensitivity, varargin)
maxMarkerSize = 10;
Parent = gca;
sensitivityThresHold = -inf;
Atlas = [];
sensitivityColormap =parula(128);
atlasAlpha = [0.2 0.3 0.4];
atlasColor = [0.88235, 0.89804, 0.8;...
    0.65, 0.65, 0.65;...
    1, 1, 1];

for iArgIn = 1 : 2: (nargin - 2)
    switch lower(varargin{iArgIn})
        case 'parent'
            Parent =  varargin{iArgIn + 1};
        case 'maxmarkersize'
            maxMarkerSize =  varargin{iArgIn + 1};
        case 'sensitivitythreshold'
            sensitivityThresHold =  varargin{iArgIn + 1};
        case 'atlas'
            Atlas =  varargin{iArgIn + 1};
        case 'sensitivitycolormap'
            sensitivityColormap =  varargin{iArgIn + 1};
        case 'atlasalpha'
            atlasAlpha =  varargin{iArgIn + 1};
        case 'atlascolor'
            atlasColor =  varargin{iArgIn + 1};
        case 's'
            
        otherwise
            warning(['field ' varargin{iArgIn} 'is not a valid field'])
    end
end


sensitivityMask = sensitivity > sensitivityThresHold;
sensitivity2Plot = sensitivity(sensitivityMask);

minSensitivity = min(sensitivity2Plot);
maxSensitivity = max(sensitivity2Plot);
sensitivityNormalized = (sensitivity2Plot - minSensitivity)./(maxSensitivity - minSensitivity);

colorIdx = floor(sensitivityNormalized*127) + 1;

scatterSize = max(maxMarkerSize.*sensitivityNormalized , 0.01);
scatterColor = sensitivityColormap(colorIdx,:);
PlotHandle.Scatter = scatter3(Parent,...
    HeadMesh.node(sensitivityMask,1),HeadMesh.node(sensitivityMask,2),HeadMesh.node(sensitivityMask,3),...
    scatterSize,...
    scatterColor,...
    'filled'...
    );

tempAxesHold  = Parent.NextPlot;
Parent.NextPlot = 'add';

if ~isempty(Atlas)
    PlotHandle.Scalp = trisurf(...
        Atlas.Scalp.face,...
        Atlas.Scalp.node(:,1),Atlas.Scalp.node(:,2), Atlas.Scalp.node(:,3),...
        ones(size(Atlas.Scalp.node(:,3))),...
        'Parent', Parent,...
        'SpecularStrength', 0, ...
        'EdgeColor','none',...
        'FaceColor',atlasColor(1,:),...
        'FaceAlpha',atlasAlpha(1));
    
    PlotHandle.Gray = trisurf(...
        Atlas.GreyMatter.face,...
        Atlas.GreyMatter.node(:,1),Atlas.GreyMatter.node(:,2), Atlas.GreyMatter.node(:,3),...
        2.*ones(size(Atlas.GreyMatter.node(:,3))),...
        'Parent', Parent,...
        'SpecularStrength', 0, ...
        'EdgeColor','none',...
        'FaceColor',atlasColor(2,:),...
        'FaceAlpha',atlasAlpha(2));
    
    PlotHandle.White = trisurf(...
        Atlas.WhiteMatter.face,...
        Atlas.WhiteMatter.node(:,1),Atlas.WhiteMatter.node(:,2), Atlas.WhiteMatter.node(:,3),...
        3.*ones(size(Atlas.WhiteMatter.node(:,3))),...
        'Parent', Parent,...
        'SpecularStrength', 0, ...
        'EdgeColor','none',...
        'FaceColor',atlasColor(3,:),...
        'FaceAlpha',atlasAlpha(3));
end
Parent.NextPlot = tempAxesHold;
end