function vewertoolbar(viewerC, GHandle, vIdx)
GHandle.Viewer(vIdx).mainToolbar = uitoolbar('Parent', GHandle.Viewer(vIdx).mainFigure);

img1 = rand(16,16,3);
GHandle.Viewer(vIdx).pushtool1 = uipushtool(GHandle.Viewer(vIdx).mainToolbar,...
    'CData', img1, 'Separator', 'on', ...
    'TooltipString', 'Your toggle tool', ...
    'HandleVisibility', 'off');

img2 = 0.5.*ones(16,16,3);
GHandle.Viewer(vIdx).LockMultipleWiewer  = uitoggletool(GHandle.Viewer(vIdx).mainToolbar,...
    'CData', img2, 'Separator', 'on', ...
    'TooltipString', 'Your toggle tool', ...
    'ClickedCallback',@(handle,evnt)lockmultiplewiewer_callback(handle, evnt, GHandle),...
    'HandleVisibility', 'off');
img3 = rand(16,16,3);
GHandle.Viewer(vIdx).toggletool2 = uitoggletool(GHandle.Viewer(vIdx).mainToolbar,...
    'CData', img3, 'Separator', 'off', ...
    'TooltipString', 'Your toggle tool', ...
    'HandleVisibility', 'off');
img4 = rand(16,16,3);
GHandle.Viewer(vIdx).toggletool3 = uitoggletool(GHandle.Viewer(vIdx).mainToolbar,...
    'CData', img4, 'Separator', 'off', ...
    'TooltipString', 'Your toggle tool', ...
    'HandleVisibility', 'off');
end

function lockmultiplewiewer_callback(handle, ~, GHandle)
state = handle.State;
for idx = GHandle.Temp.vIdxList'
    GHandle.Viewer(idx).LockMultipleWiewer.State = state;
end
end