function viewerpanel(viewerC, GHandle, vIdx)

% Arrange the main interface
GHandle.Viewer(vIdx).mainLayout = uix.VBoxFlex(...
    'Parent', GHandle.Viewer(vIdx).mainFigure,...
    'Spacing', 8 );

% + Create the panels
GHandle.Viewer(vIdx).PlotInfoPanel = uix.HBoxFlex(...
     'Parent', GHandle.Viewer(vIdx).mainLayout, ...
     'Spacing', 8);

GHandle.Viewer(vIdx).ViewPanel = uix.HBoxFlex(...
     'Parent', GHandle.Viewer(vIdx).mainLayout, ...
     'Spacing', 3 );

GHandle.Viewer(vIdx).PlotPanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).PlotInfoPanel, ...
    'Title', 'Plot', ...
    'HelpFcn', @onDemoHelp );
GHandle.Viewer(vIdx).InfoPanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).PlotInfoPanel, ...
    'Title', 'Info', ...
    'HelpFcn', {@onDemoHelp, GHandle} );

GHandle.Viewer(vIdx).VideoPanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).ViewPanel, ...
    'Title', 'Video', ...
    'HelpFcn', @onDemoHelp );
GHandle.Viewer(vIdx).PreferencePanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).ViewPanel, ...
    'Title', 'Preferences', ...
    'HelpFcn', @onDemoHelp );
GHandle.Viewer(vIdx).ProbePanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).ViewPanel, ...
    'Title', 'Probe', ...
    'HelpFcn', @onDemoHelp );
GHandle.Viewer(vIdx).TrackPanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).ViewPanel, ...
    'Title', 'Traks', ...
    'HelpFcn', @onDemoHelp );

% preference Vbox
GHandle.Viewer(vIdx).PreferencePanel.VPanel = uix.VBox('Parent', GHandle.Viewer(vIdx).PreferencePanel.Panel);
    
% probe axes
GHandle.Viewer(vIdx).probePanel.probeAxes = axes('Parent', GHandle.Viewer(vIdx).ProbePanel.Panel,...
    'Position',  [0.05 0.05 0.9 0.9], ...
    'Units', 'normalized', ...
    'Color', viewerC.backgroundColor, ...
    'XColor', viewerC.foregroundColor, ...
    'YColor', viewerC.foregroundColor, ...
    'Xgrid', 'on', ...
    'Ygrid', 'on', ...
    'GridColor', viewerC.foregroundColor, ...
    'NextPlot', 'add',...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', viewerC.defaultFontName, ...
    'Visible', 'off', ...
    'Title', 'Probe plot');

% track tab
GHandle.Viewer(vIdx).TrackPanel.TabGroup = uitabgroup('Parent', GHandle.Viewer(vIdx).TrackPanel.Panel, ...
    'Position',[0 0 1 0.97]);
GHandle.Viewer(vIdx).TrackPanel.ChannelTab = uitab('Parent',GHandle.Viewer(vIdx).TrackPanel.TabGroup, ...
    'Title', 'Channels', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.textForegroundColor);
GHandle.Viewer(vIdx).TrackPanel.EventTab = uitab('Parent', GHandle.Viewer(vIdx).TrackPanel.TabGroup, ...
    'Title', 'Events', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.textForegroundColor);
end
function onDemoHelp(a,b,c)
disp('ciao')
end
