function  viewertime(viewerC, GHandle, vIdx)

GHandle.Viewer(vIdx).PlotPanel.Time.MainAxes = axes('parent', GHandle.Viewer(vIdx).PlotPanel.TimeTab,...
    'Position', [0.07 0.22 0.88 0.66], ...
    'Units', 'normalized', ...
    'Color', viewerC.backgroundColor, ...
    'XColor', viewerC.foregroundColor, ...
    'YColor', viewerC.foregroundColor, ...
    'Xgrid', 'on', ...
    'Ygrid', 'on', ...
    'GridColor', viewerC.foregroundColor, ...
    'NextPlot', 'add',...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', viewerC.defaultFontName, ...
    'Visible', 'on', ...
    'Title', 'Main plots');

GHandle.Viewer(vIdx).PlotPanel.Time.SupportAxes = axes('parent', GHandle.Viewer(vIdx).PlotPanel.TimeTab,...
    'Position', [0.07 0.22 0.88 0.66], ...
    'Units', 'normalized', ...
    'HitTest', 'off',...
    'Color', 'none', ...
    'XColor', viewerC.foregroundColor, ...
    'YColor', viewerC.foregroundColor, ...
    'Xgrid', 'off', ...
    'Ygrid', 'off', ...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'NextPlot', 'add',...
    'GridColor', viewerC.foregroundColor, ...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', viewerC.defaultFontName, ...
    'Visible', 'on', ...
    'Title', 'Main plots');

GHandle.Viewer(vIdx).PlotPanel.Time.SmallAxes = axes('parent', GHandle.Viewer(vIdx).PlotPanel.TimeTab,...
    'Units', 'normalized', ...
    'Position', [0.1 0.04 0.8 0.07], ...
    'Color', viewerC.backgroundColor, ...
    'Color', viewerC.backgroundColor, ...
    'XColor', viewerC.foregroundColor, ...
    'YColor', viewerC.foregroundColor, ...
    'NextPlot', 'add',...
    'GridColor', viewerC.foregroundColor, ...
    'ButtonDownFcn', {@move_time_window, GHandle, vIdx},...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', viewerC.defaultFontName, ...
    'Visible', 'on', ...
    'Box', 'on', ...
    'XLimMode', 'auto', ...
    'YLimMode', 'auto', ...
    'XGrid', 'off', ...
    'YGrid', 'off');
GHandle.Viewer(vIdx).PlotPanel.Time.SmallAxes.XAxis.Visible = 'on';
GHandle.Viewer(vIdx).PlotPanel.Time.SmallAxes.YAxis.Visible = 'on';

GHandle.Viewer(vIdx).PlotPanel.Time.XEditMin = uicontrol('Parent', GHandle.Viewer(vIdx).PlotPanel.TimeTab, ...
    'Style', 'edit', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.06 0.04 0.05], ...
    'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Tag','min',...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
    'String', 'min');

GHandle.Viewer(vIdx).PlotPanel.Time.XEditMax = uicontrol('Parent', GHandle.Viewer(vIdx).PlotPanel.TimeTab, ...
    'Style', 'edit', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.91 0.06 0.04 0.05], ...
    'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Tag','max',...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
    'String', 'max');

GHandle.Viewer(vIdx).PlotPanel.Time.YEditMin = uicontrol('Parent', GHandle.Viewer(vIdx).PlotPanel.TimeTab, ...
    'Style', 'edit', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.01 0.20 0.04 0.05], ...
    'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Visible','off',...
    'String', 'min',...
    'Tag','min',...
    'Callback', {@editY_callback, GHandle, vIdx});

GHandle.Viewer(vIdx).PlotPanel.Time.YEditMax = uicontrol('Parent', GHandle.Viewer(vIdx).PlotPanel.TimeTab, ...
    'Style', 'edit', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.01 0.85 0.04 0.05], ...
    'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Visible','off',...
    'String', 'max',...
    'Tag','max',...
    'Callback', {@editY_callback, GHandle, vIdx});

GHandle.Viewer(vIdx).PlotPanel.Time.ButtonFirst = uicontrol('Parent', GHandle.Viewer(vIdx).PlotPanel.TimeTab, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.03 0.03 0.02 0.08], ...
    'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
    'Tag','F',...
    'String', 'F');
GHandle.Viewer(vIdx).PlotPanel.Time.ButtonBackwardS = uicontrol('Parent', GHandle.Viewer(vIdx).PlotPanel.TimeTab, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.03 0.02 0.03], ...
    'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
    'Tag','<<',...
    'String', '<<');
GHandle.Viewer(vIdx).PlotPanel.Time.ButtonBackwardL = uicontrol('Parent', GHandle.Viewer(vIdx).PlotPanel.TimeTab, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.07 0.03 0.02 0.03], ...
    'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
    'Tag','<',...
    'String', '<');
GHandle.Viewer(vIdx).PlotPanel.Time.ButtonLast = uicontrol('Parent', GHandle.Viewer(vIdx).PlotPanel.TimeTab, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.95 0.03 0.02 0.08], ...
    'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
    'Tag','L',...
    'String', 'L');
GHandle.Viewer(vIdx).PlotPanel.Time.ButtonForwardL = uicontrol('Parent', GHandle.Viewer(vIdx).PlotPanel.TimeTab, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.93 0.03 0.02 0.03], ...
    'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
    'Tag','>>',...
    'String', '>>');
GHandle.Viewer(vIdx).PlotPanel.Time.ButtonForwardS = uicontrol('Parent', GHandle.Viewer(vIdx).PlotPanel.TimeTab, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.91 0.03 0.02 0.03], ...
    'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
    'Tag','>',...
    'String', '>');

end

function editY_callback(handle, ~, GHandle, vIdx)
mask = contains({'min', 'max'}, handle.Tag);
GHandle.Viewer(vIdx).PlotPanel.Time.MainAxes.YLim(mask) = str2double(handle.String);
GHandle.Viewer(vIdx).WatchList.edvLine = GHandle.Viewer(vIdx).WatchList.edvLine; % replace with reset/redraw
end

function move_time_window(~, eventData, GHandle, vIdx)
small_step = 1;
big_step = 10;
switch eventData.EventName
    case 'Action'
        switch eventData.Source.Tag
            case '<'
                xmin = GHandle.Viewer(vIdx).WatchList.timeLim(1) - small_step;
                xmax = GHandle.Viewer(vIdx).WatchList.timeLim(2) - small_step;
                
            case '>'
                xmin = GHandle.Viewer(vIdx).WatchList.timeLim(1) + small_step;
                xmax = GHandle.Viewer(vIdx).WatchList.timeLim(2) + small_step;
                
            case '<<'
                xmin = GHandle.Viewer(vIdx).WatchList.timeLim(1) - big_step;
                xmax = GHandle.Viewer(vIdx).WatchList.timeLim(2) - big_step;
                
            case '>>'
                xmin = GHandle.Viewer(vIdx).WatchList.timeLim(1) + big_step;
                xmax = GHandle.Viewer(vIdx).WatchList.timeLim(2) + big_step;
                
            case 'F'
                xmin = GHandle.Viewer(vIdx).Data.Time(1);
                xmax = GHandle.Viewer(vIdx).WatchList.timeLim(2);
                
            case 'L'
                xmin = GHandle.Viewer(vIdx).WatchList.timeLim(1);
                xmax = GHandle.Viewer(vIdx).Data.Time(end);
                
            case 'max'
                xmin = GHandle.Viewer(vIdx).WatchList.timeLim(1);
                xmax = str2double(eventData.Source.String);
                if xmax > GHandle.Viewer(vIdx).WatchList.timeLim(1)
                    GHandle.Viewer(vIdx).WatchList.timeLim(2) = xmax;
                else
                    msgbox('Invalid value - max must be larger than min')
                end
                
            case 'min'
                xmax = GHandle.Viewer(vIdx).WatchList.timeLim(2);
                xmin = str2double(eventData.Source.String);
                if xmin < GHandle.Viewer(vIdx).WatchList.timeLim(2)
                    GHandle.Viewer(vIdx).WatchList.timeLim(1) = xmin;
                else
                    msgbox('Invalid value - min must be smaller than max')
                end
        end
        
    case 'Hit'
        xrange = GHandle.Viewer(vIdx).WatchList.timeLim(2) - GHandle.Viewer(vIdx).WatchList.timeLim(1);
        xmin = eventData.IntersectionPoint(1) - xrange/2;
        xmax = xmin + xrange;
end
if strcmp(GHandle.Viewer(vIdx).LockMultipleWiewer.State,'on')
    for vIdx = GHandle.Temp.vIdxList'
        GHandle.Viewer(vIdx).WatchList.timeLim = [xmin , xmax];
    end
else
    GHandle.Viewer(vIdx).WatchList.timeLim = [xmin , xmax];
end
end
