function viewertrackpref(viewerC, GHandle, vIdx)

GHandle.Viewer(vIdx).PreferencePanel.SortingMethods = uiw.widget.Popup(...
    'Parent',  GHandle.Viewer(vIdx).PreferencePanel.VPanel, ...
    'Items',viewerC.sortingMethod,...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'Label','Sorting:', ...
    'LabelLocation','left',...
    'Callback',@(h,e)sortingmethod_callback(h,e, GHandle, vIdx)...
    );

GHandle.Viewer(vIdx).PreferencePanel.YAutoscale = uicontrol('Parent', GHandle.Viewer(vIdx).PreferencePanel.VPanel, ...
    'Style', 'checkbox', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.foregroundColor, ...
    'Units', 'normalized', ...
    'FontWeight', 'bold', ...
    'Value',true,...
    'Callback', {@yautoscale_callback, GHandle, vIdx},...
    'FontSize', 8, ...
    'FontAngle', 'italic', ...
    'HorizontalAlignment', 'right', ...
    'String', 'Y axes Autoscale');
end

function yautoscale_callback(handle, ~, GHandle, vIdx)
if handle.Value
    GHandle.Viewer(vIdx).PlotPanel.Time.YEditMax.Visible = 'off';
    GHandle.Viewer(vIdx).PlotPanel.Time.YEditMin.Visible = 'off';
    GHandle.Viewer(vIdx).WatchList.edvLine = GHandle.Viewer(vIdx).WatchList.edvLine;
else
    GHandle.Viewer(vIdx).PlotPanel.Time.YEditMax.Visible = 'on';
    GHandle.Viewer(vIdx).PlotPanel.Time.YEditMin.Visible = 'on';
    GHandle.Viewer(vIdx).PlotPanel.Time.YEditMax.String = 'max';
    GHandle.Viewer(vIdx).PlotPanel.Time.YEditMin.String = 'min';
end
end

function sortingmethod_callback(~, Event, GHandle, vIdx)
sortingmethod = Event.Source.String{Event.Source.Value};
colors = sorting_colors((size(GHandle.Viewer(vIdx).Data,2)-1), sortingmethod);
GHandle.Viewer(vIdx).WatchList.colorLine = colors;
GHandle.Viewer(vIdx).WatchList.edvLine = ones(size(GHandle.Viewer(vIdx).WatchList.edvLine));
end