function viewerpanel(viewerC, GHandle, vIdx)

defaultHSplit = -[70; 30];
defaultVTopSplit = -[80; 20];
defaultVBotSplit = -[25; 25; 25; 25];


% Arrange the main interface
GHandle.Viewer(vIdx).mainLayout = uix.VBoxFlex(...
    'Parent', GHandle.Viewer(vIdx).mainFigure,...
    'Spacing', 8 );

% + Create the panels
GHandle.Viewer(vIdx).PlotInfoLayout = uix.HBoxFlex(...
     'Parent', GHandle.Viewer(vIdx).mainLayout, ...
     'Spacing', 8);

GHandle.Viewer(vIdx).ViewLayout = uix.HBoxFlex(...
     'Parent', GHandle.Viewer(vIdx).mainLayout, ...
     'Spacing', 3 );

GHandle.Viewer(vIdx).PlotPanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).PlotInfoLayout, ...
    'Title', 'Plot', ...
    'HelpFcn', @onDemoHelp );
GHandle.Viewer(vIdx).InfoPanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).PlotInfoLayout, ...
    'Title', 'Info', ...
    'HelpFcn', {@onDemoHelp, GHandle} );

GHandle.Viewer(vIdx).VideoPanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).ViewLayout, ...
    'Title', 'Video', ...
    'HelpFcn', @onDemoHelp );
GHandle.Viewer(vIdx).PreferencePanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).ViewLayout, ...
    'Title', 'Preferences', ...
    'HelpFcn', @onDemoHelp );
GHandle.Viewer(vIdx).ProbePanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).ViewLayout, ...
    'Title', 'Probe', ...
    'HelpFcn', @onDemoHelp );
GHandle.Viewer(vIdx).TrackPanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).ViewLayout, ...
    'Title', 'Traks', ...
    'HelpFcn', @onDemoHelp );

% set split ratio

GHandle.Viewer(vIdx).mainLayout.Heights = defaultHSplit;
GHandle.Viewer(vIdx).PlotInfoLayout.Widths = defaultVTopSplit;
GHandle.Viewer(vIdx).ViewLayout.Widths = defaultVBotSplit;

%plot tabgroup
GHandle.Viewer(vIdx).PlotPanel.TabGroup = uitabgroup(GHandle.Viewer(vIdx).PlotPanel.Panel);
GHandle.Viewer(vIdx).PlotPanel.TimeTab = uitab('Parent', GHandle.Viewer(vIdx).PlotPanel.TabGroup, ...
    'Title', 'Time', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.textForegroundColor);
GHandle.Viewer(vIdx).PlotPanel.FrequencyTab = uitab('Parent', GHandle.Viewer(vIdx).PlotPanel.TabGroup, ...
    'Title', 'Spectrum', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.textForegroundColor);
GHandle.Viewer(vIdx).PlotPanel.TimeFrequencyTab = uitab('Parent', GHandle.Viewer(vIdx).PlotPanel.TabGroup, ...
    'Title', 'Time-Frequency', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.textForegroundColor);


% preference Vbox
GHandle.Viewer(vIdx).PreferencePanel.VPanel = uix.VBox('Parent', GHandle.Viewer(vIdx).PreferencePanel.Panel);
    
% probe axes
GHandle.Viewer(vIdx).ProbePanel.ProbeAxes = axes('Parent', GHandle.Viewer(vIdx).ProbePanel.Panel,...
    'Position',  [0.05 0.05 0.9 0.9], ...
    'Units', 'normalized', ...
    'Color', viewerC.backgroundColor, ...
    'XColor', viewerC.foregroundColor, ...
    'YColor', viewerC.foregroundColor, ...
    'Xgrid', 'on', ...
    'Ygrid', 'on', ...
    'GridColor', viewerC.foregroundColor, ...
    'NextPlot', 'add',...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', viewerC.defaultFontName, ...
    'Visible', 'off', ...
    'Title', 'Probe plot');

% track tab
GHandle.Viewer(vIdx).TrackPanel.TabGroup = uitabgroup('Parent', GHandle.Viewer(vIdx).TrackPanel.Panel, ...
    'Position',[0 0 1 0.97]);
GHandle.Viewer(vIdx).TrackPanel.ChannelTab = uitab('Parent',GHandle.Viewer(vIdx).TrackPanel.TabGroup, ...
    'Title', 'Channels', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.textForegroundColor);
GHandle.Viewer(vIdx).TrackPanel.EventTab = uitab('Parent', GHandle.Viewer(vIdx).TrackPanel.TabGroup, ...
    'Title', 'Events', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.textForegroundColor);
end
function onDemoHelp(a,b,c)
disp('ciao')
end
