function viewerpanel(viewerC, GHandle, vIdx)

trackTableColumnName = { 'S', 'D','Wavelength', 'SD distance (mm)','Name'};
trackTableColumnFormat = {'char' 'char', 'numeric', 'numeric', 'char'};

eventTableColumnName = {'Label', 'Code', 'Start (s)', 'Duration (s)'};
eventTableColumnFormat = {'char' 'char', 'numeric', 'numeric'};

%% Main splits
GHandle.Viewer(vIdx).mainLayout = uix.VBoxFlex(...
    'Parent', GHandle.Viewer(vIdx).mainFigure,...
    'Spacing', 3);
GHandle.Viewer(vIdx).PlotInfoLayout = uix.HBoxFlex(...
    'Parent', GHandle.Viewer(vIdx).mainLayout, ...
    'Spacing', 3);
GHandle.Viewer(vIdx).ViewLayout = uix.HBoxFlex(...
    'Parent', GHandle.Viewer(vIdx).mainLayout, ...
    'Spacing', 3);


%% Panels
GHandle.Viewer(vIdx).PlotPanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).PlotInfoLayout, ...
    'Title', 'Plot', ...
    'HelpFcn', @onDemoHelp);
GHandle.Viewer(vIdx).InfoPanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).PlotInfoLayout, ...
    'Title', 'Info', ...
    'HelpFcn', {@onDemoHelp, GHandle});

GHandle.Viewer(vIdx).VideoPanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).ViewLayout, ...
    'Title', 'Video', ...
    'HelpFcn', @onDemoHelp, ...
    'DockFcn', {@video_dock, GHandle, vIdx, viewerC});
GHandle.Viewer(vIdx).PreferencePanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).ViewLayout, ...
    'Title', 'Preferences', ...
    'HelpFcn', @onDemoHelp);
GHandle.Viewer(vIdx).ProbePanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).ViewLayout, ...
    'Title', 'Probe', ...
    'HelpFcn', @onDemoHelp, ...
    'DockFcn', {@probe_dock, GHandle, vIdx, viewerC});
GHandle.Viewer(vIdx).DataPanel.Panel = uix.BoxPanel( ...
    'Parent', GHandle.Viewer(vIdx).ViewLayout, ...
    'Title', 'Data', ...
    'HelpFcn', @onDemoHelp, ...
    'DockFcn', {@data_dock, GHandle, vIdx, viewerC});

%% Plot
GHandle.Viewer(vIdx).PlotPanel.TabGroup = uitabgroup(GHandle.Viewer(vIdx).PlotPanel.Panel);
GHandle.Viewer(vIdx).PlotPanel.TimeTab = uitab('Parent', GHandle.Viewer(vIdx).PlotPanel.TabGroup, ...
    'Title', 'Time', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.textForegroundColor);
GHandle.Viewer(vIdx).PlotPanel.FrequencyTab = uitab('Parent', GHandle.Viewer(vIdx).PlotPanel.TabGroup, ...
    'Title', 'Spectrum', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.textForegroundColor);
GHandle.Viewer(vIdx).PlotPanel.TimeFrequencyTab = uitab('Parent', GHandle.Viewer(vIdx).PlotPanel.TabGroup, ...
    'Title', 'Time-Frequency', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.textForegroundColor);

%% Info
GHandle.Viewer(vIdx).InfoPanel.VPanel = uix.VBox(...
    'Parent', GHandle.Viewer(vIdx).InfoPanel.Panel,...
    'BackgroundColor', viewerC.backgroundColor...
    );

%% Video

%% Preferences
GHandle.Viewer(vIdx).PreferencePanel.VPanel = uix.VBox(...
    'Parent', GHandle.Viewer(vIdx).PreferencePanel.Panel,...
    'BackgroundColor', viewerC.backgroundColor...
    );

%% Probe
GHandle.Viewer(vIdx).ProbePanel.ProbeAxes = axes('Parent', GHandle.Viewer(vIdx).ProbePanel.Panel,...
    'Position',  [0.05 0.05 0.9 0.9], ...
    'Units', 'normalized', ...
    'Color', viewerC.backgroundColor, ...
    'XColor', viewerC.foregroundColor, ...
    'YColor', viewerC.foregroundColor, ...
    'Xgrid', 'on', ...
    'Ygrid', 'on', ...
    'GridColor', viewerC.foregroundColor, ...
    'NextPlot', 'add',...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', viewerC.defaultFontName, ...
    'Visible', 'off', ...
    'Title', 'Probe plot');

%% Tracks
GHandle.Viewer(vIdx).DataPanel.TabGroup = uitabgroup('Parent', GHandle.Viewer(vIdx).DataPanel.Panel, ...
    'Position',[0 0 1 0.97]);
GHandle.Viewer(vIdx).DataPanel.TrackTab = uitab('Parent',GHandle.Viewer(vIdx).DataPanel.TabGroup, ...
    'Title', 'Tracks', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.textForegroundColor);
GHandle.Viewer(vIdx).DataPanel.EventTab = uitab('Parent', GHandle.Viewer(vIdx).DataPanel.TabGroup, ...
    'Title', 'Events', ...
    'BackgroundColor', viewerC.backgroundColor, ...
    'ForegroundColor', viewerC.textForegroundColor);

GHandle.Viewer(vIdx).DataPanel.TrackTable = uiw.widget.Table(...
    'Parent', GHandle.Viewer(vIdx).DataPanel.TrackTab, ...
    'Units', 'normalize', ...
    'ColumnName', trackTableColumnName, ...
    'CellSelectionCallback', {@channel_table_selection_callback, GHandle, vIdx},...
    'ColumnResizePolicy', 'all', ...
    'ColumnFormat',trackTableColumnFormat, ...
    'Position',  [0 0 1 1],...
    'Sortable', true,...
    'LabelVisible','off');

GHandle.Viewer(vIdx).DataPanel.EventTable = uiw.widget.Table(...
    'Parent',  GHandle.Viewer(vIdx).DataPanel.EventTab, ...
    'Units', 'normalize', ...
    'ColumnName', eventTableColumnName, ...
    'ColumnEditable',[false false false false], ...
    'CellSelectionCallback', {@event_table_selection_callback, GHandle, vIdx},...
    'ColumnResizePolicy', 'all', ...
    'ColumnFormat', eventTableColumnFormat, ...
    'Sortable', true,...
    'Position',  [0 0 1 1],...
    'LabelVisible','off');
end

function channel_table_selection_callback(a,b,c,d)
disp('sciao')
end

function event_table_selection_callback(a,b,c,d)
end

function onDemoHelp(a,b,c)
disp('ciao')
end

function video_dock(~, ~, GHandle, vIdx, viewerC)
if GHandle.Viewer(vIdx).VideoPanel.Panel.Docked
    GHandle.Viewer(vIdx).Undocked.Video = figure(...
        'Name', 'Video', ...
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'Toolbar', 'none', ...
        'CloseRequestFcn', {@video_dock, GHandle, vIdx, viewerC});
    set(GHandle.Viewer(vIdx).VideoPanel.Panel,...
        'Parent', GHandle.Viewer(vIdx).Undocked.Video, ...
        'Units', 'Normalized', ...
        'Position', [0 0 1 1]);
else
    GHandle.Viewer(vIdx).Undocked.Video = get(GHandle.Viewer(vIdx).VideoPanel.Panel, 'Parent');
    set(GHandle.Viewer(vIdx).VideoPanel.Panel,...
        'Parent', GHandle.Viewer(vIdx).ViewLayout);
    delete(GHandle.Viewer(vIdx).Undocked.Video);
    uistack(GHandle.Viewer(vIdx).VideoPanel.Panel,'down',2);
    GHandle.Viewer(vIdx).mainLayout.Heights = viewerC.defaultHSplit;
    GHandle.Viewer(vIdx).PlotInfoLayout.Widths = viewerC.defaultVTopSplit;
    GHandle.Viewer(vIdx).ViewLayout.Widths = viewerC.defaultVBotSplit;
end
GHandle.Viewer(vIdx).VideoPanel.Panel.Docked = ~GHandle.Viewer(vIdx).VideoPanel.Panel.Docked;
end

function probe_dock(~, ~, GHandle, vIdx, viewerC)
if GHandle.Viewer(vIdx).ProbePanel.Panel.Docked
    GHandle.Viewer(vIdx).Undocked.Probe = figure(...
        'Name', 'Probe', ...
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'Toolbar', 'none', ...
        'CloseRequestFcn', {@probe_dock, GHandle, vIdx, viewerC});
    set(GHandle.Viewer(vIdx).ProbePanel.Panel,...
        'Parent', GHandle.Viewer(vIdx).Undocked.Probe, ...
        'Units', 'Normalized', ...
        'Position', [0 0 1 1]);
else
    GHandle.Viewer(vIdx).Undocked.Probe = get(GHandle.Viewer(vIdx).ProbePanel.Panel, 'Parent');
    set(GHandle.Viewer(vIdx).ProbePanel.Panel,...
        'Parent', GHandle.Viewer(vIdx).ViewLayout);
    delete(GHandle.Viewer(vIdx).Undocked.Probe);
    uistack(GHandle.Viewer(vIdx).ProbePanel.Panel,'down',1);
    GHandle.Viewer(vIdx).mainLayout.Heights = viewerC.defaultHSplit;
    GHandle.Viewer(vIdx).PlotInfoLayout.Widths = viewerC.defaultVTopSplit;
    GHandle.Viewer(vIdx).ViewLayout.Widths = viewerC.defaultVBotSplit;
end
GHandle.Viewer(vIdx).ProbePanel.Panel.Docked = ~GHandle.Viewer(vIdx).ProbePanel.Panel.Docked;
end

function data_dock(~, ~, GHandle, vIdx, viewerC)
if GHandle.Viewer(vIdx).DataPanel.Panel.Docked
    GHandle.Viewer(vIdx).Undocked.Data = figure(...
        'Name', 'Data', ...
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'Toolbar', 'none', ...
        'CloseRequestFcn', {@data_dock, GHandle, vIdx, viewerC});
    set(GHandle.Viewer(vIdx).DataPanel.Panel,...
        'Parent', GHandle.Viewer(vIdx).Undocked.Data, ...
        'Units', 'Normalized', ...
        'Position', [0 0 1 1]);
else
    GHandle.Viewer(vIdx).Undocked.Data = get(GHandle.Viewer(vIdx).DataPanel.Panel, 'Parent');
    set(GHandle.Viewer(vIdx).DataPanel.Panel,...
        'Parent', GHandle.Viewer(vIdx).ViewLayout);
    delete(GHandle.Viewer(vIdx).Undocked.Data);
    GHandle.Viewer(vIdx).mainLayout.Heights = viewerC.defaultHSplit;
    GHandle.Viewer(vIdx).PlotInfoLayout.Widths = viewerC.defaultVTopSplit;
    GHandle.Viewer(vIdx).ViewLayout.Widths = viewerC.defaultVBotSplit;
end
GHandle.Viewer(vIdx).DataPanel.Panel.Docked = ~GHandle.Viewer(vIdx).DataPanel.Panel.Docked;
end
