function popatlasplot(obj)

obj.AtlasPlot.Scalp = trisurf(...
     'Parent',obj.MainPlot.Axes,...
    obj.Atlas.Scalp.face, ...
    obj.Atlas.Scalp.node(:,1), obj.Atlas.Scalp.node(:,2), obj.Atlas.Scalp.node(:,3), ...
    ones(size(obj.Atlas.Scalp.node(:,3))), ...
    'SpecularStrength', 0, ...
    'EdgeColor', 'none', ...
    'FaceColor', [0.7 0.7 0.7], ...
    'FaceAlpha' ,0.3);

obj.AtlasPlot.GreyMatter = trisurf(...
    'Parent',obj.MainPlot.Axes,...
    obj.Atlas.GreyMatter.face, ...
    obj.Atlas.GreyMatter.node(:,1), obj.Atlas.GreyMatter.node(:,2), obj.Atlas.GreyMatter.node(:,3), ...
    ones(size(obj.Atlas.GreyMatter.node(:,3))), ...
    'SpecularStrength', 0, ...
    'EdgeColor', 'none', ...
    'FaceColor', [0.7 0.2 0], ...
    'FaceAlpha', 0.3);

obj.AtlasPlot.WhiteMatter = trisurf(...
    'Parent',obj.MainPlot.Axes,...
    obj.Atlas.WhiteMatter.face, ...
    obj.Atlas.WhiteMatter.node(:,1), obj.Atlas.WhiteMatter.node(:,2), obj.Atlas.WhiteMatter.node(:,3), ...
    ones(size(obj.Atlas.WhiteMatter.node(:,3))), ...
    'SpecularStrength', 0, ...
    'EdgeColor', 'none', ...
    'FaceColor', [0 0.2 0.2], ...
    'FaceAlpha', 0.3);

end
