function populateprobeplot(obj)

obj.ProbePlot.SourceOptode = plot3(...
    [obj.Probe.source.position(:,1) obj.Probe.source.position(:,1)]', ...
    [obj.Probe.source.position(:,2) obj.Probe.source.position(:,2)]', ...
    [obj.Probe.source.position(:,3) obj.Probe.source.position(:,3)]', ...
    'Marker', '.', ...
    'MarkerSize', 20, ...
    'Color', [0.2 0 0], ...
    'LineStyle', 'none', ...
    'Parent', obj.MainPlot.Axes);

obj.ProbePlot.DetectorOptode = plot3(...
    [obj.Probe.detector.position(:,1) obj.Probe.detector.position(:,1)]', ...
    [obj.Probe.detector.position(:,2) obj.Probe.detector.position(:,2)]', ...
    [obj.Probe.detector.position(:,3) obj.Probe.detector.position(:,3)]', ...
    'Marker', '.', ...
    'MarkerSize', 20, ...
    'Color', [0 0 0.2], ...
    'LineStyle', 'none', ...
    'Parent', obj.MainPlot.Axes);


end
