function populateprobesetting(obj)
obj.DownSamplingLabel = uicontrol('Parent', obj.SettingPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.95 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Downsampling Factor [> 1]');
obj.DownSampling = uicontrol('Parent', obj.SettingPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.91 0.8 0.04],...
    'String', '10', ...
    'Visible', 'on', ...
    'Callback', @(h,e)ViewForward.photonrefresh(h,e,obj));

obj.MaxMarkerSizeLabel = uicontrol('Parent', obj.SettingPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.85 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Max Marker Size');
obj.MaxMarkerSize = uicontrol('Parent', obj.SettingPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.81 0.8 0.04],...
    'String', '10', ...
    'Visible', 'on', ...
    'Callback', @(h,e)ViewForward.photonrefresh(h,e,obj));

obj.AngleLabel = uicontrol('Parent', obj.SettingPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.75 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Plane cut angles');
obj.Angle1 = uicontrol('Parent', obj.SettingPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.71 0.35 0.04],...
    'String', '0', ...
    'Visible', 'on', ...
    'Callback', @(h,e)ViewForward.photonrefresh(h,e,obj));
obj.Angle2 = uicontrol('Parent', obj.SettingPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.55 0.71 0.35 0.04],...
    'String', '0', ...
    'Visible', 'on', ...
    'Callback', @(h,e)ViewForward.photonrefresh(h,e,obj));

obj.SensitivityThresholdLabel = uicontrol('Parent', obj.SettingPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.65 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Sensitivity Threshold');
obj.SensitivityThreshold = uicontrol('Parent', obj.SettingPanel, ...
    'Style', 'edit', ...
    'Units', 'normalized',...
    'Position', [0.1 0.61 0.8 0.04],...
    'String', '-6', ...
    'Visible', 'on', ...
    'Callback', @(h,e)ViewForward.photonrefresh(h,e,obj));

obj.ColormapLabel = uicontrol('Parent', obj.SettingPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.55 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Colormap');
obj.Colormap = uicontrol('Parent', obj.SettingPanel, ...
    'Style', 'popup', ...
    'Units', 'normalized',...
    'Position', [0.1 0.51 0.8 0.04],...
    'String', {'parula'; 'hsv'; 'hot'; 'gray'; 'bone'; ...
    'copper';'pink'; 'white'; 'flag';  'lines'; ...
    'colorcube';'jet'; 'prism'; 'cool'; ...
    'autumn'; 'spring'; 'winter';'summer'}, ...
    'Visible', 'on', ...
    'Callback', @(h,e)ViewForward.photonrefresh(h,e,obj));

obj.ScaleLabel = uicontrol('Parent', obj.SettingPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0.1 0.45 0.8 0.03],...
    'HorizontalAlignment', 'left', ...
    'Visible', 'on', ...
    'String', 'Scale');
obj.Scale = uicontrol('Parent', obj.SettingPanel, ...
    'Style', 'popup', ...
    'Units', 'normalized',...
    'Position', [0.1 0.41 0.8 0.04],...
    'String', {'linear'; 'log10'; 'log'; 'exp'; 'sqrt'; 'cube root'}, ...
    'Value', 2, ...
    'Visible', 'on', ...
    'Callback', @(h,e)ViewForward.photonrefresh(h,e,obj));
end