classdef ViewForward < handle & matlab.mixin.SetGet
    
    properties (Transient)
        Position
        Forward
        Probe
        Atlas
    end
    
    properties
        GHandle
        
        MainFigure
        InfoPanel
        PlotPanel
        SettingPanel
        ResizeButton1
        ResizeButton2
        
        DataTypeLabel
        DataType
        SrcListLabel
        SrcList
        DetListLabel
        DetList
        ChannelListLabel
        ChannelList
        OptodeCheckbox
        ArrowCheckbox
        PhotonCheckbox
        
        ProbeAxes
        Scalp
        GreyMatter
        WhiteMatter
        Light1
        Light2
        SourceOptode
        DetectorOptode
        Sensitivity
        
        DownSamplingLabel
        DownSampling
        MaxMarkerSizeLabel
        MaxMarkerSize
        AngleLabel
        Angle1
        Angle2
        SensitivityThresholdLabel
        SensitivityThreshold
        ColormapLabel
        Colormap
        ScaleLabel
        Scale
        
        Position_
    end
    
    methods
        function Value = get.Position(obj)
            Value = obj.Position_;
        end
        function set.Position(obj,Pos)
            obj.Position_ = Pos;
        end
        %% Constructor
        function  obj = ViewForward(GHandle, Forward)
            obj.GHandle = GHandle;
            
            obj.Probe = GHandle.CurrentDataSet.Probe;
            obj.Atlas = GHandle.CurrentDataSet.Atlas;
            
            obj.Forward = Forward;
            
            obj.MainFigure = figure('Position', [100 100 1200 600], ... % cambiare con g handle
                'CloseRequestFcn', @(h,e)close_function(h,e,obj));
            obj.InfoPanel = uipanel('Parent', obj.MainFigure,...
                'Units', 'normalized', ...
                'Position', [0 0 0.2 1]);
            obj.PlotPanel = uipanel('Parent', obj.MainFigure,...
                'Units', 'normalized', ...
                'Position', [0.21 0 0.59 1]);
            obj.SettingPanel = uipanel('Parent', obj.MainFigure,...
                'Units', 'normalized', ...
                'Position', [0.81 0 0.2 1]);
            
            obj.ResizeButton1 = annotation(obj.MainFigure, 'textbox', ...
                'Units', 'normalized', ...
                'Position', [0.2 0 0.01 1], ...
                'ButtonDownFcn', @(h,e)resize_1(h,e,obj));
            obj.ResizeButton2 = annotation(obj.MainFigure, 'textbox', ...
                'Units', 'normalized',...
                'Position', [0.8 0 0.01 1],...
                'ButtonDownFcn', @(h,e)resize_2(h,e,obj));
            
            obj.populateinfo;
            obj.populateplot;
            obj.populatesetting;
        end
        
        function populateinfo(obj)
            obj.DataTypeLabel = uicontrol('Parent', obj.InfoPanel, ...
                'Style', 'text', ...
                'Units', 'normalized',...
                'Position', [0.1 0.95 0.8 0.03],...
                'HorizontalAlignment', 'left', ...
                'String', 'Data type');
            obj.DataType = uicontrol('Parent', obj.InfoPanel, ...
                'Style', 'popup', ...
                'Units', 'normalized',...
                'Position', [0.1 0.9 0.8 0.05],...
                'String', {'SrcDet'; 'Channels'}, ...
                'Callback', @(h,e)switch_datatype(h,e,obj));
            
            obj.SrcListLabel = uicontrol('Parent', obj.InfoPanel, ...
                'Style', 'text', ...
                'Units', 'normalized',...
                'Position', [0.1 0.85 0.35 0.03],...
                'HorizontalAlignment', 'left', ...
                'Visible', 'on', ...
                'String', 'Sources');
            obj.SrcList = uicontrol('Parent', obj.InfoPanel, ...
                'Style', 'listbox', ...
                'Units', 'normalized',...
                'Position', [0.1 0.45 0.35 0.4],...
                'String', obj.Probe.source.label, ...
                'Value', 1:length(obj.Probe.source.label), ...
                'Max', 2, ...
                'Visible', 'on', ...
                'Callback', @(h,e)srclist_callback(h,e,obj));
            
            obj.DetListLabel = uicontrol('Parent', obj.InfoPanel, ...
                'Style', 'text', ...
                'Units', 'normalized',...
                'Position', [0.55 0.85 0.35 0.03],...
                'HorizontalAlignment', 'left', ...
                'Visible', 'on', ...
                'String', 'Detectors');
            obj.DetList = uicontrol('Parent', obj.InfoPanel, ...
                'Style', 'listbox', ...
                'Units', 'normalized',...
                'Position', [0.55 0.45 0.35 0.4],...
                'String', obj.Probe.detector.label, ...
                'Value', 1:length(obj.Probe.detector.label), ...
                'Max', 2, ...
                'Visible', 'on', ...
                'Callback', @(h,e)detlist_callback(h,e,obj));
            
            obj.ChannelListLabel = uicontrol('Parent', obj.InfoPanel, ...
                'Style', 'text', ...
                'Units', 'normalized',...
                'Position', [0.1 0.85 0.8 0.03],...
                'HorizontalAlignment', 'left', ...
                'Visible', 'off', ...
                'String', 'Channels');
            obj.ChannelList = uicontrol('Parent', obj.InfoPanel, ...
                'Style', 'listbox', ...
                'Units', 'normalized',...
                'Position', [0.1 0.45 0.8 0.4],...
                'String', obj.Probe.channel.label, ...
                'Max', 2, ...
                'Visible', 'off', ...
                'Callback', @(h,e)channellist_callback(h,e,obj));
            
            obj.OptodeCheckbox = uicontrol('Parent', obj.InfoPanel, ...
                'Style', 'checkbox', ...
                'Units', 'normalized',...
                'Position', [0.1 0.35 0.8 0.05],...
                'HorizontalAlignment', 'left', ...
                'Visible', 'on', ...
                'String', 'Optodes', ...
                'Value', true, ...
                'Callback', @(h,e)optode_checkbox(h,e,obj));
            obj.ArrowCheckbox = uicontrol('Parent', obj.InfoPanel, ...
                'Style', 'checkbox', ...
                'Units', 'normalized',...
                'Position', [0.1 0.3 0.8 0.05],...
                'HorizontalAlignment', 'left', ...
                'Visible', 'on', ...
                'String', 'Direction', ...
                'Value', true, ...
                'Callback', @(h,e)arrow_checkbox(h,e,obj));
            obj.PhotonCheckbox = uicontrol('Parent', obj.InfoPanel, ...
                'Style', 'checkbox', ...
                'Units', 'normalized',...
                'Position', [0.1 0.25 0.8 0.05],...
                'HorizontalAlignment', 'left', ...
                'Visible', 'on', ...
                'String', 'Photon density', ...
                'Callback', @(h,e)photon_refresh(h,e,obj));
            
        end
        
        function populateplot(obj)
            obj.ProbeAxes = axes('Parent', obj.PlotPanel, ...
                'Units', 'normalized', ...
                'NextPlot', 'add', ...
                'Position', [0.1 0.1 0.8 0.8], ...
                'Visible', 'off');
            
            obj.Scalp = trisurf(obj.Atlas.Scalp.face, ...
                obj.Atlas.Scalp.node(:,1), obj.Atlas.Scalp.node(:,2), obj.Atlas.Scalp.node(:,3), ...
                ones(size(obj.Atlas.Scalp.node(:,3))), ...
                'SpecularStrength', 0, ...
                'EdgeColor', 'none', ...
                'FaceColor', [0.7 0.7 0.7], ...
                'FaceAlpha' ,0.3);
            obj.GreyMatter = trisurf(obj.Atlas.GreyMatter.face, ...
                obj.Atlas.GreyMatter.node(:,1), obj.Atlas.GreyMatter.node(:,2), obj.Atlas.GreyMatter.node(:,3), ...
                ones(size(obj.Atlas.GreyMatter.node(:,3))), ...
                'SpecularStrength', 0, ...
                'EdgeColor', 'none', ...
                'FaceColor', [0.7 0.2 0], ...
                'FaceAlpha', 0.3);
            obj.WhiteMatter = trisurf(obj.Atlas.WhiteMatter.face, ...
                obj.Atlas.WhiteMatter.node(:,1), obj.Atlas.WhiteMatter.node(:,2), obj.Atlas.WhiteMatter.node(:,3), ...
                ones(size(obj.Atlas.WhiteMatter.node(:,3))), ...
                'SpecularStrength', 0, ...
                'EdgeColor', 'none', ...
                'FaceColor', [0 0.2 0.2], ...
                'FaceAlpha', 0.3);
            
            obj.Light1 = light('Position',[100 0 100]);     % x is left->right, y is back->front
            obj.Light2 = light('Position',[-100 0 100]);
            
            axis equal
            axis off
            axis vis3d
            
            obj.SourceOptode = plot3(...
                [obj.Probe.source.position(:,1) obj.Probe.source.position(:,1)]', ...
                [obj.Probe.source.position(:,2) obj.Probe.source.position(:,2)]', ...
                [obj.Probe.source.position(:,3) obj.Probe.source.position(:,3)]', ...
                'Marker', '.', ...
                'MarkerSize', 20, ...
                'Color', 'r', ...
                'LineStyle', 'none', ...
                'Parent', obj.ProbeAxes);
            obj.DetectorOptode = plot3(...
                [obj.Probe.detector.position(:,1) obj.Probe.detector.position(:,1)]', ...
                [obj.Probe.detector.position(:,2) obj.Probe.detector.position(:,2)]', ...
                [obj.Probe.detector.position(:,3) obj.Probe.detector.position(:,3)]', ...
                'Marker', '.', ...
                'MarkerSize', 20, ...
                'Color', 'b', ...
                'LineStyle', 'none', ...
                'Parent', obj.ProbeAxes);
            
            obj.Sensitivity = scatter3(0,0,0, 'Visible', 'off');
        end
        
        function populatesetting(obj)
            obj.DownSamplingLabel = uicontrol('Parent', obj.SettingPanel, ...
                'Style', 'text', ...
                'Units', 'normalized',...
                'Position', [0.1 0.95 0.8 0.03],...
                'HorizontalAlignment', 'left', ...
                'Visible', 'on', ...
                'String', 'Downsampling Factor [> 1]');
            obj.DownSampling = uicontrol('Parent', obj.SettingPanel, ...
                'Style', 'edit', ...
                'Units', 'normalized',...
                'Position', [0.1 0.91 0.8 0.04],...
                'String', '10', ...
                'Visible', 'on', ...
                'Callback', @(h,e)photon_refresh(h,e,obj));
            
            obj.MaxMarkerSizeLabel = uicontrol('Parent', obj.SettingPanel, ...
                'Style', 'text', ...
                'Units', 'normalized',...
                'Position', [0.1 0.85 0.8 0.03],...
                'HorizontalAlignment', 'left', ...
                'Visible', 'on', ...
                'String', 'Max Marker Size');
            obj.MaxMarkerSize = uicontrol('Parent', obj.SettingPanel, ...
                'Style', 'edit', ...
                'Units', 'normalized',...
                'Position', [0.1 0.81 0.8 0.04],...
                'String', '10', ...
                'Visible', 'on', ...
                'Callback', @(h,e)photon_refresh(h,e,obj));
            
            obj.AngleLabel = uicontrol('Parent', obj.SettingPanel, ...
                'Style', 'text', ...
                'Units', 'normalized',...
                'Position', [0.1 0.75 0.8 0.03],...
                'HorizontalAlignment', 'left', ...
                'Visible', 'on', ...
                'String', 'Plane cut angles');
            obj.Angle1 = uicontrol('Parent', obj.SettingPanel, ...
                'Style', 'edit', ...
                'Units', 'normalized',...
                'Position', [0.1 0.71 0.35 0.04],...
                'String', '0', ...
                'Visible', 'on', ...
                'Callback', @(h,e)photon_refresh(h,e,obj));
            obj.Angle2 = uicontrol('Parent', obj.SettingPanel, ...
                'Style', 'edit', ...
                'Units', 'normalized',...
                'Position', [0.55 0.71 0.35 0.04],...
                'String', '0', ...
                'Visible', 'on', ...
                'Callback', @(h,e)photon_refresh(h,e,obj));
            
            obj.SensitivityThresholdLabel = uicontrol('Parent', obj.SettingPanel, ...
                'Style', 'text', ...
                'Units', 'normalized',...
                'Position', [0.1 0.65 0.8 0.03],...
                'HorizontalAlignment', 'left', ...
                'Visible', 'on', ...
                'String', 'Sensitivity Threshold');
            obj.SensitivityThreshold = uicontrol('Parent', obj.SettingPanel, ...
                'Style', 'edit', ...
                'Units', 'normalized',...
                'Position', [0.1 0.61 0.8 0.04],...
                'String', '-6', ...
                'Visible', 'on', ...
                'Callback', @(h,e)photon_refresh(h,e,obj));
            
            obj.ColormapLabel = uicontrol('Parent', obj.SettingPanel, ...
                'Style', 'text', ...
                'Units', 'normalized',...
                'Position', [0.1 0.55 0.8 0.03],...
                'HorizontalAlignment', 'left', ...
                'Visible', 'on', ...
                'String', 'Colormap');
            obj.Colormap = uicontrol('Parent', obj.SettingPanel, ...
                'Style', 'popup', ...
                'Units', 'normalized',...
                'Position', [0.1 0.51 0.8 0.04],...
                'String', {'parula'; 'hsv'; 'hot'; 'gray'; 'bone'; ...
                'copper';'pink'; 'white'; 'flag';  'lines'; ...
                'colorcube';'jet'; 'prism'; 'cool'; ...
                'autumn'; 'spring'; 'winter';'summer'}, ...
                'Visible', 'on', ...
                'Callback', @(h,e)photon_refresh(h,e,obj));
            
            obj.ScaleLabel = uicontrol('Parent', obj.SettingPanel, ...
                'Style', 'text', ...
                'Units', 'normalized',...
                'Position', [0.1 0.45 0.8 0.03],...
                'HorizontalAlignment', 'left', ...
                'Visible', 'on', ...
                'String', 'Scale');
            obj.Scale = uicontrol('Parent', obj.SettingPanel, ...
                'Style', 'popup', ...
                'Units', 'normalized',...
                'Position', [0.1 0.41 0.8 0.04],...
                'String', {'linear'; 'log10'; 'log'; 'exp'; 'sqrt'; 'cube root'}, ...
                'Value', 2, ...
                'Visible', 'on', ...
                'Callback', @(h,e)photon_refresh(h,e,obj));
        end
        
    end
    
end

function close_function(h, ~, obj)
delete(h);
obj.GHandle.TempWindow = [];
end

function resize_1(~, ~, obj)
obj.MainFigure.WindowButtonMotionFcn = @(h,e)panel_resizing1(h,e,obj);
obj.MainFigure.WindowButtonUpFcn = @(h,e)stop_resizing(h,e);
end
function panel_resizing1(h, ~, obj)
relXPos = h.CurrentPoint(1)./h.Position(3);
obj.ResizeButton1.Position(1) = max(relXPos - 0.005,0);
obj.InfoPanel.Position(3) = obj.ResizeButton1.Position(1);
obj.PlotPanel.Position(1) = obj.ResizeButton1.Position(1) + 0.01;
obj.PlotPanel.Position(3) = obj.ResizeButton2.Position(1) - obj.PlotPanel.Position(1);
end

function resize_2(~, ~, obj)
obj.MainFigure.WindowButtonMotionFcn = @(h,e)panel_resizing2(h,e,obj);
obj.MainFigure.WindowButtonUpFcn = @(h,e)stop_resizing(h,e);
end
function panel_resizing2(h, ~, obj)
relXPos = h.CurrentPoint(1)./h.Position(3);
obj.SettingPanel.Position(1) = min(relXPos + 0.005,1);
obj.SettingPanel.Position(3) = 1 - obj.SettingPanel.Position(1);
obj.ResizeButton2.Position(1) = obj.SettingPanel.Position(1) - 0.01;
obj.PlotPanel.Position(3) = obj.ResizeButton2.Position(1) - obj.PlotPanel.Position(1);
end

function stop_resizing(h, ~)
h.WindowButtonMotionFcn = [];
h.WindowButtonUpFcn = [];
end

function switch_datatype(h, ~, obj)
if h.Value == 1
    obj.SrcListLabel.Visible = 'on';
    obj.SrcList.Visible = 'on';
    obj.DetListLabel.Visible = 'on';
    obj.DetList.Visible = 'on';
    obj.ChannelList.Visible = 'off';
    obj.ChannelListLabel.Visible = 'off';
else
    obj.SrcListLabel.Visible = 'off';
    obj.SrcList.Visible = 'off';
    obj.DetListLabel.Visible = 'off';
    obj.DetList.Visible = 'off';
    obj.ChannelList.Visible = 'on';
    obj.ChannelListLabel.Visible = 'on';
end
end

function srclist_callback(h, ~, obj)
colorOn = 'r';
colorOff = [0.2 0 0];
set(obj.SourceOptode,'Color', colorOff);
set(obj.SourceOptode(h.Value),'Color', colorOn);
photon_refresh([],[],obj);
end
function detlist_callback(h, ~, obj)
colorOn = 'b';
colorOff = [0 0 0.2];
set(obj.DetectorOptode,'Color', colorOff);
set(obj.DetectorOptode(h.Value),'Color', colorOn);
photon_refresh([],[],obj);
end
function channellist_callback(h, ~, obj)
src = obj.Probe.channel.pairs(h.Value,1);
det = obj.Probe.channel.pairs(h.Value,2);

colorOn = 'r';
colorOff = [0.2 0 0];
set(obj.SourceOptode,'Color', colorOff);
set(obj.SourceOptode(src),'Color', colorOn);

colorOn = 'b';
colorOff = [0 0 0.2];
set(obj.DetectorOptode,'Color', colorOff);
set(obj.DetectorOptode(det),'Color', colorOn);

photon_refresh([],[],obj);
end

function optode_checkbox(h, ~, obj)
if h.Value == true
    set(obj.SourceOptode,'Visible', 'on');
    set(obj.DetectorOptode,'Visible', 'on');
else
    set(obj.SourceOptode,'Visible', 'off');
    set(obj.DetectorOptode,'Visible', 'off');
end
end

function arrow_checkbox(h, ~, obj)

end

function photon_refresh(~, ~, obj)
if obj.PhotonCheckbox.Value == true
    obj.Sensitivity.delete;
    
    if obj.DataType.Value == 1
        photonDensityOrig = sum(abs([obj.Forward.srcFlux(:, obj.SrcList.Value) obj.Forward.detFlux(:, obj.DetList.Value)]), 2);
        flaggona = size([obj.SrcList.Value; obj.DetList.Value],2) == 1;
    else
        src = obj.Probe.channel.pairs(obj.ChannelList.Value,1);
        det = obj.Probe.channel.pairs(obj.ChannelList.Value,2);
        photonDensityOrig = sum(abs(obj.Forward.srcFlux(:,src).*obj.Forward.detFlux(:,det)),2);
        flaggona = size(obj.ChannelList.Value,2) == 1;
    end
    
    photonDensity = photonDensityOrig ./ max(photonDensityOrig);
    
    switch obj.Scale.String{obj.Scale.Value}
        case 'linear'
            ...
        case 'log10'
        photonDensity = log10(photonDensity);
        case 'log'
            photonDensity = log(photonDensity);
        case 'exp'
            photonDensity = exp(photonDensity);
        case 'sqrt'
            photonDensity = photonDensity.^(1/2);
        case 'cube root'
            photonDensity = photonDensity.^(1/3);
    end
    
    sensitivityColormap = feval(obj.Colormap.String{obj.Colormap.Value},128);
    sensitivityThreshold = max(str2double(obj.SensitivityThreshold.String), -Inf);
    maxMarkerSize = max(str2double(obj.MaxMarkerSize.String), 0);
    downsamplingFactor = round(max(str2double(obj.DownSampling.String), 1));
    
    sensitivityMask = photonDensity > sensitivityThreshold;
    
    
    
    % get the half sensitivity to see the section in plot
    if flaggona
        if obj.DataType.Value == 1
            srcDir = [obj.Forward.srcDir(obj.SrcList.Value,:); obj.Forward.detDir(obj.DetList.Value,:)];
            p1 = [obj.Forward.src(obj.SrcList.Value,:); obj.Forward.det(obj.DetList.Value,:)];
            p2 = p1 + srcDir;
            iVersor = [1 0 0];
            jVersor = [0 1 0]; %#ok vuoi non metterlo?
            kVersor = [0 0 1];
            if norm(cross(srcDir, iVersor)) > 0.1
                p3 = p1 + iVersor;
            else
                p3 = p1 + kVersor;
            end
        else
            p1 = obj.Forward.src(src,:);
            p2 = obj.Forward.det(det,:);
            p3 = centerofmass(obj.Forward.node(:,1:3), photonDensityOrig);
        end
        
        coffp3 = points2plane(p1, p2, p3);
        angle1 = deg2rad(str2double(obj.Angle1.String));
        p31 = (p3-p1)*rotate3dax(angle1,p2-p1) + p1;
        coff = points2plane(p1, p2, p31);
        mask1 = dot(obj.Forward.node(:,1:3), repmat(coff(1:3),[size(obj.Forward.node,1) 1]),2) + coff(4) > 0;
        mask1 = and(mask1, dot(obj.Forward.node(:,1:3), repmat(coffp3(1:3),[size(obj.Forward.node,1) 1]),2) + coffp3(4) > 0);
        angle2 = deg2rad(str2double(obj.Angle2.String));
        p32 = (p3-p1)*rotate3dax(-angle2,p2-p1) + p1;
        coff = points2plane(p1, p2, p32);
        mask2 = dot(obj.Forward.node(:,1:3), repmat(coff(1:3),[size(obj.Forward.node,1) 1]),2) + coff(4) < 0;
        mask2 = and(mask2, dot(obj.Forward.node(:,1:3), repmat(coffp3(1:3),[size(obj.Forward.node,1) 1]),2) + coffp3(4) < 0);
        angleMask = or(mask1, mask2);
    end

downSampleMask = false(size(sensitivityMask));
downSampleMask(1:downsamplingFactor:end) = sensitivityMask(1:downsamplingFactor:end);
sensitivityMask = and(downSampleMask, angleMask);
sensitivity2Plot = photonDensity(sensitivityMask);

minSensitivity = min(sensitivity2Plot);
maxSensitivity = max(sensitivity2Plot);
sensitivityNormalized = (sensitivity2Plot - minSensitivity)./(maxSensitivity - minSensitivity);

colorIdx = floor(sensitivityNormalized*127) + 1;

scatterSize = max(maxMarkerSize.*sensitivityNormalized , 0.01);
scatterColor = sensitivityColormap(colorIdx,:);

obj.Sensitivity = scatter3(obj.ProbeAxes, ...
    obj.Forward.node(sensitivityMask,1), ...
    obj.Forward.node(sensitivityMask,2), ...
    obj.Forward.node(sensitivityMask,3),...
    scatterSize,...
    scatterColor,...
    'filled'...
    );
else
    obj.Sensitivity.delete;
end
end
