function newatlas2(~, ~, GHandle)

figureSize = GHandle.Preference.Figure.sizeMedium;
BackgroundColor = GHandle.Preference.Theme.backgroundColor;
ForegroundColor = GHandle.Preference.Theme.foregroundColor;

GHandle.TempWindow.NewAtlasFigure = figure(...
    'position', figureSize,...
    'Resize', 'on',...
    'Name', 'New NIRS Atlas', ...
    'CloseRequestFcn',{@close_figure,GHandle},...
    'Numbertitle', 'off', ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL',...
    'Visible', 'off' ...
    );

%% Panels
GHandle.TempWindow.WidgetPanel = uipanel(...
    'Parent',GHandle.TempWindow.NewAtlasFigure,...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Units', 'normalize', ...
    'Position',[0.05 0.05 0.6 0.9], ...
    'BorderType', 'line');

GHandle.TempWindow.LogPanel = uipanel(...
    'Parent',GHandle.TempWindow.NewAtlasFigure,...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Units', 'normalize', ...
    'Position',[0.7 0.05 0.25 0.9], ...
    'BorderType', 'line');

%% Widgets panel
GHandle.TempWindow.AtlasNameLabel = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'Atlas Name',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.05 0.9 0.9 0.05]);
GHandle.TempWindow.AtlasName = uicontrol('Style', 'edit',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'Insert Name',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.05 0.85 0.9 0.05]);

GHandle.TempWindow.NoteLabel = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'Notes',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.05 0.75 0.9 0.05]);
GHandle.TempWindow.NoteName = uicontrol('Style', 'edit',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'Insert Notes',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.05 0.67 0.9 0.08]);

GHandle.TempWindow.BrowseLabel = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'Browse Atlas Folder',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.05 0.57 0.475 0.05]);
GHandle.TempWindow.BrowseName = uicontrol('Style', 'edit',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', '',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.05 0.52 0.74 0.05]);
GHandle.TempWindow.BrowseButton = uicontrol('Style', 'pushbutton',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'Browse',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'Callback', {@atlas_widget_callback, GHandle}, ...
    'Position', [0.8 0.52 0.15 0.05]);

GHandle.TempWindow.ScalpLabel = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'Scalp',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.15 0.4 0.35 0.05]);
GHandle.TempWindow.GreyLabel = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'Grey Matter',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.15 0.33 0.35 0.05]);
GHandle.TempWindow.WhiteLabel = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'White Matter',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.15 0.26 0.35 0.05]);
GHandle.TempWindow.VoxelLabel = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'Voxel',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.15 0.19 0.35 0.05]);
GHandle.TempWindow.HeadLabel = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'Head mesh',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.15 0.12 0.35 0.05]);
GHandle.TempWindow.LandmarkLabel = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'Landmarks',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.15 0.05 0.35 0.05]);

GHandle.TempWindow.ScalpIcon = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'X',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', 'r', ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'right', ...
    'FontWeight', 'bold', ...
    'Position', [0.05 0.4 0.05 0.05]);
GHandle.TempWindow.GreyIcon = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'X',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', 'r', ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'right', ...
    'FontWeight', 'bold', ...
    'Position', [0.05 0.33 0.05 0.05]);
GHandle.TempWindow.WhiteIcon = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'X',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', 'r', ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'right', ...
    'FontWeight', 'bold', ...
    'Position', [0.05 0.26 0.05 0.05]);
GHandle.TempWindow.VoxelIcon = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'X',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', 'r', ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'right', ...
    'FontWeight', 'bold', ...
    'Position', [0.05 0.19 0.05 0.05]);
GHandle.TempWindow.HeadIcon = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'X',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', 'r', ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'right', ...
    'FontWeight', 'bold', ...
    'Position', [0.05 0.12 0.05 0.05]);
GHandle.TempWindow.LandmarkIcon = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'X',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', 'r', ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'right', ...
    'FontWeight', 'bold', ...
    'Position', [0.05 0.05 0.05 0.05]);

GHandle.TempWindow.ScalpBar = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'dfgdf',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'FontWeight', 'bold', ...
    'Position', [0.55 0.4 0.4 0.05]);
GHandle.TempWindow.GreyBar = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'dfgdf',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'FontWeight', 'bold', ...
    'Position', [0.55 0.33 0.4 0.05]);
GHandle.TempWindow.WhiteBar = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'dfgdf',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'FontWeight', 'bold', ...
    'Position', [0.55 0.26 0.4 0.05]);
GHandle.TempWindow.VoxelBar = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'dfgdf',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'FontWeight', 'bold', ...
    'Position', [0.55 0.19 0.4 0.05]);
GHandle.TempWindow.HeadBar = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'dfgdf',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'FontWeight', 'bold', ...
    'Position', [0.55 0.12 0.4 0.05]);
GHandle.TempWindow.LandmarkBar = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.WidgetPanel, ...
    'String', 'dfgdf',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'FontWeight', 'bold', ...
    'Position', [0.55 0.05 0.4 0.05]);

%% Log panel
GHandle.TempWindow.LogLabel = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.LogPanel, ...
    'String', 'Loading log',...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.05 0.9 0.9 0.05]);
GHandle.TempWindow.LogName = uicontrol('Style', 'text',...
    'Parent', GHandle.TempWindow.LogPanel, ...
    'String', '',...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', ForegroundColor, ...
    'Visible','on',...
    'Units', 'normalize', ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.05 0.25 0.9 0.65]);

GHandle.TempWindow.SaveButton = uicontrol('Style', 'pushbutton',...
    'Parent', GHandle.TempWindow.LogPanel, ...
    'BackgroundColor', BackgroundColor, ...
    'ForegroundColor', ForegroundColor, ...
    'String', 'Save',...
    'Units', 'normalize', ...
    'Position', [0.05 0.05 0.9 0.1],...
    'Callback', {@save_atlas, GHandle}...
    );

%% Turn on
GHandle.TempWindow.NewAtlasFigure.Visible = 'on';
end

function atlas_widget_callback(~, ~, GHandle)
folderPath = uigetdir;
fileList = dir(folderPath);
GHandle.TempWindow.BrowseName.String = folderPath;

fileIdx = contains({fileList.name}, 'ScalpSurfaceMesh');
if any(fileIdx)
    GHandle.TempWindow.ScalpIcon.String = sprintf(strrep('\u2714', '\u', '\x'));
    GHandle.TempWindow.ScalpIcon.ForegroundColor = [0 1 0];
else
    GHandle.TempWindow.ScalpIcon.String = 'X';
    GHandle.TempWindow.ScalpIcon.ForegroundColor = [1 0 0];
end

fileIdx = contains({fileList.name}, 'GMSurfaceMesh');
if any(fileIdx)
    GHandle.TempWindow.GreyIcon.String = sprintf(strrep('\u2714', '\u', '\x'));
    GHandle.TempWindow.GreyIcon.ForegroundColor = [0 1 0];
else
    GHandle.TempWindow.GreyIcon.String = 'X';
    GHandle.TempWindow.GreyIcon.ForegroundColor = [1 0 0];
end

fileIdx = contains({fileList.name}, 'WMSurfaceMesh');
if any(fileIdx)
    GHandle.TempWindow.WhiteIcon.String = sprintf(strrep('\u2714', '\u', '\x'));
    GHandle.TempWindow.WhiteIcon.ForegroundColor = [0 1 0];
else
    GHandle.TempWindow.WhiteIcon.String = 'X';
    GHandle.TempWindow.WhiteIcon.ForegroundColor = [1 0 0];
end

fileIdx = contains({fileList.name}, 'TissueMask');
if any(fileIdx)
    GHandle.TempWindow.VoxelIcon.String = sprintf(strrep('\u2714', '\u', '\x'));
    GHandle.TempWindow.VoxelIcon.ForegroundColor = [0 1 0];
else
    GHandle.TempWindow.VoxelIcon.String = 'X';
    GHandle.TempWindow.VoxelIcon.ForegroundColor = [1 0 0];
end

fileIdx = contains({fileList.name}, 'HeadVolumeMesh');
if any(fileIdx)
    GHandle.TempWindow.HeadIcon.String = sprintf(strrep('\u2714', '\u', '\x'));
    GHandle.TempWindow.HeadIcon.ForegroundColor = [0 1 0];
else
    GHandle.TempWindow.HeadIcon.String = 'X';
    GHandle.TempWindow.HeadIcon.ForegroundColor = [1 0 0];
end

fileIdx = contains({fileList.name}, 'LandmarkPoints');
if any(fileIdx)
    GHandle.TempWindow.LandmarkIcon.String = sprintf(strrep('\u2714', '\u', '\x'));
    GHandle.TempWindow.LandmarkIcon.ForegroundColor = [0 1 0];
else
    GHandle.TempWindow.LandmarkIcon.String = 'X';
    GHandle.TempWindow.LandmarkIcon.ForegroundColor = [1 0 0];
end

end

function save_atlas(~, ~, GHandle)
%add a tree branch
name = GHandle.TempWindow.AtlasName.String;
note = GHandle.TempWindow.NoteName.String;

GHandle.TempWindow.loadingBar.GrayMatter = LoadingBar;
GHandle.TempWindow.loadingBar.WhiteMatter = LoadingBar;
GHandle.TempWindow.loadingBar.Scalp = LoadingBar;
GHandle.TempWindow.loadingBar.Voxel = LoadingBar;
GHandle.TempWindow.loadingBar.HeadVolume = LoadingBar;
GHandle.TempWindow.loadingBar.LandMarks = LoadingBar;

% Listener for perc bar
addlistener(GHandle.TempWindow.loadingBar.GrayMatter,'loadingPerc','PostSet',@(src,evnt)loading_graymatter(src,evnt,GHandle));
addlistener(GHandle.TempWindow.loadingBar.WhiteMatter,'loadingPerc','PostSet',@(src,evnt)loading_whitematter(src,evnt,GHandle));
addlistener(GHandle.TempWindow.loadingBar.Scalp,'loadingPerc','PostSet',@(src,evnt)loading_scalp(src,evnt,GHandle));
addlistener(GHandle.TempWindow.loadingBar.Voxel,'loadingPerc','PostSet',@(src,evnt)loading_voxel(src,evnt,GHandle));
addlistener(GHandle.TempWindow.loadingBar.HeadVolume,'loadingPerc','PostSet',@(src,evnt)loading_headvolume(src,evnt,GHandle));
addlistener(GHandle.TempWindow.loadingBar.LandMarks,'loadingPerc','PostSet',@(src,evnt)loading_landmarks(src,evnt,GHandle));
% Listener for log text
addlistener(GHandle.TempWindow.loadingBar.GrayMatter,'loadingText','PostSet',@(src,evnt)add_log(src,evnt,GHandle));
addlistener(GHandle.TempWindow.loadingBar.WhiteMatter,'loadingText','PostSet',@(src,evnt)add_log(src,evnt,GHandle));
addlistener(GHandle.TempWindow.loadingBar.Scalp,'loadingText','PostSet',@(src,evnt)add_log(src,evnt,GHandle));
addlistener(GHandle.TempWindow.loadingBar.Voxel,'loadingText','PostSet',@(src,evnt)add_log(src,evnt,GHandle));
addlistener(GHandle.TempWindow.loadingBar.HeadVolume,'loadingText','PostSet',@(src,evnt)add_log(src,evnt,GHandle));
addlistener(GHandle.TempWindow.loadingBar.LandMarks,'loadingText','PostSet',@(src,evnt)add_log(src,evnt,GHandle));

GHandle.TempWindow.loadingBar.GrayMatter.loadingPerc = 0;
GHandle.TempWindow.loadingBar.WhiteMatter.loadingPerc = 0;
GHandle.TempWindow.loadingBar.Scalp.loadingPerc = 0;
GHandle.TempWindow.loadingBar.Voxel.loadingPerc = 0;
GHandle.TempWindow.loadingBar.HeadVolume.loadingPerc = 0;
GHandle.TempWindow.loadingBar.LandMarks.loadingPerc = 0;

GHandle.TempWindow.location = GHandle.TempWindow.BrowseName.String;

GHandle.TempWindow.AtlasName.Enable = 'off';
GHandle.TempWindow.NoteName.Enable = 'off';

GHandle.TempWindow.LogName.String = 'Start Loading Atlas...';

loadatlasfrommat(GHandle);

GHandle.CurrentDataSet.Atlas.name = name;
GHandle.CurrentDataSet.Atlas.note = note;

DataBase = GHandle.DataBase.add(GHandle.CurrentDataSet.Atlas, name, GHandle.Temp);
GHandle.DataBase = DataBase;
close(GHandle.TempWindow.NewAtlasFigure);
tree(GHandle);
end


function loading_graymatter(~, evnt, GHandle)
if (evnt.AffectedObject.loadingPerc < 1)
    ii = round(10 * evnt.AffectedObject.loadingPerc);
else
    ii = 10;
end
GHandle.TempWindow.GreyBar.String =  [repmat(char(9608),[1 ii]) repmat(char(9618),[1 10-ii])];
drawnow;
end

function loading_whitematter(~, evnt, GHandle)
if (evnt.AffectedObject.loadingPerc < 1)
    ii = round(10 * evnt.AffectedObject.loadingPerc);
else
    ii = 10;
end
GHandle.TempWindow.WhiteBar.String =  [repmat(char(9608),[1 ii]) repmat(char(9618),[1 10-ii])];
drawnow;
end

function loading_scalp(~, evnt, GHandle)
if (evnt.AffectedObject.loadingPerc < 1)
    ii = round(10 * evnt.AffectedObject.loadingPerc);
else
    ii = 10;
end
GHandle.TempWindow.ScalpBar.String =  [repmat(char(9608),[1 ii]) repmat(char(9618),[1 10-ii])];
drawnow;
end

function loading_voxel(~, evnt, GHandle)
if (evnt.AffectedObject.loadingPerc < 1)
    ii = round(10 * evnt.AffectedObject.loadingPerc);
else
    ii = 10;
end
GHandle.TempWindow.VoxelBar.String =  [repmat(char(9608),[1 ii]) repmat(char(9618),[1 10-ii])];
drawnow;
end

function loading_headvolume(~, evnt, GHandle)
if (evnt.AffectedObject.loadingPerc < 1)
    ii = round(10 * evnt.AffectedObject.loadingPerc);
else
    ii = 10;
end
GHandle.TempWindow.HeadBar.String =  [repmat(char(9608),[1 ii]) repmat(char(9618),[1 10-ii])];
drawnow;
end

function loading_landmarks(~, evnt, GHandle)
if (evnt.AffectedObject.loadingPerc < 1)
    ii = round(10 * evnt.AffectedObject.loadingPerc);
else
    ii = 10;
end
GHandle.TempWindow.LandmarkBar.String =  [repmat(char(9608),[1 ii]) repmat(char(9618),[1 10-ii])];
drawnow;
end

function add_log(~, evnt, GHandle)
GHandle.TempWindow.LogName.String = char(GHandle.TempWindow.LogName.String, evnt.AffectedObject.loadingText);
drawnow;
end

function close_figure(Handle, ~, GHandle)
delete(Handle);
GHandle.TempWindow = [];
end