function newatlas(~, ~, GHandle)	

	figureSize = GHandle.Preference.Figure.sizeMedium;


	GHandle.TempWindow.NewAtlasFigure = figure(...
	'position', figureSize,...
    'Resize', 'on',...
    'Name', 'New NIRS Atlas', ...
    'Numbertitle', 'off', ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL',...
	'Visible', 'off' ...
	);
	
	GHandle.TempWindow.NewAtlasName = uiw.widget.EditableText(...      
    'Parent',GHandle.TempWindow.NewAtlasFigure,...=
    'Value','Insert Name',...
    'Label','Study Name:',...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.80 0.35 0.15]);

	GHandle.TempWindow.NewAtlasNote = uiw.widget.EditableText(...      
    'Parent',GHandle.TempWindow.NewAtlasFigure,...
    'Value','Insert Note',...
    'Label','Study Note:',...
	'IsMultiLine', 1,...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.50 0.05 0.25 0.45]);

	GHandle.TempWindow.NewAtlasLoadButton = uicontrol('Style', 'pushbutton',...	
    'Parent', GHandle.TempWindow.NewAtlasFigure, ...
	'String', 'Load',...
	'Units', 'normalize', ...
	'Position', [0.8 0.15 0.2 0.1],...
	'Callback', {@load_atlas ,GHandle}...
	); 

	GHandle.TempWindow.NewAtlasFigure.Visible = 'on';

end

function load_atlas(~,~, GHandle)
end
















