function newprobe(~, ~, GHandle)
	
	figureSize = GHandle.Preference.Figure.sizeLarge;


	GHandle.TempWindow.NewProbeFigure = figure(...
	'position', figureSize,...
    'Resize', 'on',...
    'Name', 'New NIRS Probe', ...
    'Numbertitle', 'off', ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL',...
	'Visible', 'off' ...
	);
	
	GHandle.TempWindow.NewProbeName = uiw.widget.EditableText(...      
    'Parent',GHandle.TempWindow.NewProbeFigure,...=
    'Value','Insert Name',...
    'Label','Probe Name:',...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.90 0.15 0.08]);

	GHandle.TempWindow.NewProbeNote = uiw.widget.EditableText(...      
    'Parent',GHandle.TempWindow.NewProbeFigure,...
    'Value','Insert Note',...
    'Label','Study Note:',...
	'IsMultiLine', 1,...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.65 0.20 0.20]);

	
	GHandle.TempWindow.NewProbeLoadButton = uicontrol('Style', 'pushbutton',...	
    'Parent', GHandle.TempWindow.NewProbeFigure, ...
	'String', 'Load',...
	'Units', 'normalize', ...
	'Position', [0.8 0.15 0.1 0.05],...
	'Callback', {@loadprobe ,GHandle}...
	); 

	GHandle.TempWindow.NewProbeAxes = axes(...
	'Parent', GHandle.TempWindow.NewProbeFigure,...
	'NextPlot', 'add',...
	'View', [45,45],...
	'Units', 'normalize', ...
	'Position', [0.5 0.3 0.4 0.4]...
	);
	
	%sistemare con phantom
	sphere;
	phi = rand(10,1)*pi;
	theta = rand(10,1)*pi;
	GHandle.TempWindow.NewProbeScatter = scatter3(...
		sin(phi),cos(phi).*sin(theta),cos(phi).*cos(theta),...
		'filled',...
		'Marker','s',...
		'SizeData',60,...
		'MarkerEdgeColor', 'k',...
		'LineWidth',1,...
		'ButtonDownFcn',{@(handle, evnt)scatter_callback(handle, evnt ,GHandle)});
	
	GHandle.TempWindow.NewProbeScatterDetector = scatter3(...
		[],[],[],...
		'filled',...
		'SizeData',60,...
		'MarkerEdgeColor', 'k',...
		'LineWidth',1,...
		'ButtonDownFcn',{@(handle, evnt)scatterdetector_callback(handle, evnt ,GHandle)});
	
	GHandle.TempWindow.NewProbeScatterSource = scatter3(...
		[],[],[],...
		'Marker','x',...
		'SizeData',60,...
		'MarkerEdgeColor', 'k',...
		'LineWidth',1,...
		'ButtonDownFcn',{@(handle, evnt)scattersource_callback(handle, evnt ,GHandle)});
	

	GHandle.TempWindow.NewProbeFigure.Visible = 'on';

end


function loadprobe(~, ~, GHandle )
	
	
	probeName = GHandle.TempWindow.NewProbeName.Value;
	note = GHandle.TempWindow.NewProbeNote.Value;

	NewProbe = NirsProbe('name', probeName, 'note', note);
	
	DataBase = GHandle.DataBase.add(NewProbe);

	GHandle.DataBase = DataBase;
		
	tree(GHandle);
	
	GHandle.Main.Tree.TabGroup.SelectedTab = GHandle.Main.Tree.ProbeTab;
	
end


function scatter_callback(~, evnt ,GHandle)
	xData = GHandle.TempWindow.NewProbeScatter.XData;
	yData = GHandle.TempWindow.NewProbeScatter.YData;
	zData = GHandle.TempWindow.NewProbeScatter.ZData;
    xIntersection = evnt.IntersectionPoint(1);
	yIntersection = evnt.IntersectionPoint(2);
	zIntersection = evnt.IntersectionPoint(3);
	
	[~ ,idxX ] = min(abs(xData-xIntersection));
	[~ ,idxY ] = min(abs(yData-yIntersection));
	[~ ,idxZ ] = min(abs(zData-zIntersection));
	
	if ((idxX == idxY) && (idxY == idxZ))
		set(GHandle.TempWindow.NewProbeScatterSource,'XData',xData(idxX),'YData',yData(idxX),'ZData',zData(idxX))
		xData(idxX) = [];
		yData(idxX) = [];
		zData(idxX) = [];		
		set(GHandle.TempWindow.NewProbeScatter,'XData',xData,'YData',yData,'ZData',zData);
	end
end


function scatterdetector_callback



end

function scattersource_callback


end
