function newprobe(~, ~, GHandle)
	
	figureSize = GHandle.Preference.Figure.sizeMedium;


	GHandle.TempWindow.NewProbeFigure = figure(...
	'position', figureSize,...
    'Resize', 'on',...
    'Name', 'New NIRS Study', ...
    'Numbertitle', 'off', ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL',...
	'Visible', 'off' ...
	);
	
	GHandle.TempWindow.NewProbeName = uiw.widget.EditableText(...      
    'Parent',GHandle.TempWindow.NewProbeFigure,...=
    'Value','Insert Name',...
    'Label','Study Name:',...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.80 0.35 0.15]);

	GHandle.TempWindow.NewProbeNote = uiw.widget.EditableText(...      
    'Parent',GHandle.TempWindow.NewProbeFigure,...
    'Value','Insert Note',...
    'Label','Study Note:',...
	'IsMultiLine', 1,...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.50 0.05 0.25 0.45]);

	
	GHandle.TempWindow.NewProbeLoadButton = uicontrol('Style', 'pushbutton',...	
    'Parent', GHandle.TempWindow.NewProbeFigure, ...
	'String', 'Load',...
	'Units', 'normalize', ...
	'Position', [0.8 0.15 0.2 0.1],...
	'Callback', {@loadprobe ,GHandle}...
	); 

	GHandle.TempWindow.NewProbeFigure.Visible = 'on';

end


function loadprobe(~, ~, GHandle )
	
	
	probeName = GHandle.TempWindow.NewProbeName.Value;
	note = GHandle.TempWindow.NewProbeNote.Value;

	NewProbe = NirsProbe('name', probeName, 'note', note);
	
	DataBase = GHandle.DataBase.add(NewProbe);

	GHandle.DataBase = DataBase;
		
	tree(GHandle);
	
	GHandle.Main.Tree.TabGroup.SelectedTab = GHandle.Main.Tree.ProbeTab;
	
end
















