function methodwindow(GHandle)
	
	methodPath = fullfile(GHandle.Preference.Path.currentPath, 'Method', 'MethodList.mat');
	GHandle.MethodWindow = load(methodPath); % it wipe out also the field
	
	fontSize = GHandle.Preference.Font.sizeL;
	EdgeColor = 'k';
	BackGroundColor = 'g';
	LineWidth = 3;
	position = [0.3 0.9 0.3 0.07];
	
	figurePosition = GHandle.Preference.Figure.sizeLarge;

	GHandle.MethodWindow.WatchList  = MethodWatchList;

	GHandle.MethodWindow.mainFigure = figure('Position', figurePosition, ...
    'Visible', 'on', ...
    'Resize', 'on',...
    'Name', 'Viewer', ...
    'Numbertitle', 'off', ...
    'Tag', 'sensors_viewer', ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL');

	
	position = [0.01 0.01 0.20 0.90];


GHandle.MethodWindow.Tree.MethodTree = uiw.widget.Tree(...
		'Parent',GHandle.MethodWindow.mainFigure,...
		'Label','Database:', ...
		'LabelLocation','top',...
		'LabelHeight',18,...
		'Units', 'normalized', ...
		'Position', position,...
		'RootVisible', 'false'...
		);


nMethod = length(GHandle.MethodWindow.MethodList);
for iMethod = 1:nMethod
	
	CurrentMethod = GHandle.MethodWindow.MethodList(iMethod);

	
	if ~isfield(GHandle.MethodWindow.Tree, CurrentMethod.type)
		
		GHandle.MethodWindow.Tree.(CurrentMethod.type).MainNode =...
				uiw.widget.TreeNode('Name', CurrentMethod.type,...
				'Parent', GHandle.MethodWindow.Tree.MethodTree...
				); 
	end
	
	if ~isempty(CurrentMethod.subType)
		if ~isfield(GHandle.MethodWindow.Tree, CurrentMethod.subType)
			GHandle.MethodWindow.Tree.(CurrentMethod.subType).MainNode =...
					uiw.widget.TreeNode('Name', CurrentMethod.subType,...
					'Parent', GHandle.MethodWindow.Tree.(CurrentMethod.type).MainNode...
					); 
		end
		
	GHandle.MethodWindow.Tree.(CurrentMethod.tag).MainNode =...
		uiw.widget.TreeNode('Name', CurrentMethod.name,...
		'Parent', GHandle.MethodWindow.Tree.(CurrentMethod.subType).MainNode,...
		'Value', CurrentMethod.tag...
		); 			
	else
			
	GHandle.MethodWindow.Tree.(CurrentMethod.tag).MainNode =...
		uiw.widget.TreeNode('Name', CurrentMethod.name,...
		'Parent', GHandle.MethodWindow.Tree.(CurrentMethod.type).MainNode,...
		'Value', CurrentMethod.tag...
		); 
	end		
	
	GHandle.MethodWindow.Tree.MethodTree.MouseClickedCallback = {@clickcallback,GHandle}; 
end
	position = [0.3 0.90 0.3 0.07];
	GHandle.MethodWindow.EventsTextBox.Input =...
		 annotation(GHandle.MethodWindow.mainFigure, 'textbox',...
		 'FontSize',fontSize,...
		 'EdgeColor', EdgeColor,...
		 'LineWidth', LineWidth,...
		 'BackGroundColor', BackGroundColor,...
		 'String', 'Input',...
		 'Units', 'normalized', ...
		 'Position',position...
		);
	pos = [0.45 0.90 0 -0.03];
	GHandle.MethodWindow.EventsArrow.Input =...
		 annotation( GHandle.MethodWindow.mainFigure,'arrow', ...
		  'Units', 'normalized', ...
		 'Position',pos...
		);
	
	GHandle.MethodWindow.methodListListener = addlistener(GHandle.MethodWindow.WatchList,...
		'listMethod','PostSet',@(src,evnt)methodboxplot(src,evnt,GHandle));

end
function clickcallback(~, Event, GHandle) 

		if ~isempty(Event.Nodes) % click on a node 
			switch Event.SelectionType 
				
				case 'normal' 
					%displaymethod
					
				case 'open'
					methodIdx = strcmp({GHandle.MethodWindow.MethodList.tag},...
						Event.Nodes.Value);
					method2Add = GHandle.MethodWindow.MethodList(methodIdx);
					GHandle.MethodWindow.WatchList.listMethod =...
						[GHandle.MethodWindow.WatchList.listMethod ;method2Add];

					
				case 'alt' 
					%'dxstudy	
			end 
		end

end
