function  Handle = guidisp(Probe, GHandle , editableField)
dxsxEdge = 0.05;
overunderEdge = 0.009;
textBoxWidth = 0.3;
textBoxHeight = 0.12;
gmColor = [0.65 0.65 0.65];
wmColor =  [1 1 1];
scalpColor = [255 229 204]./255;
sourceColor = [1 0 0];
detectorColor = [0 0 1];

idx = GHandle.Temp.idx;
fontName = 'Arial'; %'Lobster Two';


textFontSize = GHandle.Preference.Font.sizeM;

idx = GHandle.Temp.idx;

% create the figure and the editable field if is not specify
if ~exist('editableField','var')
    editableField = '';
end
editableField = lower(editableField);

if ~exist('GHandle','var') || isempty(GHandle)
    Handle.MainFigure = figure;
    GHandle.Main.SubPanel.Panel = uipanel('Parent',Handle.MainFigure);
end

% assign the title
GHandle.Main.Display.SubPanel(idx).Panel.Title = 'Probe';

% id
lowerPos = (0.3 +overunderEdge) + 3 *( 0.7 - overunderEdge)/4;
GHandle.Main.Display.SubPanel(idx).IdTextBox = gtextbox(...
    'Parent',GHandle.Main.Display.SubPanel(idx).Panel,...
    'TextString',Probe.id,...
    'TitleString','ID:',...
    'FontSize',textFontSize,...
    'Units','normalized',...
    'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);


lowerPos = (0.3 +overunderEdge) + 2 *( 0.7 - overunderEdge)/4;
% name
if any(contains(editableField,'name'))
    GHandle.Main.Display.SubPanel(idx).NameEditableTextBox = geditabletext(...
        'Parent',GHandle.Main.Display.SubPanel(idx).Panel,...
        'TextString',Probe.name,...
        'TitleString','Name',...
        'FontSize',textFontSize,...
        'Units','normalized',...
        'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);
else
    GHandle.Main.Display.SubPanel(idx).NameTextBox = gtextbox(...
        'Parent',GHandle.Main.Display.SubPanel(idx).Panel,...
        'TextString',Probe.name,...
        'TitleString','Name:',...
        'FontSize',textFontSize,...
        'Units','normalized',...
        'Position',[dxsxEdge lowerPos textBoxWidth textBoxHeight]);
end

GHandle.Main.Display.SubPanel(idx).SubPanel = uipanel(...
    'Parent',GHandle.Main.Display.SubPanel(idx).Panel,...
    'Units', 'normalize', ...
    'Position',[0.45 0.05 0.50 0.90],...
    'Visible', 'on',...
    'BackgroundColor',[0 0 0]);

GHandle.Main.Display.SubPanel(idx).Axes = axes(...
    'Parent',GHandle.Main.Display.SubPanel(idx).SubPanel,...
    'Units', 'normalize', ...
    'Position',[0 0 1 1],...
    'NextPlot','add',...
    'Visible', 'off');

set(GHandle.Main.Display.SubPanel(idx).Axes,'CameraViewAngle',get(GHandle.Main.Display.SubPanel(idx).Axes,'CameraViewAngle'));
set(GHandle.Main.Display.SubPanel(idx).Axes,'PlotBoxAspectRatio',get(GHandle.Main.Display.SubPanel(idx).Axes,'PlotBoxAspectRatio'));
set(GHandle.Main.Display.SubPanel(idx).Axes,'DataAspectRatio',get(GHandle.Main.Display.SubPanel(idx).Axes,'DataAspectRatio'));
rotate3d(GHandle.Main.Display.SubPanel(idx).Axes, 'on');

lighting(GHandle.Main.Display.SubPanel(idx).Axes,'gouraud');
GHandle.Main.Display.SubPanel(idx).Light(1) = light('Position', [+100 0 50]);
GHandle.Main.Display.SubPanel(idx).Light(2) = light('Position', [-100 0 50]);




GHandle.Main.Display.SubPanel(idx).Scalp = trisurf(...
    Atlas.Scalp.face,...
    Atlas.Scalp.node(:,1),Atlas.Scalp.node(:,2), Atlas.Scalp.node(:,3),...
    ones(size(Atlas.Scalp.node(:,3))),...
    'Parent', GHandle.Main.Display.SubPanel(idx).Axes,...
    'SpecularStrength', 0, ...
    'EdgeColor','none',...
    'FaceColor',scalpColor,...
    'FaceAlpha',0.2);

GHandle.Main.Display.SubPanel(idx).Gray = trisurf(...
    Atlas.GreyMatter.face,...
    Atlas.GreyMatter.node(:,1),Atlas.GreyMatter.node(:,2), Atlas.GreyMatter.node(:,3),...
    2.*ones(size(Atlas.GreyMatter.node(:,3))),...
    'Parent', GHandle.Main.Display.SubPanel(idx).Axes,...
    'SpecularStrength', 0, ...
    'EdgeColor','none',...
    'FaceColor',gmColor,...
    'FaceAlpha',0.3);

GHandle.Main.Display.SubPanel(idx).White = trisurf(...
    Atlas.WhiteMatter.face,...
    Atlas.WhiteMatter.node(:,1),Atlas.WhiteMatter.node(:,2), Atlas.WhiteMatter.node(:,3),...
    3.*ones(size(Atlas.WhiteMatter.node(:,3))),...
    'Parent', GHandle.Main.Display.SubPanel(idx).Axes,...
    'SpecularStrength', 0, ...
    'EdgeColor','none',...
    'FaceColor',wmColor);


end

