function dispmethod(obj)
backgroundColor = [0.9 0.9 0.9];

Method = obj.Method;
nParam = 0;

if isfield(Method.UserParameters,'name')
    paramNames = {Method.UserParameters.name};
    paramField = {Method.UserParameters.field};
    paramString = {Method.UserParameters.string};
    paramStyle = {Method.UserParameters.style};
    
    %% Calculate sizing parameters
    nParam = length(paramNames);
    inter = 1/(5*nParam+1);
    %%
    intra = 2*inter;
end
obj.Parent.InfoSetPanelUp.Children.delete;

%% Create GUI objects
for iParam = 1:1:nParam
    labelPos = [0.1, intra*(nParam-iParam+1) + 3*inter*(nParam-iParam)+inter, 0.8, inter];
    valuePos = [0.1, intra*(nParam-iParam+1) + 3*inter*(nParam-iParam), 0.8, inter];
    textLabel(iParam) = uicontrol('Parent', obj.Parent.InfoSetPanelUp, ...
        'Style', 'text', ...
        'Units', 'normalized',...
        'Position', labelPos,...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', backgroundColor*0.9, ...
        'Visible', 'on', ...
        'String', paramNames{iParam});
    switch paramStyle{iParam}
        case {'edit', 'text'}
            if ~isempty(paramField{iParam})
                textValue(iParam) = uicontrol('Parent', obj.Parent.InfoSetPanelUp, ...
                    'Style', paramStyle{iParam}, ...
                    'Units', 'normalized',...
                    'Position', valuePos,...
                    'Callback', @(h,e)update_parameter(h,e,obj,iParam),...
                    'HorizontalAlignment', 'left', ...
                    'BackgroundColor', backgroundColor*1.1, ...
                    'Visible', 'on', ...
                    'String', num2str(Method.Parameters.(paramField{iParam})));
            end
            
        case 'checkbox'
            textValue(iParam) = uicontrol('Parent', obj.Parent.InfoSetPanelUp, ...
                'Style', 'checkbox', ...
                'Units', 'normalized',...
                'Position', valuePos,...
                'Callback', @(h,e)update_parameter(h,e,obj,iParam),...
                'HorizontalAlignment', 'left', ...
                'BackgroundColor', backgroundColor*1.1, ...
                'Visible', 'on', ...
                'Value', Method.Parameters.(paramField{iParam}));
            
        case 'listbox'
            switch lower(paramString{iParam})
                case 'event'
                    stringList = obj.Parent.AnalysisData.Measure.Event.Dictionary(:,2);
                otherwise
                    stringList = paramString{iParam};
            end
            textValue(iParam) = uicontrol('Parent', obj.Parent.InfoSetPanelUp, ...
                'Style', 'listbox', ...
                'Units', 'normalized',...
                'Position', valuePos,...
                'Callback', @(h,e)update_parameter(h,e,obj,iParam),...
                'HorizontalAlignment', 'left', ...
                'BackgroundColor', backgroundColor*1.1, ...
                'Visible', 'on', ...
                'Max', 2, ...
                'Value', Method.Parameters.(paramField{iParam}),...
                'String', stringList);
        otherwise
            %% inserire warning
    end
    
end

end

function update_parameter(h,~,obj,iParam)
paramField = {obj.Method.UserParameters.field};


switch h.Style
    case 'checkbox'
        obj.Method.Parameters.(paramField{iParam}) = h.Value;
    case 'listbox'
        obj.Method.Parameters.(paramField{iParam}) = h.Value;
    case 'edit'
        obj.Method.Parameters.(paramField{iParam}) = str2double(h.String);
    otherwise
        warning('gnegnegne');
end
end








