function populatepanel(GHandle)
 
backgroundColor = GHandle.Preference.Figure.backgroundColor;
foregroundColor = GHandle.Preference.Figure.foregroundColor;
highlightColor = GHandle.Preference.Figure.highlightColor;
defaultFontName = GHandle.Preference.Font.name;

stepW = 0.02;
stepH = 0.02;
panelaxesH = 0.7;
panelH = 1-panelaxesH-3*stepH;


labels = GHandle.Temp.labels;
values = GHandle.Temp.values;
panellabels = GHandle.Temp.panellabels;

npanels = length(panellabels);
panelwidth = (1-(npanels+1)*stepW)/npanels;

for jj = 1:1:npanels
    
    panel_position = [jj*stepW+(jj-1)*panelwidth stepH panelwidth panelH];
    GHandle.Viewer.metadata(jj).panel = uipanel('parent', GHandle.Viewer.mainFigure,...
        'Position', panel_position, ...
        'Units', 'normalized', ...
        'BackgroundColor', backgroundColor, ...
        'ForegroundColor', foregroundColor, ...
        'HighlightColor', highlightColor, ...
        'ShadowColor', [211 211 211]/255, ...
        'BorderType', 'line', ...
        'FontWeight', 'bold', ...
        'FontSize', 8, ...
        'FontName', defaultFontName, ...
        'Visible', 'on', ...
        'Title', panellabels{jj});
    
    currentlabels = fliplr(labels{1,jj});
	currentvalues = fliplr(values{1,jj});
	
    nlines = length(currentlabels);
    boxheight = 1/(nlines+2);
    for ii = 1:1:nlines
        GHandle.Viewer.metadata(jj).label(ii) = uicontrol('Parent', GHandle.Viewer.metadata(jj).panel, ...
            'Style', 'text', ...
            'BackgroundColor', backgroundColor, ...
            'ForegroundColor', foregroundColor, ...
            'Units', 'normalized', ...
            'Position', [0.1 ii*boxheight 0.3 0.1], ...
            'FontWeight', 'bold', ...
            'FontSize', 8, ...
            'FontAngle', 'italic', ...
            'HorizontalAlignment', 'left', ...
            'String', currentlabels{ii});
        GHandle.Viewer.metadata(jj).value(ii) = uicontrol('Parent', GHandle.Viewer.metadata(jj).panel, ...
            'Style', 'text', ...
            'BackgroundColor', backgroundColor, ...
            'ForegroundColor', foregroundColor, ...
            'Units', 'normalized', ...
            'Position', [0.4 ii*boxheight 0.6 0.1], ...
            'FontWeight', 'bold', ...
            'FontAngle', 'italic', ...
            'FontSize', 8, ...
            'String', currentvalues{ii});
    end
end
end

