function viewer(GHandle)

% create the viewer idx

if (isempty(GHandle.Viewer))
	vIdx = 1;
	GHandle.Temp.vIdxList = 1;
else
	vIdx = max(GHandle.Temp.vIdxList) + 1;
	GHandle.Temp.vIdxList = [GHandle.Temp.vIdxList ; vIdx];
end

sortingmethod = 'sortnomo';
dataType = {'AC','DC','phase'};
GHandle.Viewer(vIdx).Data = [GHandle.CurrentDataSet.Data(:,end), GHandle.CurrentDataSet.Data(:,10:30)];

% Set UI objects size


%panelWidth = (1-mainAxesWidth) / 2;
stepW = 0.02;
stepH = 0.02;
panelaxesW = 1-2*stepW;
panelaxesH = 0.7;
%npanels = 4;
%panelW = (1-(npanels+1)*stepW)/npanels;
panelH = 1-panelaxesH-3*stepH;

figurePosition = GHandle.Preference.Figure.sizeLarge;

% Set color theme

backgroundColor = GHandle.Preference.Figure.backgroundColor;
foregroundColor = GHandle.Preference.Figure.foregroundColor;
highlightColor = GHandle.Preference.Figure.highlightColor;


% Set font
defaultFontName = GHandle.Preference.Font.name;

%initialize plot settings
GHandle.Viewer(vIdx).WatchList = ViewerWatchList;



%% Main figure
GHandle.Viewer(vIdx).mainFigure = figure('Position', figurePosition, ...
    'Visible', 'on', ...
    'Resize', 'on',...
    'Name', 'Viewer', ...
    'Numbertitle', 'off', ...
    'Tag', 'sensors_viewer', ...
    'Color', backgroundColor, ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
	'CloseRequestFcn', @(handle, evnt)close_reqest(handle, evnt, GHandle, vIdx),...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL');


%% Menu
GHandle.Viewer(vIdx).menu.menuFile = uimenu('Parent', GHandle.Viewer(vIdx).mainFigure, 'Label', 'File');
GHandle.Viewer(vIdx).menu.menuFile_loadData = uimenu('Parent', GHandle.Viewer(vIdx).menu.menuFile, ...
    'Label', 'Load Data...', ...
    'Callback', @load_data);
GHandle.Viewer(vIdx).menu.menuFile_export = uimenu('Parent', GHandle.Viewer(vIdx).menu.menuFile, ...
    'Label', 'Export');
GHandle.Viewer(vIdx).menu.menuFile_export_export2png = uimenu('Parent', GHandle.Viewer(vIdx).menu.menuFile, ...
    'Label', 'Export to png', ...
    'Callback', @export2png);
GHandle.Viewer(vIdx).menu.menuFile_quit = uimenu('Parent', GHandle.Viewer(vIdx).menu.menuFile, ...
    'Label', 'Quit', ...
    'Callback', {@closewindow, GHandle.Viewer(vIdx).mainFigure});

GHandle.Viewer(vIdx).menu.menuEdit = uimenu('Parent', GHandle.Viewer(vIdx).mainFigure, 'Label', 'Edit');

GHandle.Viewer(vIdx).menu.menuView = uimenu('Parent', GHandle.Viewer(vIdx).mainFigure, 'Label', 'View');
GHandle.Viewer(vIdx).menu.menuView_openTable = uimenu('Parent', GHandle.Viewer(vIdx).menu.menuView, ...
    'Label', 'Open Table...');


%% Toolbar
GHandle.Viewer(vIdx).mainToolbar = uitoolbar('Parent', GHandle.Viewer(vIdx).mainFigure);

img1 = rand(16,16,3);
GHandle.Viewer(vIdx).pushtool1 = uipushtool(GHandle.Viewer(vIdx).mainToolbar,...
    'CData', img1, 'Separator', 'on', ...
    'TooltipString', 'Your toggle tool', ...
    'HandleVisibility', 'off');

img2 = 0.5.*ones(16,16,3);
GHandle.Viewer(vIdx).LockMultipleWiewer  = uitoggletool(GHandle.Viewer(vIdx).mainToolbar,...
    'CData', img2, 'Separator', 'on', ...
    'TooltipString', 'Your toggle tool', ...
	'ClickedCallback',@(handle,evnt)lockmultiplewiewer_callback(handle, evnt, GHandle),...
    'HandleVisibility', 'off');
img3 = rand(16,16,3);
GHandle.Viewer(vIdx).toggletool2 = uitoggletool(GHandle.Viewer(vIdx).mainToolbar,...
    'CData', img3, 'Separator', 'off', ...
    'TooltipString', 'Your toggle tool', ...
    'HandleVisibility', 'off');
img4 = rand(16,16,3);
GHandle.Viewer(vIdx).toggletool3 = uitoggletool(GHandle.Viewer(vIdx).mainToolbar,...
    'CData', img4, 'Separator', 'off', ...
    'TooltipString', 'Your toggle tool', ...
    'HandleVisibility', 'off');

%% Panels
panellabels = {'Measure', 'Subject', 'Probe', 'Selected Channel'};

labels = {...
          {'Measure ID', 'Duration', 'Samples', 'Sampling Rate'}, ...
          {'pippo', 'pluto'}, ...
          {'topolino', 'paperino', 'qui', 'quo', 'qua'}, ...
          {'archimede', 'Average', 'Average window'}, ...
         };

 
	 
values = {...
          {GHandle.CurrentDataSet.Measure.id, [num2str(GHandle.CurrentDataSet.Measure.timeLength) ' s'], num2str(height(GHandle.CurrentDataSet.Data)), [num2str(GHandle.CurrentDataSet.Measure.updateRate) ' Hz']}, ...
          {'pippo', 'pluto'}, ...
          {'topolino', 'paperino', 'qui', 'quo', 'qua'}, ...
          {'archimede', '-', '-'}, ...
         }; 
	 
	 
npanels = length(panellabels);
panelwidth = (1-(npanels+1)*stepW)/npanels;

for jj = 1:1:npanels
    
    panel_position = [jj*stepW+(jj-1)*panelwidth stepH panelwidth panelH];
    GHandle.Viewer(vIdx).metadata(jj).panel = uipanel('parent', GHandle.Viewer(vIdx).mainFigure,...
        'Position', panel_position, ...
        'Units', 'normalized', ...
        'BackgroundColor', backgroundColor, ...
        'ForegroundColor', foregroundColor, ...
        'HighlightColor', highlightColor, ...
        'ShadowColor', [211 211 211]/255, ...
        'BorderType', 'line', ...
        'FontWeight', 'bold', ...
        'FontSize', 8, ...
        'FontName', defaultFontName, ...
        'Visible', 'on', ...
        'Title', panellabels{jj});
    
    currentlabels = fliplr(labels{1,jj});
	currentvalues = fliplr(values{1,jj});
	
    nlines = length(currentlabels);
    boxheight = 1/(nlines+3);
    for ii = 1:1:nlines
        GHandle.Viewer(vIdx).metadata(jj).label(ii) = uicontrol('Parent', GHandle.Viewer(vIdx).metadata(jj).panel, ...
            'Style', 'text', ...
            'BackgroundColor', backgroundColor, ...
            'ForegroundColor', foregroundColor, ...
            'Units', 'normalized', ...
            'Position', [0.1 (ii+1)*boxheight 0.3 0.1], ...
            'FontWeight', 'bold', ...
            'FontSize', 8, ...
            'FontAngle', 'italic', ...
            'HorizontalAlignment', 'left', ...
            'String', currentlabels{ii});
        GHandle.Viewer(vIdx).metadata(jj).value(ii) = uicontrol('Parent', GHandle.Viewer(vIdx).metadata(jj).panel, ...
            'Style', 'text', ...
            'BackgroundColor', backgroundColor, ...
            'ForegroundColor', foregroundColor, ...
            'Units', 'normalized', ...
            'Position', [0.4 (ii+1)*boxheight 0.6 0.1], ...
            'FontWeight', 'bold', ...
            'FontAngle', 'italic', ...
            'FontSize', 8, ...
            'String', currentvalues{ii});
    end
end

% Type selector
GHandle.Viewer(vIdx).DataTypeSelectorlabel = uicontrol('Parent', GHandle.Viewer(vIdx).metadata(1).panel, ...
            'Style', 'text', ...
            'BackgroundColor', backgroundColor, ...
            'ForegroundColor', foregroundColor, ...
            'Units', 'normalized', ...
            'Position', [0.1 boxheight 0.3 0.1], ...
            'FontWeight', 'bold', ...
            'FontSize', 8, ...
            'FontAngle', 'italic', ...
            'HorizontalAlignment', 'left', ...
            'String', 'Data Type');
		
GHandle.Viewer(vIdx).DataTypeSelector = uicontrol('Parent', GHandle.Viewer(vIdx).metadata(1).panel, ...
            'Style', 'popup',...
            'BackgroundColor', backgroundColor, ...
            'ForegroundColor', foregroundColor, ...
            'Units', 'normalized', ...
            'Position', [0.45 boxheight 0.5 0.1], ...
            'FontWeight', 'bold', ...
            'String',dataType);

%% Tabs
GHandle.Viewer(vIdx).tabs.group = uitabgroup(GHandle.Viewer(vIdx).mainFigure, 'Position',[stepW panelH+2*stepH panelaxesW panelaxesH]);
GHandle.Viewer(vIdx).tabs.time = uitab('Parent', GHandle.Viewer(vIdx).tabs.group, ...
    'Title', 'Time', ...
    'BackgroundColor', [1 0 0], ...
    'ForegroundColor', foregroundColor);
GHandle.Viewer(vIdx).tabs.frequency = uitab(GHandle.Viewer(vIdx).tabs.group, ...
    'Title', 'Spectrum', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor);
GHandle.Viewer(vIdx).tabs.timefrequency = uitab(GHandle.Viewer(vIdx).tabs.group, ...
    'Title', 'Time-Frequency', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor);
GHandle.Viewer(vIdx).tabs.video = uitab(GHandle.Viewer(vIdx).tabs.group, ...
    'Title', 'Videos', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor);
GHandle.Viewer(vIdx).tabs.preference = uitab(GHandle.Viewer(vIdx).tabs.group, ...
    'Title', 'Preference', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor);


%% Time tab
%panelaxes_position = [stepW panelH+2*stepH panelaxesW panelaxesH];
panelaxes_position = [0 0 1 1];
GHandle.Viewer(vIdx).timeplot.panel = uipanel('parent', GHandle.Viewer(vIdx).tabs.time,...
    'Position', panelaxes_position, ...
    'Units', 'normalized', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'HighlightColor', highlightColor, ...
    'ShadowColor', [211 211 211]/255, ...
    'BorderType', 'none', ...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', defaultFontName, ...
    'Visible', 'on');


GHandle.Viewer(vIdx).timeplot.bigaxes1 = axes('parent', GHandle.Viewer(vIdx).timeplot.panel,...
    'Position', [0.07 0.22 0.88 0.66], ...
    'Units', 'normalized', ...
    'Color', backgroundColor, ...
    'XColor', foregroundColor, ...
    'YColor', foregroundColor, ...
    'Xgrid', 'on', ...
    'Ygrid', 'on', ...
    'GridColor', foregroundColor, ...
	'NextPlot', 'add',...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', defaultFontName, ...
    'Visible', 'on', ...
    'Title', 'Main plots');

GHandle.Viewer(vIdx).timeplot.bigaxes2 = axes('parent', GHandle.Viewer(vIdx).timeplot.panel,...
    'Position', [0.07 0.22 0.88 0.66], ...
    'Units', 'normalized', ...
    'Color', backgroundColor, ...
    'XColor', foregroundColor, ...
    'YColor', foregroundColor, ...
    'Xgrid', 'off', ...
    'Ygrid', 'off', ...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
	'NextPlot', 'add',...
    'GridColor', foregroundColor, ...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', defaultFontName, ...
    'Visible', 'on', ...
    'Title', 'Main plots');

GHandle.Viewer(vIdx).timeplot.smallaxes = axes('parent', GHandle.Viewer(vIdx).timeplot.panel,...
    'Units', 'normalized', ...
    'Position', [0.1 0.04 0.8 0.07], ...
    'Color', backgroundColor, ...
    'Color', backgroundColor, ...
    'XColor', foregroundColor, ...
    'YColor', foregroundColor, ...
	'NextPlot', 'add',...
    'GridColor', foregroundColor, ...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', defaultFontName, ...   
    'Visible', 'off', ...
    'Box', 'on', ...
    'XLimMode', 'auto', ...
    'YLimMode', 'auto', ...
    'XGrid', 'off', ...
    'YGrid', 'off');

GHandle.Viewer(vIdx).timeplot.spectrumaxes = axes('parent', GHandle.Viewer(vIdx).timeplot.panel,...
    'Position', [0.8 0.7 0.15 0.15], ...
    'Units', 'normalized', ...
    'Color', [backgroundColor 0], ...
    'XColor', foregroundColor, ...
    'YColor', foregroundColor, ...
    'Xgrid', 'off', ...
    'Ygrid', 'off', ...
	'NextPlot', 'add',...
    'GridColor', foregroundColor, ...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', defaultFontName, ...
    'Box', 'off', ...
    'Visible', 'off', ...
    'Title', 'Spectrum');


GHandle.Viewer(vIdx).timeplot.editmin = uicontrol('Parent', GHandle.Viewer(vIdx).timeplot.panel, ...
    'Style', 'edit', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.06 0.04 0.05], ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
	'Tag','min',...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
    'String', 'min');

GHandle.Viewer(vIdx).timeplot.editmax = uicontrol('Parent', GHandle.Viewer(vIdx).timeplot.panel, ...
    'Style', 'edit', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.91 0.06 0.04 0.05], ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
	'Tag','max',...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
    'String', 'max');

GHandle.Viewer(vIdx).timeplot.buttonBwall = uicontrol('Parent', GHandle.Viewer(vIdx).timeplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.03 0.03 0.02 0.08], ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
	'Tag','F',...
    'String', 'F');
GHandle.Viewer(vIdx).timeplot.buttonBw10 = uicontrol('Parent', GHandle.Viewer(vIdx).timeplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.03 0.02 0.03], ...
	'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
	'Tag','<<',...
    'String', '<<');
GHandle.Viewer(vIdx).timeplot.buttonBw1 = uicontrol('Parent', GHandle.Viewer(vIdx).timeplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.07 0.03 0.02 0.03], ...
	'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
	'Tag','<',...
    'String', '<');
GHandle.Viewer(vIdx).timeplot.buttonFwall = uicontrol('Parent', GHandle.Viewer(vIdx).timeplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.95 0.03 0.02 0.08], ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
	'Tag','L',...
    'String', 'L');
GHandle.Viewer(vIdx).timeplot.buttonFw10 = uicontrol('Parent', GHandle.Viewer(vIdx).timeplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.93 0.03 0.02 0.03], ...
	'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
	'Tag','>>',...
    'String', '>>');
GHandle.Viewer(vIdx).timeplot.buttonFw1 = uicontrol('Parent', GHandle.Viewer(vIdx).timeplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.91 0.03 0.02 0.03], ...
	'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_time_window, GHandle, vIdx}, ...
	'Tag','>',...
    'String', '>');




%% Spectrum tab

panelaxes_position = [0 0 1 1];
GHandle.Viewer(vIdx).spectrumplot.panel = uipanel('parent', GHandle.Viewer(vIdx).tabs.frequency,...
    'Position', panelaxes_position, ...
    'Units', 'normalized', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'HighlightColor', highlightColor, ...
    'ShadowColor', [211 211 211]/255, ...
    'BorderType', 'none', ...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', defaultFontName, ...
    'Visible', 'on');


GHandle.Viewer(vIdx).spectrumplot.bigaxes1 = axes('parent', GHandle.Viewer(vIdx).spectrumplot.panel,...
    'Position', [0.07 0.22 0.88 0.66], ...
    'Units', 'normalized', ...
    'Color', backgroundColor, ...
    'XColor', foregroundColor, ...
    'YColor', foregroundColor, ...
    'Xgrid', 'on', ...
    'Ygrid', 'on', ...
	'NextPlot', 'add',...
    'GridColor', foregroundColor, ...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', defaultFontName, ...
    'Visible', 'on', ...
    'Title', 'Main plots');

GHandle.Viewer(vIdx).spectrumplot.bigaxes2 = axes('parent', GHandle.Viewer(vIdx).spectrumplot.panel,...
    'Position', [0.07 0.22 0.88 0.66], ...
    'Units', 'normalized', ...
    'Color', backgroundColor, ...
    'XColor', foregroundColor, ...
    'YColor', foregroundColor, ...
    'Xgrid', 'off', ...
    'Ygrid', 'off', ...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
	'NextPlot', 'add',...
    'GridColor', foregroundColor, ...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', defaultFontName, ...
    'Visible', 'off', ...
    'Title', 'Main plots');

GHandle.Viewer(vIdx).spectrumplot.smallaxes = axes('parent', GHandle.Viewer(vIdx).spectrumplot.panel,...
    'Units', 'normalized', ...
    'Position', [0.1 0.04 0.8 0.07], ...
    'Color', backgroundColor, ...
    'Color', backgroundColor, ...
    'XColor', foregroundColor, ...
    'YColor', foregroundColor, ...
	'NextPlot', 'add',...
    'GridColor', foregroundColor, ...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', defaultFontName, ...   
    'Visible', 'off', ...
    'Box', 'on', ...
    'XLimMode', 'auto', ...
    'YLimMode', 'auto', ...
    'XGrid', 'off', ...
    'YGrid', 'off');

GHandle.Viewer(vIdx).spectrumplot.spectrumaxes = axes('parent', GHandle.Viewer(vIdx).spectrumplot.panel,...
    'Position', [0.8 0.7 0.15 0.15], ...
    'Units', 'normalized', ...
    'Color', [backgroundColor 0], ...
    'XColor', foregroundColor, ...
    'YColor', foregroundColor, ...
    'Xgrid', 'off', ...
    'Ygrid', 'off', ...
	'NextPlot', 'add',...
    'GridColor', foregroundColor, ...
    'FontWeight', 'bold', ...
    'FontSize', 8, ...
    'FontName', defaultFontName, ...
    'Box', 'off', ...
    'Visible', 'off', ...
    'Title', 'Spectrum');


GHandle.Viewer(vIdx).spectrumplot.editmin = uicontrol('Parent', GHandle.Viewer(vIdx).spectrumplot.panel, ...
    'Style', 'edit', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.06 0.04 0.05], ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
	'Tag','min',...
    'Callback', {@move_spectrum_window, GHandle, vIdx}, ...
    'String', 'min');

GHandle.Viewer(vIdx).spectrumplot.editmax = uicontrol('Parent', GHandle.Viewer(vIdx).spectrumplot.panel, ...
    'Style', 'edit', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.91 0.06 0.04 0.05], ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
	'Tag','max',...
    'Callback', {@move_spectrum_window, GHandle, vIdx}, ...
    'String', 'max');

GHandle.Viewer(vIdx).spectrumplot.buttonBwall = uicontrol('Parent', GHandle.Viewer(vIdx).spectrumplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.03 0.03 0.02 0.08], ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_spectrum_window, GHandle, vIdx}, ...
	'Tag','F',...
    'String', 'F');
GHandle.Viewer(vIdx).spectrumplot.buttonBw10 = uicontrol('Parent', GHandle.Viewer(vIdx).spectrumplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.03 0.02 0.03], ...
	'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_spectrum_window, GHandle, vIdx}, ...
	'Tag','<<',...
    'String', '<<');
GHandle.Viewer(vIdx).spectrumplot.buttonBw1 = uicontrol('Parent', GHandle.Viewer(vIdx).spectrumplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.07 0.03 0.02 0.03], ...
	'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_spectrum_window, GHandle, vIdx}, ...
	'Tag','<',...
    'String', '<');
GHandle.Viewer(vIdx).spectrumplot.buttonFwall = uicontrol('Parent', GHandle.Viewer(vIdx).spectrumplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.95 0.03 0.02 0.08], ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_spectrum_window, GHandle, vIdx}, ...
	'Tag','L',...
    'String', 'L');
GHandle.Viewer(vIdx).spectrumplot.buttonFw10 = uicontrol('Parent', GHandle.Viewer(vIdx).spectrumplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.93 0.03 0.02 0.03], ...
	'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_spectrum_window, GHandle, vIdx}, ...
	'Tag','>>',...
    'String', '>>');
GHandle.Viewer(vIdx).spectrumplot.buttonFw1 = uicontrol('Parent', GHandle.Viewer(vIdx).spectrumplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.91 0.03 0.02 0.03], ...
	'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_spectrum_window, GHandle, vIdx}, ...
	'Tag','>',...
    'String', '>');

%% Time-frequency tab

panelaxes_position = [0 0 1 1];
GHandle.Viewer(vIdx).timefrequencyplot.panel = uipanel('parent', GHandle.Viewer(vIdx).tabs.timefrequency,...
    'Position', panelaxes_position, ...
    'Units', 'normalized', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'HighlightColor', highlightColor, ...
    'ShadowColor', [211 211 211]/255, ...
    'BorderType', 'none', ...
    'FontWeight', 'bold', ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontName', defaultFontName, ...
    'Visible', 'on');

GHandle.Viewer(vIdx).timefrequencyplot.bigaxes1 = axes('parent', GHandle.Viewer(vIdx).timefrequencyplot.panel,...
    'Position', [0.07 0.22 0.88 0.66], ...
    'Units', 'normalized', ...
    'Color', backgroundColor, ...
    'XColor', foregroundColor, ...
    'YColor', foregroundColor, ...
    'Xgrid', 'on', ...
    'Ygrid', 'on', ...
	'NextPlot', 'add',...
    'GridColor', foregroundColor, ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontName', defaultFontName, ...
    'Visible', 'on', ...
    'Title', 'Main plots');

GHandle.Viewer(vIdx).timefrequencyplot.bigaxes2 = axes('parent', GHandle.Viewer(vIdx).timefrequencyplot.panel,...
    'Position', [0.07 0.22 0.88 0.66], ...
    'Units', 'normalized', ...
    'Color', backgroundColor, ...
    'XColor', foregroundColor, ...
    'YColor', foregroundColor, ...
    'Xgrid', 'off', ...
    'Ygrid', 'off', ...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
	'NextPlot', 'add',...
    'GridColor', foregroundColor, ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontName', defaultFontName, ...
    'Visible', 'off', ...
    'Title', 'Main plots');

GHandle.Viewer(vIdx).timefrequencyplot.smallaxes = axes('parent', GHandle.Viewer(vIdx).timefrequencyplot.panel,...
    'Units', 'normalized', ...
    'Position', [0.1 0.04 0.8 0.07], ...
    'Color', backgroundColor, ...
    'Color', backgroundColor, ...
    'XColor', foregroundColor, ...
    'YColor', foregroundColor, ...
	'NextPlot', 'add',...
    'GridColor', foregroundColor, ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontName', defaultFontName, ...   
    'Visible', 'off', ...
    'Box', 'on', ...
    'XLimMode', 'auto', ...
    'YLimMode', 'auto', ...
    'XGrid', 'off', ...
    'YGrid', 'off');

GHandle.Viewer(vIdx).timefrequencyplot.spectrumaxes = axes('parent', GHandle.Viewer(vIdx).timefrequencyplot.panel,...
    'Position', [0.8 0.7 0.15 0.15], ...
    'Units', 'normalized', ...
    'Color', [backgroundColor 0], ...
    'XColor', foregroundColor, ...
    'YColor', foregroundColor, ...
    'Xgrid', 'off', ...
    'Ygrid', 'off', ...
	'NextPlot', 'add',...
    'GridColor', foregroundColor, ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontName', defaultFontName, ...
    'Box', 'off', ...
    'Visible', 'off', ...
    'Title', 'Spectrum');


GHandle.Viewer(vIdx).timefrequencyplot.editmin = uicontrol('Parent', GHandle.Viewer(vIdx).timefrequencyplot.panel, ...
    'Style', 'edit', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.06 0.04 0.05], ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@set_time_window_min, GHandle, vIdx}, ...
    'String', 'min');

GHandle.Viewer(vIdx).timefrequencyplot.editmax = uicontrol('Parent', GHandle.Viewer(vIdx).timefrequencyplot.panel, ...
    'Style', 'edit', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.91 0.06 0.04 0.05], ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@set_time_window_max, GHandle, vIdx}, ...
    'String', 'max');

GHandle.Viewer(vIdx).timefrequencyplot.buttonBwall = uicontrol('Parent', GHandle.Viewer(vIdx).timefrequencyplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.03 0.03 0.02 0.08], ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_window, GHandle, vIdx}, ...
    'String', 'F');
GHandle.Viewer(vIdx).timefrequencyplot.buttonBw10 = uicontrol('Parent', GHandle.Viewer(vIdx).timefrequencyplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.03 0.02 0.03], ...
	'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_window, GHandle, vIdx}, ...
    'String', '<<');
GHandle.Viewer(vIdx).timefrequencyplot.buttonBw1 = uicontrol('Parent', GHandle.Viewer(vIdx).timefrequencyplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.07 0.03 0.02 0.03], ...
	'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_window, GHandle, vIdx}, ...
    'String', '<');
GHandle.Viewer(vIdx).timefrequencyplot.buttonFwall = uicontrol('Parent', GHandle.Viewer(vIdx).timefrequencyplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.95 0.03 0.02 0.08], ...
	'FontSize',GHandle.Preference.Font.sizeL,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_window, GHandle, vIdx}, ...
    'String', 'L');
GHandle.Viewer(vIdx).timefrequencyplot.buttonFw10 = uicontrol('Parent', GHandle.Viewer(vIdx).timefrequencyplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.93 0.03 0.02 0.03], ...
	'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_window, GHandle, vIdx}, ...
    'String', '>>');
GHandle.Viewer(vIdx).timefrequencyplot.buttonFw1 = uicontrol('Parent', GHandle.Viewer(vIdx).timefrequencyplot.panel, ...
    'Style', 'pushbutton', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor', foregroundColor, ...
    'Units', 'normalized', ...
    'Position', [0.91 0.03 0.02 0.03], ...
	'FontSize',GHandle.Preference.Font.sizeS,...
    'FontWeight', 'bold', ...
    'FontAngle', 'italic', ...
    'Callback', {@move_window, GHandle, vIdx}, ...
    'String', '>');

%% Plot parameters

% channelNames = GHandle.CurrentDataSet.Data.Properties.VariableNames;
% 
% 
% nsamples = height(GHandle.CurrentDataSet.Data);
% 
% timeline_samples = linspace(1, nsamples, nsamples);
% 
% channelLabels = channelNames(columns_DC);


GHandle.Viewer(vIdx).WatchList.colorLine = sorting_colors(20, sortingmethod);

%% Time & Spectrum Plot
% Main plot
% axes(GHandle.Viewer(vIdx).timeplot.bigaxes1)
% axis tight
% cla;
% hold on

GHandle.Viewer(vIdx).listener = addlistener(GHandle.Viewer(vIdx).WatchList,'time2Plot','PostSet',@(src,evnt)timeplot(src,evnt,GHandle, vIdx));
GHandle.Viewer(vIdx).listener = addlistener(GHandle.Viewer(vIdx).WatchList,'spectrum2Plot','PostSet',@(src,evnt)spectrumplot(src,evnt,GHandle, vIdx));
GHandle.Viewer(vIdx).listener = addlistener(GHandle.Viewer(vIdx).WatchList,'timefreq2Plot','PostSet',@(src,evnt)timefreqplot(src,evnt,GHandle, vIdx));
GHandle.Viewer(vIdx).listener = addlistener(GHandle.Viewer(vIdx).WatchList,'edvLine','PostSet',@(src,evnt)change_width(src,evnt,GHandle, vIdx));
GHandle.Viewer(vIdx).listener = addlistener(GHandle.Viewer(vIdx).WatchList,'timeLim','PostSet',@(src,evnt)set_time_lim(src,evnt,GHandle, vIdx));

GHandle.Viewer(vIdx).WatchList.time2Plot = GHandle.Viewer(vIdx).Data;

[power, f] = pspectrum(ydata, GHandle.CurrentDataSet.Measure.updateRate);
%% Time-Frequency plot
% Main plot
axes(GHandle.Viewer(vIdx).timefrequencyplot.bigaxes1)
axis tight
cla;


ydata = nirsdata(:,1);


[sp,fp,tp] = pspectrum(ydata, GHandle.CurrentDataSet.Measure.updateRate, 'spectrogram');

surf(tp,fp,sp,sp)
view(107,30)
xlabel('Time (s)')
ylabel('Frequency (Hz)')
%rotate3d on


%% Turn figure on
GHandle.Viewer(vIdx).mainFigure.Visible = 'on';
end

function close_reqest(Handle, ~, GHandle, vIdx)
	delete(Handle);
	GHandle.Temp.vIdxList(GHandle.Temp.vIdxList == vIdx) = [];
	%GHandle.Viewer(vIdx) = []; add a method to remove the garbage
	if isempty (GHandle.Temp.vIdxList)
		GHandle.Viewer = [];
	end
end


function lockmultiplewiewer_callback(handle, ~, GHandle)
	state = handle.State;
	for idx = GHandle.Temp.vIdxList'
		GHandle.Viewer(idx).LockMultipleWiewer.State = state;
	end
end






















