function maingui(GHandle)
%% create the mean figure
	GHandle.Main.Figure = figure('Visible', 'off', ...
		'position', GHandle.Preference.Figure.sizeLarge,...
		'Resize', 'on',...
		'Name', 'GNirs', ...
		'SizeChangedFcn',{@resizecheck,GHandle},...
		'Numbertitle', 'off', ...
		'Color', GHandle.Preference.Figure.backgroundColor, ...
		'Toolbar', 'none', ...
		'Menubar', 'none', ...
		'DoubleBuffer', 'on', ...
		'DockControls', 'off', ...
		'Renderer', 'OpenGL');

	toolbar(GHandle);

	GHandle.Main.Display.Pannel = uipanel (...
		'Title', '', ...
		'Parent', GHandle.Main.Figure,...
		'Units', 'normalized',...
		'Visible', 'on',...
		'Position',[0.21 0.01 0.78 0.88]);

	
	tree(GHandle);
	%% display the figure and close the loading figure
	GHandle.Main.Figure.Visible = 'on';
	
end

