function maingui(GHandle)
%% create the mean figure

%textForegroundColor = GHandle.Preference.Theme.foregroundColor;
textForegroundColor = [0 0 0];
backgroundColor = [.9 .9 .9];
panelColor = GHandle.Preference.Theme.panelColor;

GHandle.Main.Figure = figure('Visible', 'off', ...
    'position', GHandle.Preference.Figure.sizeLarge, ...
    'Resize', 'on', ...
    'Name', 'YottaNIRS', ...
    'SizeChangedFcn',{@resizecheck,GHandle}, ...
    'Numbertitle', 'off', ...
    'Color', GHandle.Preference.Theme.backgroundColor, ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL');

%create the tree
GHandle.Main.Tree.TabGroup = uitabgroup(GHandle.Main.Figure,...
    'Position',[0 0 0.2 1]);
GHandle.Main.Tree.StudyTab = uitab(GHandle.Main.Tree.TabGroup,...
    'Title','Study', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor',  textForegroundColor);
GHandle.Main.Tree.ProbeTab = uitab(GHandle.Main.Tree.TabGroup,...
    'Title','Probe', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor',  textForegroundColor);
GHandle.Main.Tree.AtlasTab = uitab(GHandle.Main.Tree.TabGroup,...
    'Title','Atlas', ...
    'BackgroundColor', backgroundColor, ...
    'ForegroundColor',  textForegroundColor);
tree(GHandle);

% create the tab
GHandle.Main.Display.Panel = uipanel (...
    'Title', '', ...
    'BackgroundColor', panelColor, ...
    'Parent', GHandle.Main.Figure, ...
    'Units', 'normalized', ...
    'BorderType','none',...
    'Visible', 'on', ...
    'Position',[0.2 0 0.8 1]);
%% display the figure and close the loading figure
GHandle.Main.Figure.Visible = 'on';

end

