function newstudy(~, ~, GHandle)
	
	figureSize = GHandle.Preference.Figure.sizeMedium;


	GHandle.TempWindow.NewStudyFigure = figure(...
	'position', figureSize,...
    'Resize', 'on',...
    'Name', 'New NIRS Study', ...
    'Numbertitle', 'off', ...
    'Toolbar', 'none', ...
    'Menubar', 'none', ...
    'DoubleBuffer', 'on', ...
    'DockControls', 'off', ...
    'Renderer', 'OpenGL',...
	'Visible', 'off' ...
	);
	
	GHandle.TempWindow.NewStudyName = uiw.widget.EditableText(...      
    'Parent',GHandle.TempWindow.NewStudyFigure,...=
    'Value','Insert Name',...
    'Callback',@(h,e)disp(e),...
    'Label','Study Name:',...
    'LabelLocation','top',...
    'LabelWidth',90,...
    'Units','normalized',...
    'Position',[0.05 0.80 0.35 0.15]);

	GHandle.TempWindow.NewStudyListBox = uicontrol(...
			'Parent', GHandle.TempWindow.NewStudyFigure, ...
			'Style','listbox',...
			'Units', 'normalize', ...
			'Max', 2,...
			'Position',  [0.05 0.05 0.4 0.55],...
			'String',[],...
			'Value',[]);

	GHandle.TempWindow.NewStudySelector = uiw.widget.FolderSelector(...
    'Parent', GHandle.TempWindow.NewStudyFigure, ...
    'Value', [], ...
    'Label','Choose a data file:', ...
    'LabelLocation','top',...
    'LabelWidth',150,...
    'Units', 'normalize', ...
    'Position', [0.05 0.60 0.4 0.15],...	
	'Callback',@(ObjectHandle, Event)foudfile(ObjectHandle, Event,StudyFigure)...
	);

	
	

	GHandle.TempWindow.NewStudyLoadButton = uicontrol('Style', 'pushbutton',...	
    'Parent', GHandle.TempWindow.NewStudyFigure, ...
	'String', 'Load',...
	'Units', 'normalize', ...
	'Position', [0.8 0.15 0.2 0.1],...
	'Callback', {@AddStudytoDataBase ,GHandle}); 

	

	GHandle.TempWindow.NewStudyFigure.Visible = 'on';



	

end

